(function(){
  function categoryMarkup(cat){
    const c=cat||{tipo:'Saída',tipoGasto:'Essencial'};
    return `<div class="field"><label>Nome</label><input type="text" id="f-cat-nome" value="${esc(c.nome)}" placeholder="Ex: 🍿 Lazer"></div><div class="form-row"><div class="field"><label>Tipo</label><select id="f-cat-tipo"><option value="Saída" ${c.tipo==='Saída'?'selected':''}>Saída</option><option value="Entrada" ${c.tipo==='Entrada'?'selected':''}>Entrada</option></select></div><div class="field"><label>Tipo de gasto</label><select id="f-cat-gasto"><option value="Essencial" ${c.tipoGasto==='Essencial'?'selected':''}>Essencial</option><option value="Não Essencial" ${c.tipoGasto==='Não Essencial'?'selected':''}>Não Essencial</option></select></div></div><div class="field"><label>Orçado por mês</label><input type="number" step="0.01" min="0" id="f-cat-orcado" value="${c.orcado?fromCents(c.orcado):''}"></div><div class="form-error" id="cat-error" role="alert"></div><div class="modal-actions"><button class="btn btn-ghost" id="cf-form-cancel">Cancelar</button><button class="btn btn-primary" id="cf-form-save">Salvar</button></div>`;
  }
  function openCategoryForm(cat){
    openModal(cat?'Editar categoria':'Nova categoria',categoryMarkup(cat),()=>{document.getElementById('cf-form-cancel').onclick=closeModal;document.getElementById('cf-form-save').onclick=async()=>{const nome=document.getElementById('f-cat-nome').value.trim();if(!nome){document.getElementById('cat-error').textContent='Informe o nome da categoria.';return;}const payload={id:cat?cat.id:uid('cat'),nome,tipo:document.getElementById('f-cat-tipo').value,tipoGasto:document.getElementById('f-cat-gasto').value,orcado:toCents(document.getElementById('f-cat-orcado').value)};if(cat){const idx=state.categorias.findIndex(x=>x.id===cat.id);state.categorias[idx]=payload;}else state.categorias.push(payload);registrarHistorico(cat?'edicao_categoria':'criacao_categoria',`${cat?'Categoria editada':'Categoria criada'}: ${nome}`);await saveData();closeModal();render();};});
  }
  function accountMarkup(conta){
    const c=conta||{dataSaldoInicial:todayLocal()};
    return `<div class="field"><label>Nome</label><input type="text" id="f-conta-nome" value="${esc(c.nome)}" placeholder="Ex: Nubank"></div><div class="form-row"><div class="field"><label>Saldo inicial</label><input type="number" step="0.01" id="f-conta-saldo" value="${c.saldoInicial!=null?fromCents(c.saldoInicial):''}"></div><div class="field"><label>Data do saldo</label><input type="date" id="f-conta-data" value="${c.dataSaldoInicial}"></div></div><div class="form-error" id="conta-error" role="alert"></div><div class="modal-actions"><button class="btn btn-ghost" id="ctf-cancel">Cancelar</button><button class="btn btn-primary" id="ctf-save">Salvar</button></div>`;
  }
  function openAccountForm(conta){
    openModal(conta?'Editar conta':'Nova conta',accountMarkup(conta),()=>{document.getElementById('ctf-cancel').onclick=closeModal;document.getElementById('ctf-save').onclick=async()=>{const nome=document.getElementById('f-conta-nome').value.trim(),error=document.getElementById('conta-error');if(!nome){error.textContent='Informe o nome da conta.';return;}if(!document.getElementById('f-conta-data').value){error.textContent='Informe a data do saldo inicial.';return;}const payload={id:conta?conta.id:uid('conta'),nome,saldoInicial:toCents(document.getElementById('f-conta-saldo').value),dataSaldoInicial:document.getElementById('f-conta-data').value};if(conta){const idx=state.contas.findIndex(x=>x.id===conta.id);state.contas[idx]=payload;}else state.contas.push(payload);registrarHistorico(conta?'edicao_conta':'criacao_conta',`${conta?'Conta editada':'Conta criada'}: ${nome}`);await saveData();closeModal();render();};});
  }
  window.openCategoryForm=openCategoryForm;
  window.openAccountForm=openAccountForm;
})();
