const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const context={window:{}};vm.createContext(context);const analysisFiles=['js/services/analysis/core.js','js/services/analysis/recurring.js','js/services/analysis/commitment.js','js/services/analysis/reserve.js','js/services/analysis/quality.js','js/services/analysis/anomaly.js','js/services/analysis/concentration.js','js/services/analysis/index.js'];for(const file of ['js/financial-core.js','js/services/future.js',...analysisFiles,'js/services/daily-cashflow.js'])vm.runInContext(fs.readFileSync(file,'utf8'),context,{filename:file});
assert.equal(context.window.FinTrackAnalysisInternals,undefined,'detalhes internos não devem permanecer na API global');assert.deepEqual(Object.keys(context.window.AnalysisService),['recurringExpenses','futureCommitment','emergencyReserve','dataQuality','monthAnomaly','expenseConcentration']);
const months=['2026-01-05','2026-02-04','2026-03-06'];
const data={contas:[{id:'a',nome:'Conta',saldoInicial:100000,dataSaldoInicial:'2025-01-01'}],categorias:[{id:'c',nome:'Serviços',tipo:'Saída',essencial:true}],lancamentos:months.map((date,index)=>({id:`r${index}`,tipo:'Despesa',tipoOperacao:'despesa',status:'Pago',data:date,valor:4000+index*10,descricao:'Streaming 123',categoriaId:'c',contaId:'a'})),planejamentos:{'2026-04':{receita:200000,investimento:20000,orcamentos:{c:50000}}},fechamentos:{},ativosInvestimento:[],dividas:[],despesasAnuais:[],recurrenceDecisions:[]};
const before=JSON.stringify(data),recurring=context.window.AnalysisService.recurringExpenses(data,{today:'2026-04-01'});assert.equal(recurring.evidence.detected.length,1);assert.equal(recurring.evidence.detected[0].anual,recurring.evidence.detected[0].mensal*12);assert.equal(JSON.stringify(data),before,'análises devem ser puras');
const commitment=context.window.AnalysisService.futureCommitment(data,{startMonth:'2026-04',months:1});assert.equal(commitment.metrics.length,1);assert.equal(commitment.metrics[0].commitmentRate,35);
const daily=context.window.DailyCashflowService.project(data,'2026-04',{today:'2026-04-01'});assert.equal(daily.length,30);assert.ok(daily.every(item=>['normal','atencao','critico'].includes(item.status)));
assert.equal(context.window.AnalysisService.monthAnomaly(data,{month:'2026-04'}).status,'indisponivel');assert.equal(context.window.AnalysisService.expenseConcentration(data,{month:'2026-04'}).status,'indisponivel');
const reserveData={...data,fechamentos:Object.fromEntries(['2026-01','2026-02','2026-03'].map(month=>[month,{status:'fechado',snapshot:{receitas:100000,despesas:20000,lancamentosDetalhados:[{tipo:'Despesa',categoriaId:'c',valor:20000}]}}])),operacoes:[{id:'oa',status:'concluida'},{id:'or',status:'concluida'},{id:'ox',status:'estornada'}],lancamentos:[...data.lancamentos,{id:'a',operacaoId:'oa',aporteReservaEmergencia:true,tipoOperacao:'investimento',movimentoInvestimento:'aporte',status:'Pago',data:'2026-03-01',valor:60000},{id:'r',operacaoId:'or',aporteReservaEmergencia:true,tipoOperacao:'investimento',movimentoInvestimento:'resgate',status:'Pago',data:'2026-03-02',valor:12000},{id:'x',operacaoId:'ox',aporteReservaEmergencia:true,tipoOperacao:'investimento',movimentoInvestimento:'aporte',status:'Pago',data:'2026-03-03',valor:99999},{id:'old',aporteReservaEmergencia:false,tipoOperacao:'investimento',movimentoInvestimento:'aporte',status:'Pago',data:'2026-03-04',valor:99999}]};const reserve=context.window.AnalysisService.emergencyReserve(reserveData,{atDate:'2026-04-01'});assert.equal(reserve.evidence.aporteTotal,60000);assert.equal(reserve.evidence.resgateTotal,12000);assert.equal(reserve.evidence.contributionAverage,8000);
const reserveEdges={...reserveData,lancamentos:[...reserveData.lancamentos,{id:'pending',operacaoId:'oa',aporteReservaEmergencia:true,tipoOperacao:'investimento',movimentoInvestimento:'aporte',status:'Pendente',data:'2026-03-05',valor:70000},{id:'wrong-kind',operacaoId:'oa',aporteReservaEmergencia:true,tipoOperacao:'despesa',movimentoInvestimento:'aporte',status:'Pago',data:'2026-03-06',valor:80000},{id:'window-start',operacaoId:'oa',aporteReservaEmergencia:true,tipoOperacao:'investimento',movimentoInvestimento:'aporte',status:'Pago',data:'2025-11-01',valor:6000},{id:'before-window',operacaoId:'oa',aporteReservaEmergencia:true,tipoOperacao:'investimento',movimentoInvestimento:'aporte',status:'Pago',data:'2025-10-31',valor:90000}]};const reserveAtEdges=context.window.AnalysisService.emergencyReserve(reserveEdges,{atDate:'2026-04-01'});assert.equal(reserveAtEdges.evidence.aporteTotal,66000);assert.equal(reserveAtEdges.evidence.resgateTotal,12000);assert.equal(reserveAtEdges.evidence.contributionAverage,9000,'a média representa a janela móvel completa de seis meses');assert.deepEqual(Array.from(reserveAtEdges.evidence.contributionIds),['a','r','window-start']);
const reserveWithoutEssentials=context.window.AnalysisService.emergencyReserve({...reserveData,categorias:reserveData.categorias.map(item=>({...item,essencial:false}))},{atDate:'2026-04-01'});assert.equal(reserveWithoutEssentials.status,'indisponivel');assert.equal(reserveWithoutEssentials.confidence,20);assert.equal(reserveWithoutEssentials.metrics.find(item=>item.key==='mediaEssencial').value,0);

const historicalMonths=['2026-01','2026-02','2026-03'],anomalyHistory=Object.fromEntries(historicalMonths.map(month=>[month,{status:'fechado',snapshot:{receitas:10000,despesas:15000,lancamentosDetalhados:[{tipo:'Despesa',tipoOperacao:'despesa',data:`${month}-05`,valor:1000},{tipo:'Despesa',tipoOperacao:'despesa',data:`${month}-10`,valor:5000,extraordinario:true},{tipo:'Despesa',tipoOperacao:'despesa',data:`${month}-20`,valor:9000}]}}])),anomalyData={...data,fechamentos:anomalyHistory,lancamentos:[{tipo:'Despesa',tipoOperacao:'despesa',status:'Pago',data:'2026-04-05',valor:1500},{tipo:'Despesa',tipoOperacao:'despesa',status:'Pago',data:'2026-04-10',valor:8000,extraordinario:true},{tipo:'Despesa',tipoOperacao:'despesa',status:'Pago',data:'2026-04-20',valor:10000},{tipo:'Despesa',tipoOperacao:'transferencia',status:'Pago',data:'2026-04-05',valor:99999}]};
const anomalyDay5=context.window.AnalysisService.monthAnomaly(anomalyData,{month:'2026-04',today:'2026-04-05'}),day5=Object.fromEntries(anomalyDay5.metrics.map(item=>[item.key,item.value]));assert.equal(anomalyDay5.evidence.comparedThroughDay,5);assert.equal(day5.despesasComExtraordinarios,1500);assert.equal(day5.mediaComparavel,1000);assert.equal(anomalyDay5.status,'critico');
const anomalyDay15=context.window.AnalysisService.monthAnomaly(anomalyData,{month:'2026-04',today:'2026-04-15'}),day15=Object.fromEntries(anomalyDay15.metrics.map(item=>[item.key,item.value]));assert.equal(day15.despesasComExtraordinarios,9500);assert.equal(day15.despesasSemExtraordinarios,1500);assert.equal(day15.extraordinarios,8000);assert.equal(day15.mediaComparavel,1000,'extraordinários históricos não entram na base comparável');assert.equal(anomalyDay15.confidence,65);
const anomalyDay30=context.window.AnalysisService.monthAnomaly(anomalyData,{month:'2026-04',today:'2026-04-30'}),day30=Object.fromEntries(anomalyDay30.metrics.map(item=>[item.key,item.value]));assert.equal(day30.despesasSemExtraordinarios,11500);assert.equal(day30.mediaComparavel,10000);assert.equal(anomalyDay30.status,'normal');
const closedAnomaly=context.window.AnalysisService.monthAnomaly({...anomalyData,fechamentos:{...anomalyHistory,'2026-04':{status:'fechado',snapshot:{receitas:10000,despesas:11500,lancamentosDetalhados:anomalyData.lancamentos}}}},{month:'2026-04',today:'2026-04-05'});assert.equal(closedAnomaly.evidence.partial,false);assert.equal(closedAnomaly.evidence.comparedThroughDay,null);assert.equal(Object.fromEntries(closedAnomaly.metrics.map(item=>[item.key,item.value])).despesasSemExtraordinarios,11500);
const legacyHistory={...anomalyHistory,'2026-03':{status:'fechado',snapshot:{receitas:10000,despesas:10000}}};assert.equal(context.window.AnalysisService.monthAnomaly({...anomalyData,fechamentos:legacyHistory},{month:'2026-04',today:'2026-04-15'}).status,'indisponivel','snapshots sem detalhes não devem sustentar comparação avançada');

const quality=context.window.AnalysisService.dataQuality({...data,lancamentos:[...data.lancamentos,{id:'future-income',tipo:'Receita',status:'Pendente',data:'2026-05-10',valor:100000,contaId:'a',categoriaId:'income'}]},{startMonth:'2026-04',months:2});assert.deepEqual(Array.from(quality.evidence.incomeSources,item=>item.source),['planejamento','receita_materializada']);assert.equal(quality.evidence.dimensions.income,25);assert.equal(quality.metrics[1].incomeSource,'receita_materializada');
console.log('analysis tests: OK');
