const assert=require('node:assert/strict');
const fs=require('node:fs');
const vm=require('node:vm');

const context={window:{}};
vm.createContext(context);
vm.runInContext(fs.readFileSync('js/services/import/core.js','utf8'),context,{filename:'js/services/import/core.js'});
const imports=context.window.FinTrackBankImport;

assert.equal(imports.normalizeDate('21/09/2026'),'2026-09-21');
assert.equal(imports.normalizeDate('2026-02-29'),null);
assert.equal(imports.normalizeAmount({amount:'-1.234,56'}),-123456);
assert.equal(imports.normalizeAmount({amount:'1,234.56'}),123456);
assert.equal(imports.normalizeAmount({amount:'1,234'}),null);
assert.equal(imports.normalizeAmount({amountCents:0}),null);

const input=[
  {rowNumber:2,sourceId:'bank-1',date:'21/09/2026',description:' Mercado ',originalDescription:'COMPRA CARTAO MERCADO 097',amount:'-128,42',documentNumber:' 097 '},
  {rowNumber:3,date:'2026-09-22',description:'Salário',amountCents:500000},
  {rowNumber:4,date:'31/02/2026',description:'Erro',amount:'0,00'},
];
const before=JSON.stringify(input);
const preview=imports.previewTransactions(input,{format:'csv',accountId:'conta-1',currency:'BRL'});
assert.equal(JSON.stringify(input),before);
assert.equal(preview.totalRows,3);
assert.equal(preview.items.length,2);
assert.equal(preview.errors.length,1);
assert.equal(preview.errors[0].rowNumber,4);
assert.equal(preview.errors[0].messages.length,2);
assert.equal(preview.items[0].amountCents,-12842);
assert.equal(preview.items[0].sourceId,'bank-1');
assert.equal(preview.items[0].source.rowNumber,2);
assert.equal(preview.items[0].originalDescription,'COMPRA CARTAO MERCADO 097');
assert.equal(preview.items[0].documentNumber,'097');
assert.equal(preview.items[0].type,'debit');
assert.equal(preview.items[0].reconciliationStatus,'pending');
assert.equal(preview.items[1].type,'credit');
assert.equal(preview.items[1].suggestedNature,'receita');
assert.equal('valor' in preview.items[0],false);
assert.equal('categoriaId' in preview.items[0],false);

const foreign=imports.previewTransactions([{date:'2026-09-21',description:'Compra',amountCents:-100,currency:'USD'}],{format:'ofx',accountId:'conta-1'});
assert.equal(foreign.items.length,0);
assert.ok(foreign.errors[0].messages.some(message=>message.includes('BRL')));
const unselected=imports.previewTransactions([{date:'2026-09-21',description:'Compra',amountCents:-100}],{format:'qif'});
assert.ok(unselected.errors[0].messages.some(message=>message.includes('conta')));
assert.ok(unselected.errors[0].messages.some(message=>message.includes('Formato')));
assert.equal(imports.statementPeriod('2026-09-01','2026-09-30','reported').from,'2026-09-01');
assert.equal(imports.statementPeriod('2026-09-30','2026-09-01','reported'),null);
assert.equal(imports.sourceScope('001','12345678'),imports.sourceScope('001','12345678'));
assert.notEqual(imports.sourceScope('001','12345678'),imports.sourceScope('002','12345678'));
assert.equal(imports.sourceScope('001',''),null);
assert.equal(imports.previewTransactions(null,{format:'csv'}).errors.length,1);
console.log('bank import core tests: OK');

for(const file of ['js/core/schema.js','js/core/migrations.js','js/core/normalize.js','js/core/validate.js','js/services/financial.js','js/services/import/csv.js','js/services/import/ofx.js','js/services/import/assistant.js','js/services/import/batches.js','js/services/import/coverage.js'])vm.runInContext(fs.readFileSync(file,'utf8'),context,{filename:file});
const {FinTrackNormalize,FinTrackValidation,FinTrackBankCsv,FinTrackBankOfx,FinTrackImportAssistant,FinTrackImportBatches,FinTrackImportCoverage}=context.window;
const state=FinTrackNormalize.normalizeData({schemaVersion:9,__centsVersion:1,contas:[{id:'a',nome:'Conta A',saldoInicial:0}],categorias:[{id:'expense',nome:'Outros',tipo:'Saída',orcado:0},{id:'income',nome:'Receita',tipo:'Entrada',orcado:0}],lancamentos:[{id:'old',data:'2026-09-21',descricao:'Mercado',tipo:'Despesa',contaId:'a',categoriaId:'expense',valor:12842,status:'Pago',tipoOperacao:'despesa'}]});
assert.equal(state.schemaVersion,11);
assert.equal(state.importBatches.length,0);
assert.equal(state.importRules.length,0);
const invalidMetadata=FinTrackNormalize.normalizeData({...state,importBatches:[{id:'bad-batch',format:'ofx',status:'active'}],importRules:[{id:'bad-rule',pattern:'x',type:'Despesa',categoryId:'expense'}]});
assert.equal(FinTrackValidation.validateData(invalidMetadata).valid,false);
const repairedMetadata=FinTrackValidation.repairData(invalidMetadata);
assert.equal(repairedMetadata.importBatches.length,0);
assert.equal(repairedMetadata.importRules.length,0);
assert.equal(repairedMetadata.quarentena.filter(item=>['lote_importacao_invalido','regra_importacao_invalida'].includes(item.tipo)).length,2);
const parsed=FinTrackBankCsv.parse('Data;Histórico;Débito;Crédito;ID transação\n21/09/2026;"Compra; mercado";128,42;;bank-1\n22/09/2026;Salário;;500,00;bank-2');
assert.equal(parsed.rows.length,2);
const multiline=FinTrackBankCsv.parse('Data,Descrição,Valor\n2026-09-21,"Mercado\nCentral","-12,84"');
assert.equal(multiline.rows[0].cells[1],'Mercado\nCentral');
assert.equal(multiline.rows[0].rowNumber,2);
assert.equal(FinTrackBankCsv.parse('Data;Descrição;Valor\n2026-09-21;"Sem fim;-12,84').errors.length,1);
const mapping=FinTrackBankCsv.suggestMapping(parsed.headers);
assert.equal(mapping.debit,2);
const bankPreview=FinTrackBankCsv.preview(parsed,mapping,'a');
assert.equal(bankPreview.errors.length,0);
assert.equal(bankPreview.items[0].amountCents,-12842);
assert.equal(bankPreview.items[0].description,'Compra; mercado');
assert.equal(bankPreview.items[1].amountCents,50000);
assert.equal(FinTrackImportBatches.candidates(state,bankPreview.items[0]).length,1);
let sequence=0;
const ids=prefix=>`${prefix}-${++sequence}`;
const decisions=[{transaction:bankPreview.items[0],action:'link',matchId:'old'},{transaction:bankPreview.items[1],action:'import',categoryId:'income'}];
const result=FinTrackImportBatches.commit(state,decisions,{fileName:'extrato.csv',accountId:'a'},ids);
assert.equal(state.lancamentos.length,1);
assert.equal(result.state.lancamentos.length,2);
assert.equal(result.batch.created.length,1);
assert.equal(result.batch.linked[0].entryId,'old');
assert.equal(FinTrackValidation.validateData(result.state).valid,true);
const undone=FinTrackImportBatches.undo(result.state,result.batch.id);
assert.equal(undone.state.lancamentos.length,1);
assert.equal(undone.state.lancamentos[0].id,'old');
assert.equal(undone.batch.status,'undone');
assert.throws(()=>FinTrackImportBatches.undo(undone.state,result.batch.id),/desfeito/);
const changed=JSON.parse(JSON.stringify(result.state));changed.lancamentos[1].descricao='Corrigido';
assert.throws(()=>FinTrackImportBatches.undo(changed,result.batch.id),/alterados/);
assert.equal(FinTrackImportBatches.inspectUndo(changed,result.batch.id).conflicts[0].rowNumber,3);
const closed=JSON.parse(JSON.stringify(result.state));closed.fechamentos={'2026-09':{status:'fechado'}};
assert.throws(()=>FinTrackImportBatches.undo(closed,result.batch.id),/mês fechado/);
const reimport=FinTrackImportBatches.commit(result.state,[{transaction:bankPreview.items[1],action:'link',matchId:result.batch.created[0].entryId}],{fileName:'extrato-2.csv',accountId:'a'},ids);
assert.throws(()=>FinTrackImportBatches.undo(reimport.state,result.batch.id),/Outro lote ativo/);
assert.equal(FinTrackImportBatches.undo(FinTrackImportBatches.undo(reimport.state,reimport.batch.id).state,result.batch.id).state.lancamentos.length,1);
assert.equal(FinTrackImportBatches.inspectUndo(reimport.state,result.batch.id).conflicts[0].kind,'linked');
const conflicting={...bankPreview.items[1],date:'2026-09-24'};
const conflicts=FinTrackImportBatches.candidates(result.state,conflicting);
assert.equal(conflicts.length,1);
assert.equal(conflicts[0].compatible,false);
assert.throws(()=>FinTrackImportBatches.commit(result.state,[{transaction:conflicting,action:'link',matchId:result.batch.created[0].entryId}],{fileName:'extrato-3.csv',accountId:'a'},ids),/compatível/);
assert.throws(()=>FinTrackImportBatches.commit(state,[{transaction:bankPreview.items[0],action:'import',categoryId:'income'}],{fileName:'extrato.csv',accountId:'a'},ids),/categoria/);
assert.equal(FinTrackImportBatches.candidates(state,{...bankPreview.items[0],description:'Mercado'})[0].tier,'strong');
const nearDate={...bankPreview.items[0],description:'Mercado',date:'2026-09-22'};
assert.equal(FinTrackImportBatches.candidates(state,nearDate)[0].tier,'probable');
assert.equal(FinTrackImportBatches.candidates(state,{...bankPreview.items[0],description:'Outro estabelecimento'})[0].tier,'weak');
const coverageState={contas:[{id:'a'},{id:'b'}],importBatches:[
  {id:'c1',accountId:'a',status:'active',period:{from:'2026-09-01',to:'2026-09-10',kind:'confirmed'}},
  {id:'c2',accountId:'a',status:'active',period:{from:'2026-09-11',to:'2026-09-20',kind:'reported'}},
  {id:'c3',accountId:'a',status:'active',period:{from:'2026-09-18',to:'2026-09-25',kind:'confirmed'}},
  {id:'c4',accountId:'a',status:'active',period:{from:'2026-10-01',to:'2026-10-05',kind:'confirmed'}},
  {id:'legacy',accountId:'a',status:'active'},
  {id:'undone',accountId:'a',status:'undone',period:{from:'2026-09-26',to:'2026-09-30',kind:'confirmed'}}
]};
const coverage=FinTrackImportCoverage.analyze(coverageState),accountCoverage=coverage.find(item=>item.accountId==='a');
assert.equal(accountCoverage.merged.length,2);
assert.equal(accountCoverage.gaps[0].from,'2026-09-26');
assert.equal(accountCoverage.gaps[0].to,'2026-09-30');
assert.equal(accountCoverage.overlaps.length,1);
assert.equal(accountCoverage.unknownCount,1);
assert.equal(coverage.find(item=>item.accountId==='b').status,'unknown');
console.log('bank import workflow tests: OK');

const sgml='OFXHEADER:100\nDATA:OFXSGML\nVERSION:102\n<OFX><BANKMSGSRSV1><STMTTRNRS><STMTRS><CURDEF>BRL<BANKACCTFROM><BANKID>001<ACCTID>12345678</BANKACCTFROM><BANKTRANLIST><STMTTRN><TRNTYPE>DEBIT<DTPOSTED>20260921120000<TRNAMT>-12.84<FITID>fit-1<NAME>Mercado<MEMO>Compra</STMTTRN></BANKTRANLIST></STMTRS></STMTTRNRS></BANKMSGSRSV1></OFX>';
const ofx=FinTrackBankOfx.parse(sgml);
assert.equal(ofx.errors.length,0);
assert.equal(ofx.statements[0].accountSuffix,'5678');
assert.equal(FinTrackBankOfx.preview(ofx.statements[0],'a').items[0].amountCents,-1284);
assert.equal(FinTrackBankOfx.preview(ofx.statements[0],'a').items[0].sourceId,'fit-1');
assert.ok(FinTrackBankOfx.preview(ofx.statements[0],'a').items[0].source.identityKey);
assert.ok(!JSON.stringify(FinTrackBankOfx.preview(ofx.statements[0],'a').items[0]).includes('12345678'));
const fixture=name=>fs.readFileSync(`tests/fixtures/bank-import/${name}`,'utf8');
const sgmlFixture=FinTrackBankOfx.parse(fixture('statement-sgml.ofx')).statements[0];
const xmlFixture=FinTrackBankOfx.parse(fixture('statement-xml.ofx')).statements[0];
assert.equal(sgmlFixture.period.from,'2026-09-01');
assert.equal(xmlFixture.period.to,'2026-09-30');
const firstScoped=FinTrackBankOfx.preview(sgmlFixture,'a').items[0];
const secondScoped=FinTrackBankOfx.preview(xmlFixture,'a').items[0];
assert.notEqual(firstScoped.source.identityKey,secondScoped.source.identityKey);
assert.equal(FinTrackBankCsv.preview(FinTrackBankCsv.parse(fixture('statement.csv')),{date:0,description:1,amount:2,sourceId:3},'a').items.length,1);
const scopedState=JSON.parse(JSON.stringify(state));
scopedState.lancamentos=[{...scopedState.lancamentos[0],id:'scoped',importSource:{sourceId:'fit-same',identityKey:firstScoped.source.identityKey}}];
assert.equal(FinTrackImportBatches.candidates(scopedState,{...secondScoped,date:'2026-09-22'}).length,0);
assert.equal(FinTrackImportBatches.candidates(scopedState,{...firstScoped,date:'2026-09-22'}).length,1);
const legacyState=JSON.parse(JSON.stringify(scopedState));
delete legacyState.lancamentos[0].importSource.identityKey;
assert.equal(FinTrackImportBatches.candidates(legacyState,firstScoped).length,1);
const xml='<?xml version="1.0"?><OFX><BANKMSGSRSV1><STMTTRNRS><STMTRS><CURDEF>BRL</CURDEF><BANKACCTFROM><ACCTID>77</ACCTID></BANKACCTFROM><BANKTRANLIST><STMTTRN><DTPOSTED>20260922</DTPOSTED><TRNAMT>500.00</TRNAMT><FITID>fit-2</FITID><NAME>Salário &amp; bônus</NAME></STMTTRN></BANKTRANLIST></STMTRS></STMTTRNRS></BANKMSGSRSV1></OFX>';
assert.equal(FinTrackBankOfx.preview(FinTrackBankOfx.parse(xml).statements[0],'a').items[0].description,'Salário & bônus');
assert.equal(FinTrackBankOfx.parse(sgml.replace('<CURDEF>BRL','<CURDEF>USD')).statements[0].currency,'USD');
assert.equal(FinTrackBankOfx.preview(FinTrackBankOfx.parse(sgml.replace('<CURDEF>BRL','<CURDEF>USD')).statements[0],'a').items.length,0);
assert.equal(FinTrackBankOfx.parse('<!DOCTYPE ofx [<!ENTITY x SYSTEM "file:///secret">]><OFX></OFX>').errors.length,1);
assert.equal(FinTrackBankOfx.parse('<OFX><CCSTMTRS></CCSTMTRS></OFX>').errors.length,1);

const ruled=FinTrackImportAssistant.addRule(state,{pattern:'mercado',type:'Despesa',categoryId:'expense'},ids);
const suggestion=FinTrackImportAssistant.suggestCategory(ruled,bankPreview.items[0]);
assert.equal(suggestion.categoryId,'expense');
assert.match(suggestion.reason,/Regra local/);
assert.equal(FinTrackImportAssistant.removeRule(ruled,suggestion.ruleId).importRules.length,0);
assert.throws(()=>FinTrackImportAssistant.addRule(state,{pattern:'ma',type:'Despesa',categoryId:'expense'},ids),/3 a 80/);
assert.throws(()=>FinTrackImportAssistant.addRule(state,{pattern:'PIX',type:'Despesa',categoryId:'expense'},ids),/genérico/);
assert.throws(()=>FinTrackImportAssistant.addRule(state,{pattern:'Pagamento PIX',type:'Despesa',categoryId:'expense'},ids),/genérico/);
const historic={...state,lancamentos:[...state.lancamentos,{...state.lancamentos[0],id:'old-2',data:'2026-09-18'},{...state.lancamentos[0],id:'old-3',data:'2026-09-19'}]};
assert.equal(FinTrackImportAssistant.suggestCategory(historic,{...bankPreview.items[0],description:'Mercado',date:'2026-09-22'}).source,'history');
assert.equal(FinTrackImportAssistant.suggestCategory({...historic,importRules:ruled.importRules},{...bankPreview.items[0],description:'Mercado',date:'2026-09-22'}).source,'rule');
const remembered=FinTrackImportBatches.commit(state,[{transaction:bankPreview.items[0],action:'import',categoryId:'expense',rememberRule:true}],{format:'csv',fileName:'regra.csv',accountId:'a'},ids);
assert.equal(remembered.state.importRules.length,1);
assert.equal(FinTrackImportAssistant.suggestCategory(remembered.state,bankPreview.items[0]).categoryId,'expense');
assert.equal(FinTrackImportBatches.undo(remembered.state,remembered.batch.id).state.importRules.length,1);

const transferBase=FinTrackNormalize.normalizeData({...state,contas:[...state.contas,{id:'b',nome:'Conta B',saldoInicial:0}],lancamentos:[],operacoes:[]});
const transferTransaction={...bankPreview.items[0],description:'Transferência própria'};
const transferResult=FinTrackImportBatches.commit(transferBase,[{transaction:transferTransaction,action:'transfer',destinationAccountId:'b'}],{format:'ofx',fileName:'extrato.ofx',accountId:'a'},ids);
assert.equal(transferResult.batch.format,'ofx');
assert.equal(transferResult.state.lancamentos.length,2);
assert.equal(transferResult.state.operacoes.length,1);
assert.equal(FinTrackValidation.validateData(transferResult.state).valid,true);
assert.equal(FinTrackImportBatches.undo(FinTrackNormalize.normalizeData(transferResult.state),transferResult.batch.id).state.lancamentos.length,0);
const opposite={id:'existing-credit',data:transferTransaction.date,descricao:'Crédito existente',tipo:'Receita',contaId:'b',categoriaId:'income',valor:12842,status:'Pago',tipoOperacao:'receita'};
const withOpposite=FinTrackNormalize.normalizeData({...transferBase,lancamentos:[opposite]});
assert.equal(FinTrackImportAssistant.transferHints(withOpposite,transferTransaction).counterparts.length,1);
assert.throws(()=>FinTrackImportBatches.commit(withOpposite,[{transaction:transferTransaction,action:'transfer',destinationAccountId:'b'}],{format:'csv',fileName:'transfer.csv',accountId:'a'},ids),/movimento oposto existente/);
const paired=FinTrackImportBatches.commit(withOpposite,[{transaction:transferTransaction,action:'transfer',destinationAccountId:'b',counterpartId:'existing-credit'}],{format:'csv',fileName:'transfer.csv',accountId:'a'},ids);
assert.equal(paired.batch.modified.length,1);
assert.equal(paired.state.lancamentos.length,2);
assert.equal(FinTrackValidation.validateData(paired.state).valid,true);
const unpaired=FinTrackImportBatches.undo(FinTrackNormalize.normalizeData(paired.state),paired.batch.id).state;
assert.equal(unpaired.lancamentos.length,1);
assert.equal(unpaired.lancamentos[0].id,'existing-credit');
assert.equal(unpaired.lancamentos[0].tipoOperacao,'receita');
assert.equal(unpaired.operacoes.length,0);
assert.equal(FinTrackValidation.validateData(unpaired).valid,true);
const nearOpposite={...opposite,data:'2026-09-22'};
const nearState=FinTrackNormalize.normalizeData({...transferBase,lancamentos:[nearOpposite]});
assert.equal(FinTrackImportAssistant.transferHints(nearState,transferTransaction).counterparts[0].date,'2026-09-22');
const nearPair=FinTrackImportBatches.commit(nearState,[{transaction:transferTransaction,action:'transfer',destinationAccountId:'b',counterpartId:'existing-credit'}],{format:'csv',fileName:'transfer-near.csv',accountId:'a'},ids);
assert.equal(nearPair.state.lancamentos.find(item=>item.id==='existing-credit').data,'2026-09-22');
assert.equal(FinTrackValidation.validateData(nearPair.state).valid,true);
assert.equal(FinTrackImportBatches.undo(nearPair.state,nearPair.batch.id).state.lancamentos[0].data,'2026-09-22');
const closedNear=JSON.parse(JSON.stringify(nearPair.state));closedNear.fechamentos={'2026-09':{status:'fechado'}};
assert.throws(()=>FinTrackImportBatches.undo(closedNear,nearPair.batch.id),/mês fechado/);
console.log('OFX and import assistant tests: OK');
