const assert=require('node:assert/strict');
const fs=require('node:fs');
const vm=require('node:vm');

const context={window:{}};
vm.createContext(context);
for(const file of ['js/core/schema.js','js/core/migrations.js','js/core/normalize.js','js/core/validate.js','js/financial-core.js','js/core/closing.js']) vm.runInContext(fs.readFileSync(file,'utf8'),context,{filename:file});
const legacy=JSON.parse(fs.readFileSync('tests/fixtures/legacy-v1.json','utf8'));
const current=context.window.FinTrackNormalize.normalizeData(legacy);
assert.equal(current.schemaVersion,4);
assert.equal(current.contas[0].saldoInicial,10050);
assert.equal(current.lancamentos[0].valor,2590);
assert.equal(current.cartoes[0].limite,120000);
assert.equal(current.dividas[0].saldo,80000);
assert.equal(current.planejamentos['2026-02'].receita,300000);
assert.equal(current.planejamentos['2026-02'].orcamentos['cat-1'],45000);
assert.equal(context.window.FinTrackValidation.validateData(current).valid,true);

const regression=JSON.parse(fs.readFileSync('tests/fixtures/regression-v4.json','utf8'));
const normalized=context.window.FinTrackNormalize.normalizeData(regression);
assert.equal(normalized.lancamentos.length,3);
assert.equal(context.window.FinTrackValidation.validateData(normalized).warnings.length,0);
const repaired=context.window.FinTrackValidation.repairData({...normalized,lancamentos:[...normalized.lancamentos,{id:null}]});
assert.equal(repaired.lancamentos.length,3);
const brokenTransfer={...normalized,lancamentos:[...normalized.lancamentos,{id:'transfer-out',tipo:'Despesa',tipoOperacao:'transferencia',natureza:'transferencia',movimentoTransferencia:'saida',operacaoId:'op-broken',valor:100,data:'2026-02-10',contaId:'a'}]};
assert.ok(context.window.FinTrackValidation.validateData(brokenTransfer).warnings.some(item=>item.includes('transferência incompleta')));
const closed=context.window.FinTrackClosing.createSnapshot(normalized,'2026-01',{observacao:'Fechamento de teste',fechadoEm:'2026-02-01T12:00:00.000Z'});
assert.equal(closed.status,'fechado');
assert.equal(closed.snapshot.receitas,500000);
assert.equal(context.window.FinTrackClosing.reopen(closed,'2026-02-02T12:00:00.000Z').status,'aberto');
console.log('migration tests: OK');
