const assert=require('node:assert/strict');
const fs=require('node:fs');
const vm=require('node:vm');
const window={};
vm.runInNewContext(fs.readFileSync('js/reporting/monthly-pdf.js','utf8'),{window});
const closing={fechadoEm:'2026-08-31T20:00:00.000Z',observacao:'Fechamento <validado>',snapshot:{receitas:500000,despesas:320000,investimentos:50000,resultado:130000,planejamento:{receita:480000,investimento:40000},orcamentoDetalhado:[{categoriaNome:'Mercado',orcado:100000,realizado:65000,pendente:20000,comprometido:85000,disponivel:15000}],contas:[{nome:'Conta principal',saldo:130000}],lancamentosDetalhados:[{data:'2026-08-10',descricao:'Salário',categoriaNome:'Renda',contaNome:'Conta principal',status:'Pago',valor:500000}]}};
const html=window.FinTrackPdfReport.buildHtml('2026-08',closing);
assert.ok(html.includes('Relatório mensal FinTrack'));
assert.ok(html.includes('Conta principal'));
assert.ok(html.includes('Fechamento &lt;validado&gt;'));
assert.ok(html.includes('snapshot imutável'));
assert.ok(html.includes('Pendente'));
assert.ok(html.includes('Comprometido'));
const legacyHtml=window.FinTrackPdfReport.buildHtml('2024-02',{fechadoEm:'2024-03-01T00:00:00.000Z',snapshot:{versao:1,receitas:100000,despesas:4550,investimentos:0,resultado:95450}});
assert.ok(legacyHtml.includes('Relatório mensal FinTrack'));
assert.ok(legacyHtml.includes('954,50'));
assert.ok(!legacyHtml.includes('undefined'));
assert.throws(()=>window.FinTrackPdfReport.buildHtml('2026-08',{}),/snapshot mensal fechado/);
console.log('reporting tests: OK');
