(function(){
  'use strict';
  const escape=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[char]));
  const frame=(type,title,question,summary,body,legend='')=>`<figure class="chart chart-${type}" data-chart="${type}"><figcaption><strong>${escape(title)}</strong><span>${escape(question)}</span></figcaption><p class="chart-summary">${escape(summary)}</p>${body||'<div class="chart-empty">Sem dados suficientes para este gráfico.</div>'}${legend?`<div class="chart-legend">${legend}</div>`:''}</figure>`;
  const extent=values=>Math.max(1,...values.map(value=>Math.abs(Number(value)||0)));
  function groupedBars(options){const rows=options.data||[],keys=options.keys||[],max=extent(rows.flatMap(row=>keys.map(key=>row[key.value]))),groups=rows.map((row,index)=>`<g transform="translate(${index*(260/Math.max(1,rows.length))+10},0)">${keys.map((key,k)=>{const value=Number(row[key.value]||0),height=Math.abs(value)/max*88;return `<rect x="${k*14}" y="${100-height}" width="11" height="${height}" class="chart-color-${k}" tabindex="0"><title>${escape(row.label)} · ${escape(key.label)}: ${value}</title></rect>`;}).join('')}<text x="0" y="116">${escape(String(row.label).slice(5))}</text></g>`).join('');return frame('bars',options.title,options.question,options.summary,rows.length?`<svg viewBox="0 0 280 124" role="img" aria-label="${escape(options.summary)}">${groups}</svg>`:'',keys.map((key,i)=>`<span><i class="chart-key chart-color-${i}"></i>${escape(key.label)}</span>`).join(''));}
  function horizontalBars(options){const rows=options.data||[],max=extent(rows.map(row=>row.value)),body=rows.map((row,index)=>`<div class="chart-h-row"><span>${escape(row.label)}</span><div><i style="width:${Math.min(100,Math.abs(row.value)/max*100)}%"></i></div><strong>${escape(options.format?options.format(row.value):row.value)}</strong></div>`).join('');return frame('horizontal',options.title,options.question,options.summary,body);}
  function line(options,type='line'){const rows=options.data||[],max=extent(rows.map(row=>row.value)),points=rows.map((row,index)=>`${10+index*(260/Math.max(1,rows.length-1))},${100-(Number(row.value)||0)/max*82}`).join(' '),body=rows.length?`<svg viewBox="0 0 280 115" role="img" aria-label="${escape(options.summary)}">${type==='area'?`<polygon points="10,105 ${points} 270,105" class="chart-area-fill"/>`:''}<polyline points="${points}" class="chart-line-path"/>${rows.map((row,index)=>`<circle cx="${10+index*(260/Math.max(1,rows.length-1))}" cy="${100-(Number(row.value)||0)/max*82}" r="3" tabindex="0"><title>${escape(row.label)}: ${row.value}</title></circle>`).join('')}</svg>`:'';return frame(type,options.title,options.question,options.summary,body);}
  function donut(options){const rows=options.data||[],total=sum(rows),segments=[];let offset=0;rows.forEach((row,index)=>{const length=total?row.value/total*100:0;segments.push(`<circle cx="50" cy="50" r="36" pathLength="100" stroke-dasharray="${length} ${100-length}" stroke-dashoffset="${-offset}" class="chart-stroke-${index%6}"><title>${escape(row.label)}: ${row.value}</title></circle>`);offset+=length;});return frame('donut',options.title,options.question,options.summary,rows.length?`<div class="chart-donut-wrap"><svg viewBox="0 0 100 100" role="img" aria-label="${escape(options.summary)}">${segments.join('')}</svg><div class="chart-donut-legend">${rows.map((row,index)=>`<span><i class="chart-key chart-stroke-${index%6}"></i>${escape(row.label)} · ${escape(options.format?options.format(row.value):row.value)}</span>`).join('')}</div></div>`:'');}
  const sum=rows=>rows.reduce((total,row)=>total+Number(row.value||0),0);
  const area=options=>line(options,'area');
  const sparkline=options=>line({...options,title:options.title||'Tendência',question:options.question||'Como evoluiu?',summary:options.summary||'Série histórica'},'sparkline');
  window.FinTrackCharts={groupedBars,horizontalBars,line,area,donut,sparkline};
})();
