(function(){
  'use strict';
  const escape=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[char]));
  const number=value=>Number.isFinite(Number(value))?Number(value):0,rowsOf=data=>(Array.isArray(data)?data:[]).filter(Boolean);
  function domain(values,{includeZero=true}={}){const safe=values.map(number),rawMin=safe.length?Math.min(...safe):0,rawMax=safe.length?Math.max(...safe):0;let min=includeZero?Math.min(0,rawMin):rawMin,max=includeZero?Math.max(0,rawMax):rawMax;if(min===max){const padding=Math.max(1,Math.abs(min)*.1);min-=padding;max+=padding;}return {min,max,span:max-min,zero:max/(max-min)*100};}
  const y=(value,scale,top=10,height=90)=>top+(scale.max-number(value))/scale.span*height,x=(index,length,left=10,width=260)=>length<=1?left+width/2:left+index*width/(length-1);
  const frame=(type,title,question,summary,body,legend='',empty)=>`<figure class="chart chart-${type}" data-chart="${type}"><figcaption><strong>${escape(title)}</strong><span>${escape(question)}</span></figcaption><p class="chart-summary">${escape(summary)}</p>${body||`<div class="chart-empty"><strong>${escape(empty?.title||'Ainda faltam dados')}</strong><span>${escape(empty?.message||'Adicione informações para visualizar esta evolução.')}</span>${empty?.action?`<button class="btn btn-ghost" data-chart-action="${escape(empty.action.target||'')}">${escape(empty.action.label)}</button>`:''}</div>`}${legend?`<div class="chart-legend">${legend}</div>`:''}</figure>`;
  function groupedBars(options){const rows=rowsOf(options.data),keys=rowsOf(options.keys),scale=domain(rows.flatMap(row=>keys.map(key=>number(row[key.value])))),zeroY=y(0,scale),groupWidth=250/Math.max(1,rows.length),barWidth=Math.min(12,Math.max(5,(groupWidth-5)/Math.max(1,keys.length))),groups=rows.map((row,index)=>`<g transform="translate(${12+index*groupWidth},0)">${keys.map((key,k)=>{const value=number(row[key.value]),valueY=y(value,scale),height=Math.max(1,Math.abs(valueY-zeroY));return `<rect x="${k*(barWidth+2)}" y="${Math.min(valueY,zeroY)}" width="${barWidth}" height="${height}" class="chart-color-${k}" tabindex="0" aria-label="${escape(row.label)} · ${escape(key.label)}: ${value}"><title>${escape(row.label)} · ${escape(key.label)}: ${value}</title></rect>`;}).join('')}<text x="0" y="116">${escape(String(row.label).slice(-5))}</text></g>`).join(''),body=rows.length&&keys.length?`<svg viewBox="0 0 280 124" role="img" aria-label="${escape(options.summary)}"><line x1="8" x2="272" y1="${zeroY}" y2="${zeroY}" class="chart-zero"/>${groups}</svg>`:'';return frame('bars',options.title,options.question,options.summary,body,keys.map((key,i)=>`<span><i class="chart-key chart-color-${i}"></i>${escape(key.label)}</span>`).join(''),options.empty);}
  function horizontalBars(options){const rows=rowsOf(options.data),max=Math.max(1,...rows.map(row=>Math.abs(number(row.value)))),body=rows.map(row=>`<div class="chart-h-row" tabindex="0" aria-label="${escape(row.label)}: ${number(row.value)}"><span>${escape(row.label)}</span><div><i style="width:${Math.min(100,Math.abs(number(row.value))/max*100)}%"></i></div><strong>${escape(options.format?options.format(number(row.value)):number(row.value))}</strong></div>`).join('');return frame('horizontal',options.title,options.question,options.summary,body,'',options.empty);}
  function line(options,type='line'){const rows=rowsOf(options.data),scale=domain(rows.map(row=>row.value)),points=rows.map((row,index)=>`${x(index,rows.length)},${y(row.value,scale)}`).join(' '),zeroY=y(0,scale),body=rows.length?`<svg viewBox="0 0 280 115" role="img" aria-label="${escape(options.summary)}"><line x1="8" x2="272" y1="${zeroY}" y2="${zeroY}" class="chart-zero"/>${type==='area'?`<polygon points="${x(0,rows.length)},${zeroY} ${points} ${x(rows.length-1,rows.length)},${zeroY}" class="chart-area-fill"/>`:''}${rows.length>1?`<polyline points="${points}" class="chart-line-path"/>`:''}${rows.map((row,index)=>`<circle cx="${x(index,rows.length)}" cy="${y(row.value,scale)}" r="3" tabindex="0" aria-label="${escape(row.label)}: ${number(row.value)}"><title>${escape(row.label)}: ${number(row.value)}</title></circle>`).join('')}</svg>`:'';return frame(type,options.title,options.question,options.summary,body,'',options.empty);}
  function donut(options){const rows=rowsOf(options.data).map(row=>({...row,value:Math.max(0,number(row.value))})).filter(row=>row.value>0),total=rows.reduce((sum,row)=>sum+row.value,0),segments=[];let offset=0;rows.forEach((row,index)=>{const length=row.value/total*100;segments.push(`<circle cx="50" cy="50" r="36" pathLength="100" stroke-dasharray="${length} ${100-length}" stroke-dashoffset="${-offset}" class="chart-stroke-${index%6}" tabindex="0" aria-label="${escape(row.label)}: ${row.value}"><title>${escape(row.label)}: ${row.value}</title></circle>`);offset+=length;});const body=rows.length?`<div class="chart-donut-wrap"><svg viewBox="0 0 100 100" role="img" aria-label="${escape(options.summary)}">${segments.join('')}</svg><div class="chart-donut-legend">${rows.map((row,index)=>`<span><i class="chart-key chart-stroke-${index%6}"></i>${escape(row.label)} · ${escape(options.format?options.format(row.value):row.value)}</span>`).join('')}</div></div>`:'';return frame('donut',options.title,options.question,options.summary,body,'',options.empty);}
  const area=options=>line(options,'area'),sparkline=options=>line({...options,title:options.title||'Tendência',question:options.question||'Como evoluiu?',summary:options.summary||'Série histórica'},'sparkline');
  window.FinTrackCharts={domain,groupedBars,horizontalBars,line,area,donut,sparkline};
})();
