(function(){
  'use strict';
  const escape=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[char]));
  const tone=value=>['positive','warning','negative','neutral'].includes(value)?value:'neutral';
  const classes=value=>String(value||'').split(/\s+/).filter(item=>/^[a-z][a-z0-9-]*$/i.test(item)).join(' ');
  window.MetricCard={render(options={}){return `<article class="metric-card stat-card tone-${tone(options.tone)}"><span class="metric-label stat-label">${escape(options.label)}</span><strong class="metric-value stat-value">${escape(options.value)}</strong>${options.comparison?`<span class="metric-comparison stat-meta trend-${escape(options.trend||'neutral')}">${escape(options.comparison)}</span>`:''}${options.sparkline?`<div class="metric-sparkline" aria-hidden="true">${options.sparkline}</div>`:''}${options.detail?`<small class="metric-detail">${escape(options.detail)}</small>`:''}</article>`;}};
  window.InsightCard={render(options={}){const state=['normal','atencao','critico'].includes(options.state)?options.state:'normal';return `<article class="insight-card state-${state}"><div class="insight-card-title"><strong>${escape(options.headline||options.title)}</strong><span class="badge">${escape(options.label||state)}</span></div>${options.metrics?.length?`<div class="insight-metrics">${options.metrics.map(item=>`<div><span>${escape(item.label)}</span><strong>${escape(item.value)}</strong></div>`).join('')}</div>`:''}${options.message?`<p>${escape(options.message)}</p>`:''}${options.details?`<details><summary>Entenda esta leitura</summary><p>${escape(options.details)}</p></details>`:''}${options.action?`<button class="btn btn-ghost" data-insight-target="${escape(options.action.target||'')}">${escape(options.action.label)}</button>`:''}</article>`;}};
  window.MonthNavigator={render(options={}){const value=/^\d{4}-\d{2}$/.test(options.value)?options.value:new Date().toISOString().slice(0,7),id=options.id||'month-navigator',toDate=month=>new Date(`${month}-01T12:00:00`),shift=(month,amount)=>{const date=toDate(month);date.setMonth(date.getMonth()+amount);return `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}`;},min=options.min||shift(value,-12),max=options.max||shift(value,12),months=[];for(let cursor=min;cursor<=max;cursor=shift(cursor,1))months.push(cursor);const label=month=>new Intl.DateTimeFormat('pt-BR',{month:'long',year:'numeric'}).format(toDate(month));return `<div class="month-navigator"><label for="${escape(id)}">Mês</label><select id="${escape(id)}">${months.map(month=>`<option value="${month}" ${month===value?'selected':''}>${escape(label(month))}</option>`).join('')}</select>${options.showToday?`<button class="btn btn-ghost" type="button" data-month-today="${escape(id)}">Hoje</button>`:''}</div>`;}};
  window.DataPanel={render(options={}){const state=['normal','atencao','critico'].includes(options.state)?options.state:'normal',size=['full','wide','compact'].includes(options.size)?options.size:'full',extra=classes(options.className);return `<section class="data-panel section state-${state} panel-${size}${extra?' '+extra:''}"><header class="data-panel-head section-head"><div><h2>${escape(options.title)}</h2>${options.question?`<p class="section-sub">${escape(options.question)}</p>`:''}</div>${options.action?`<button class="btn btn-ghost" data-panel-target="${escape(options.action.target||'')}">${escape(options.action.label)}</button>`:''}</header>${options.summary?`<p class="data-panel-summary">${escape(options.summary)}</p>`:''}<div class="data-panel-content">${options.content||''}</div></section>`;}};
})();
