(function(){'use strict';
  const esc=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&apos;'}[char]));
  function snapshots(data,year){return Object.entries(data.fechamentos||{}).filter(([key,item])=>key.startsWith(`${year}-`)&&item?.snapshot).sort(([a],[b])=>a.localeCompare(b)).map(([mes,item])=>({mes,snapshot:window.FinTrackClosing.readSnapshot(item.snapshot)}));}
  const sum=(items,field)=>items.reduce((total,item)=>total+Number(item.snapshot[field]||0),0);
  function report(data,year){const items=snapshots(data,year);return {ano:Number(year),meses:items,totais:{receitas:sum(items,'receitas'),despesas:sum(items,'despesas'),investimentos:sum(items,'investimentos'),resultado:sum(items,'resultado')},origem:'snapshots_fechados',completo:items.length===12};}
  function planning(data,year){const rows=Array.from({length:12},(_,i)=>{const mes=`${year}-${String(i+1).padStart(2,'0')}`,p=data.planejamentos?.[mes]||{};return {mes,receita:Number(p.receita||0),investimento:Number(p.investimento||0),despesas:Object.values(p.orcamentos||{}).reduce((a,b)=>a+Number(b||0),0)};});return {ano:Number(year),meses:rows,totais:{receita:rows.reduce((a,b)=>a+b.receita,0),despesas:rows.reduce((a,b)=>a+b.despesas,0),investimento:rows.reduce((a,b)=>a+b.investimento,0)}};}
  function compare(data,endMonth){const [year,month]=endMonth.split('-').map(Number),keys=offset=>Array.from({length:3},(_,i)=>{const d=new Date(year,month-1-offset-i,1);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`;}),total=list=>list.reduce((acc,key)=>acc+Number(data.fechamentos?.[key]?.snapshot?.resultado||0),0),currentKeys=keys(0),current=total(currentKeys),previous=total(keys(3)),lastYear=total(currentKeys.map(key=>`${Number(key.slice(0,4))-1}${key.slice(4)}`));return {periodo:endMonth,tresMeses:current,tresAnteriores:previous,anoAnterior:lastYear,variacaoTrimestral:previous?Math.round((current/previous-1)*100):null,variacaoAnual:lastYear?Math.round((current/lastYear-1)*100):null};}
  function csv(data,year){const r=report(data,year);return ['Mês;Receitas;Despesas;Investimentos;Resultado',...r.meses.map(item=>[item.mes,item.snapshot.receitas||0,item.snapshot.despesas||0,item.snapshot.investimentos||0,item.snapshot.resultado||0].join(';'))].join('\n');}
  function excel(data,year){const r=report(data,year),rows=r.meses.map(item=>`<Row><Cell><Data ss:Type="String">${esc(item.mes)}</Data></Cell>${['receitas','despesas','investimentos','resultado'].map(field=>`<Cell><Data ss:Type="Number">${Number(item.snapshot[field]||0)/100}</Data></Cell>`).join('')}</Row>`).join('');return `<?xml version="1.0"?><Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet" xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"><Worksheet ss:Name="Relatório ${year}"><Table><Row>${['Mês','Receitas','Despesas','Investimentos','Resultado'].map(v=>`<Cell><Data ss:Type="String">${v}</Data></Cell>`).join('')}</Row>${rows}</Table></Worksheet></Workbook>`;}
  window.AnnualReportService={report,planning,compare,csv,excel};
})();
