(function(){
  const escape=value=>String(value??'').replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));
  const money=value=>(Number(value||0)/100).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
  const date=value=>{const text=String(value||'').slice(0,10),parts=text.split('-');return parts.length===3?`${parts[2]}/${parts[1]}/${parts[0]}`:'—';};
  const rows=(items,renderer,columns,empty)=>items?.length?items.map(renderer).join(''):`<tr><td colspan="${columns}" class="empty">${empty}</td></tr>`;
  function visualSections(key,closing,previous){
    const snapshot=closing.snapshot,entries=snapshot.lancamentosDetalhados||[],expenses=entries.filter(item=>item.tipo==='Despesa'&&item.status==='Pago'&&!['transferencia','investimento','pagamento_cartao','pagamento_divida'].includes(item.tipoOperacao)),byCategory=new Map(),byDay=new Map();
    expenses.forEach(item=>{const category=item.categoriaNome||'Sem categoria',day=String(item.data||'').slice(0,10),amount=Number(item.valor||0);byCategory.set(category,(byCategory.get(category)||0)+amount);byDay.set(day,(byDay.get(day)||0)+amount);});
    const categories=[...byCategory].sort((a,b)=>b[1]-a[1]),maxCategory=Math.max(1,...categories.map(([,value])=>value)),maxDay=Math.max(1,...byDay.values()),[year,month]=key.split('-').map(Number),count=new Date(year,month,0).getDate(),heatmap=Array.from({length:count},(_,index)=>{const day=String(index+1).padStart(2,'0'),value=byDay.get(`${key}-${day}`)||0,level=Math.min(4,Math.ceil(value/maxDay*4));return `<div class="day level-${level}" title="${day}: ${money(value)}"><strong>${day}</strong><span>${value?money(value):'—'}</span></div>`;}).join('');
    const categoryRows=categories.length?categories.slice(0,10).map(([name,value])=>`<div class="bar-row"><span>${escape(name)}</span><div><i style="width:${Math.round(value/maxCategory*100)}%"></i></div><strong>${money(value)}</strong></div>`).join(''):'<p class="muted">Sem despesas pagas detalhadas no snapshot.</p>';
    const previousSnapshot=previous?.snapshot,comparison=previousSnapshot?`<section class="report-block"><h2>Comparação com ${escape(previous.mes||'o fechamento anterior')}</h2><div class="summary comparison"><div class="card"><span>Receitas</span><strong>${money(snapshot.receitas)}</strong><small>Antes: ${money(previousSnapshot.receitas)}</small></div><div class="card"><span>Despesas</span><strong>${money(snapshot.despesas)}</strong><small>Antes: ${money(previousSnapshot.despesas)}</small></div><div class="card"><span>Resultado</span><strong>${money(snapshot.resultado)}</strong><small>Antes: ${money(previousSnapshot.resultado)}</small></div></div></section>`:'';
    const memory=closing.memoriaFinanceira?.version===1?closing.memoriaFinanceira:null,diagnosis=memory?`<section class="report-block"><h2>Diagnóstico registrado no fechamento</h2><p><strong>Saúde ${memory.health.score}/100 · ${escape(memory.health.classification)}</strong></p>${memory.insights.length?`<ul>${memory.insights.map(item=>`<li>${escape(item.title)} — ${escape(item.detail)}</li>`).join('')}</ul>`:'<p>Nenhum sinal mensal relevante registrado.</p>'}<small class="muted">${escape(memory.method)}</small></section>`:'<section class="report-block"><h2>Diagnóstico histórico</h2><p class="muted">Não disponível neste fechamento. Diagnósticos antigos não são recalculados retroativamente.</p></section>';
    return `<section class="report-block"><h2>Quando o dinheiro saiu</h2><p class="muted">Gastos pagos por dia, derivados exclusivamente dos lançamentos congelados.</p><div class="day-grid">${heatmap}</div></section><section class="report-block"><h2>Para onde foi o dinheiro</h2>${categoryRows}</section>${comparison}${diagnosis}`;
  }

  function buildHtml(key,closing,previous){
    if(!closing?.snapshot) throw new Error('O relatório exige um snapshot mensal fechado.');
    const snapshot=closing.snapshot,planning=snapshot.planejamento||{},budgets=snapshot.orcamentoDetalhado||[];
    return `<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><title>FinTrack — ${escape(key)}</title><style>
      @page{size:A4;margin:16mm}*{box-sizing:border-box}body{font:12px Arial,sans-serif;color:#1c2620;margin:0}h1,h2{color:#24402f}h1{font-size:24px;margin:0}h2{font-size:15px;margin:24px 0 8px}.muted{color:#766f5e}.summary{display:grid;grid-template-columns:repeat(4,1fr);gap:8px;margin:20px 0}.comparison{grid-template-columns:repeat(3,1fr)}.card{border:1px solid #d9d2bf;padding:10px}.card span,.card small{display:block;color:#766f5e;font-size:10px}.card strong{display:block;margin:4px 0;font-size:16px}table{width:100%;border-collapse:collapse}th,td{padding:7px;border-bottom:1px solid #e5dfce;text-align:left}th{font-size:10px;text-transform:uppercase;color:#766f5e}.num{text-align:right}.empty{text-align:center;color:#766f5e}.note{padding:12px;background:#f0ece2;margin-top:18px}.report-block{break-inside:avoid}.day-grid{display:grid;grid-template-columns:repeat(7,1fr);gap:3px}.day{min-height:38px;padding:4px;border:1px solid #e5dfce}.day strong,.day span{display:block}.day span{font-size:8px}.level-1{background:#f1ead8}.level-2{background:#e8d6a9}.level-3{background:#d8b778}.level-4{background:#c7974c}.bar-row{display:grid;grid-template-columns:130px 1fr 90px;gap:8px;align-items:center;margin:7px 0}.bar-row>div{height:10px;background:#f0ece2}.bar-row i{display:block;height:100%;background:#315d46}footer{margin-top:28px;color:#766f5e;font-size:10px}@media print{button{display:none}}
    </style></head><body><header><h1>Relatório mensal FinTrack</h1><p class="muted">Período ${escape(key)} · snapshot fechado em ${date(closing.fechadoEm)}</p></header>
    <section class="summary"><div class="card"><span>Receitas</span><strong>${money(snapshot.receitas)}</strong></div><div class="card"><span>Despesas</span><strong>${money(snapshot.despesas)}</strong></div><div class="card"><span>Investimentos</span><strong>${money(snapshot.investimentos)}</strong></div><div class="card"><span>Resultado</span><strong>${money(snapshot.resultado)}</strong></div></section>
    ${visualSections(key,closing,previous)}
    <h2>Planejado x realizado</h2><table><thead><tr><th>Indicador</th><th class="num">Planejado</th><th class="num">Realizado</th></tr></thead><tbody><tr><td>Receitas</td><td class="num">${money(planning.receita)}</td><td class="num">${money(snapshot.receitas)}</td></tr><tr><td>Investimentos</td><td class="num">${money(planning.investimento)}</td><td class="num">${money(snapshot.investimentos)}</td></tr></tbody></table>
    <h2>Orçamento por categoria</h2><table><thead><tr><th>Categoria</th><th class="num">Orçado</th><th class="num">Realizado</th><th class="num">Pendente</th><th class="num">Comprometido</th><th class="num">Disponível</th></tr></thead><tbody>${rows(budgets,item=>`<tr><td>${escape(item.categoriaNome)}</td><td class="num">${money(item.orcado)}</td><td class="num">${money(item.realizado)}</td><td class="num">${item.pendente==null?'—':money(item.pendente)}</td><td class="num">${item.comprometido==null?'—':money(item.comprometido)}</td><td class="num">${money(item.disponivel)}</td></tr>`,6,'Nenhum orçamento registrado no snapshot.')}</tbody></table>
    <h2>Saldos por conta</h2><table><thead><tr><th>Conta</th><th class="num">Saldo</th></tr></thead><tbody>${rows(snapshot.contas,item=>`<tr><td>${escape(item.nome)}</td><td class="num">${money(item.saldo)}</td></tr>`,2,'Nenhuma conta registrada no snapshot.')}</tbody></table>
    <h2>Lançamentos congelados</h2><table><thead><tr><th>Data</th><th>Descrição</th><th>Categoria</th><th>Conta</th><th>Status</th><th class="num">Valor</th></tr></thead><tbody>${rows(snapshot.lancamentosDetalhados,item=>`<tr><td>${date(item.data)}</td><td>${escape(item.descricao)}</td><td>${escape(item.categoriaNome||'—')}</td><td>${escape(item.contaNome||'—')}</td><td>${escape(item.status)}</td><td class="num">${money(item.valor)}</td></tr>`,6,'Snapshot legado sem lançamentos detalhados.')}</tbody></table>
    ${closing.observacao?`<div class="note"><strong>Observação</strong><p>${escape(closing.observacao)}</p></div>`:''}<footer>Gerado a partir do snapshot imutável do fechamento. Dados atuais não são recalculados.</footer></body></html>`;
  }
  function open(key,closing,previous){
    const popup=window.open('','_blank');
    if(!popup){window.alert('Permita pop-ups para gerar o relatório em PDF.');return false;}
    popup.opener=null;popup.document.open();popup.document.write(buildHtml(key,closing,previous));popup.document.close();
    popup.addEventListener('load',()=>{popup.focus();popup.print();},{once:true});
    return true;
  }
  window.FinTrackPdfReport={buildHtml,open};
})();
