(function(){
  const option=(value,label,current)=>`<option value="${esc(value)}" ${current===value?'selected':''}>${esc(label)}</option>`;
  const monthBounds=month=>{const [year,index]=month.split('-').map(Number),last=new Date(year,index,0).getDate();return {start:`${month}-01`,end:`${month}-${String(last).padStart(2,'0')}`,year,index:index-1,last};};
  const monthLabel=month=>new Intl.DateTimeFormat('pt-BR',{month:'long',year:'numeric'}).format(new Date(`${month}-01T12:00:00`));
  const originLabel=value=>({lancamento:'Lançamento',recorrencia:'Recorrência',parcela:'Parcela',divida:'Dívida',despesa_anual:'Despesa anual',cartao:'Cartão'}[value]||value);
  const certaintyLabel=item=>item.status==='previsto'?'Estimado':'Registrado';
  const eventRow=item=>`<tr><td>${formatDate(item.vencimento)}</td><td><span class="agenda-marker agenda-${esc(item.origem)}" aria-hidden="true"></span>${esc(originLabel(item.origem))}</td><td>${esc(item.titulo)}</td><td><span class="badge badge-pending">${esc(certaintyLabel(item))}</span></td><td class="num ${item.tipo==='receita'?'money-in':'money-out'}">${formatMoney(item.valor)}</td><td><button class="btn btn-sm" data-agenda-open="${esc(item.id)}">Detalhes</button></td></tr>`;
  const modeLabel={compromissos:'Compromissos',gastos:'Gastos confirmados',saldo:'Saldo diário',orcamento:'Ritmo do orçamento',pressao:'Pressão futura'};
  function metric(day,events){
    if(agendaVisualizacao==='compromissos'){const value=events.reduce((sum,item)=>sum+Number(item.valor||0),0);return {value,label:events.length?`${events.length} · ${formatMoney(value)}`:'—'};}
    if(agendaVisualizacao==='gastos')return {value:day.spent,label:day.spent?formatMoney(day.spent):'—'};
    if(agendaVisualizacao==='saldo')return {value:day.closingBalance,label:formatMoney(day.closingBalance)};
    if(agendaVisualizacao==='orcamento')return {value:day.budgetVariance,label:`${day.budgetVariance>0?'+':''}${formatMoney(day.budgetVariance)}`};
    return {value:day.pressure,label:day.pressure?formatMoney(day.pressure):'—'};
  }
  function calendar(bounds,items,analysis){
    const offset=new Date(bounds.year,bounds.index,1).getDay(),cells=[],commitmentMax=Math.max(1,...Array.from({length:bounds.last},(_,index)=>items.filter(item=>item.vencimento===`${agendaMes}-${String(index+1).padStart(2,'0')}`).reduce((sum,item)=>sum+Number(item.valor||0),0)));
    for(let i=0;i<offset;i++)cells.push('<div class="agenda-day is-empty" aria-hidden="true"></div>');
    for(let day=1;day<=bounds.last;day++){
      const date=`${agendaMes}-${String(day).padStart(2,'0')}`,events=items.filter(item=>item.vencimento===date),daily=analysis.days[day-1],display=metric(daily,events),intensity=agendaVisualizacao==='compromissos'?Math.min(4,Math.ceil(Math.abs(display.value)/commitmentMax*4)):daily.intensity;
      cells.push(`<button class="agenda-day ${events.length?'has-events':''} heat-level-${intensity} state-${agendaVisualizacao==='compromissos'?'normal':daily.status}" data-agenda-day="${date}" aria-label="${day} de ${monthLabel(agendaMes)}, ${events.length} evento(s), ${modeLabel[agendaVisualizacao]} ${display.label}"><span class="agenda-day-number">${day}</span><span class="agenda-day-events">${events.slice(0,3).map(item=>`<i class="agenda-marker agenda-${esc(item.origem)}" title="${esc(originLabel(item.origem))}"></i>`).join('')}</span><small class="agenda-day-metric ${display.value>=0?'money-in':'money-out'}">${display.label}</small></button>`);
    }
    return `<div class="agenda-weekdays" aria-hidden="true">${['Dom','Seg','Ter','Qua','Qui','Sex','Sáb'].map(day=>`<span>${day}</span>`).join('')}</div><div class="agenda-calendar">${cells.join('')}</div><div class="agenda-intelligence"><span>Intensidade: claro → forte</span><span>Confirmado = lançamento pago</span><span>Registrado = compromisso cadastrado</span><span>Estimado = projeção sem lançamento</span></div>`;
  }
  function dayPanel(items,analysis){
    if(!agendaDiaSelecionado)return '';
    const events=items.filter(item=>item.vencimento===agendaDiaSelecionado),day=analysis.days.find(item=>item.date===agendaDiaSelecionado),categories=day?.categories?.length?`<div class="agenda-category-list"><strong>Gastos confirmados por categoria</strong>${day.categories.map(item=>`<div><span>${esc(item.label)}</span><strong>${formatMoney(item.value)}</strong></div>`).join('')}</div>`:'';
    const pressureLabel={critico:'Alta pressão financeira',atencao:'Atenção ao fluxo do dia',normal:'Fluxo dentro do esperado'}[day?.status]||'Leitura indisponível',interpretation=`<div class="agenda-day-reading state-${esc(day?.status||'normal')}"><strong>${pressureLabel}</strong><p>${events.length} compromisso(s) · pressão futura de ${formatMoney(day?.pressure||0)}. O saldo inclui valores confirmados, registrados e estimados; apenas gastos pagos são confirmados.</p></div>`;
    return `<aside class="agenda-panel" role="dialog" aria-modal="false" aria-labelledby="agenda-panel-title"><div class="section-head"><h2 id="agenda-panel-title">${formatDate(agendaDiaSelecionado)}</h2><button class="btn btn-sm" id="agenda-close-day" aria-label="Fechar detalhes do dia">Fechar</button></div><div class="agenda-panel-body">${interpretation}<div class="agenda-panel-summary"><div class="agenda-confirmed"><small>Gasto confirmado</small><strong>${formatMoney(day?.spent||0)}</strong></div><div><small>Saldo ao final</small><strong>${formatMoney(day?.closingBalance||0)}</strong></div><div class="agenda-registered"><small>Registrados</small><strong>${day?.registered.count||0} · ${formatMoney((day?.registered.expenses||0)-(day?.registered.income||0))}</strong></div><div class="agenda-estimated"><small>Estimados</small><strong>${day?.estimated.count||0} · ${formatMoney((day?.estimated.expenses||0)-(day?.estimated.income||0))}</strong></div></div>${categories}${events.length?events.map(item=>`<article class="agenda-event ${item.status==='previsto'?'agenda-estimated':'agenda-registered'}"><div><span class="agenda-marker agenda-${esc(item.origem)}" aria-hidden="true"></span><strong>${esc(item.titulo)}</strong><p>${esc(originLabel(item.origem))} · ${esc(certaintyLabel(item))} · ${formatMoney(item.valor)}</p></div><div class="quick-actions"><button class="btn btn-sm" data-agenda-link="${esc(item.href||'')}">Ver lançamento</button>${['lancamento','recorrencia','parcela'].includes(item.origem)?`<button class="btn btn-primary btn-sm" data-agenda-pay="${esc(item.entidadeId)}">Marcar como pago</button>`:''}</div></article>`).join(''):emptyState('Sem compromissos','Não há compromissos neste dia; os indicadores acima ainda consideram lançamentos confirmados.')}</div></aside>`;
  }
  window.renderAgendaView=function(){
    const bounds=monthBounds(agendaMes),items=AgendaService.project(state,{start:bounds.start,end:bounds.end},{tipo:agendaTipo,...agendaFiltros}),accounts=state.contas||[],cards=state.cartoes||[],debts=state.dividas||[],categories=(state.categorias||[]).filter(item=>item.tipo==='Saída'&&item.natureza!=='movimentacao'),analysis=CalendarAnalysisService.analyze(state,agendaMes,{mode:agendaVisualizacao==='compromissos'?'pressao':agendaVisualizacao,categoryId:agendaCategoria,today:todayLocal()}),flow=DailyCashflowService.project(state,agendaMes),lowest=[...flow].sort((a,b)=>a.closingBalance-b.closingBalance)[0],lowIndex=flow.findIndex(item=>item.date===lowest?.date),today=todayLocal();
    const balanceChart=FinTrackCharts.line({title:'Saldo ao longo do mês',question:'Em que momento meu saldo fica mais apertado?',summary:`Menor saldo ${formatMoney(lowest?.closingBalance||0)} em ${lowest?formatDate(lowest.date):'—'}${lowest?.principalImpact?` · principal impacto: ${lowest.principalImpact.label}`:''}.`,data:flow.map(item=>({...item,label:item.date.slice(8),value:item.closingBalance})),referenceLines:today.startsWith(agendaMes)?[{axis:'x',value:today.slice(8),label:'Hoje',tone:'warning'}]:[],highlightedPoint:{index:lowIndex,label:'Menor saldo',tone:'negative'},tooltipContent:item=>({title:formatDate(item.date),metrics:[{label:'Saldo inicial',value:formatMoney(item.openingBalance)},...item.events.map(event=>({label:`${event.title} (${event.certainty==='confirmed'?'confirmado':event.certainty==='registered'?'registrado':'estimado'})`,value:`${event.type==='income'?'+':'−'}${formatMoney(event.value)}`})),{label:'Saldo final',value:formatMoney(item.closingBalance)}]})}).replace('class="chart ','class="chart chart-daily ');
    const budgetChart=FinTrackCharts.multiLine({title:'Ritmo do orçamento',question:'O gasto acumulado está acompanhando o ritmo ideal?',summary:analysis.summary.budget?`${analysis.summary.projected===null?'Gasto confirmado':`Projetado ${formatMoney(analysis.summary.projected)}`} ${analysis.summary.projected===null?formatMoney(analysis.summary.totalSpent):''} para orçamento de ${formatMoney(analysis.summary.budget)}.`:'Defina orçamentos para comparar o ritmo real com o ideal.',data:analysis.summary.budget?analysis.budgetSeries:[],keys:[{value:'actual',label:'Gasto acumulado'},{value:'ideal',label:'Ritmo ideal'}],format:formatMoney,tooltipContent:(row,key)=>({title:`Dia ${row.label} · ${key.label}`,metrics:[{label:'Valor',value:formatMoney(row[key.value])},{label:'Diferença para o ritmo',value:formatMoney(row.actual-row.ideal)}]}),empty:{title:'Orçamento não definido',message:'Configure valores em Planejamento para ativar esta comparação.'}});
    return `<div class="page-header"><div class="page-heading"><h1 class="page-title">Agenda financeira</h1><p class="page-sub">Inteligência diária para antecipar gastos, saldo, orçamento e pressão financeira</p></div><div class="agenda-month-nav"><button class="btn" id="agenda-prev" aria-label="Mês anterior">←</button><label for="agenda-mes" class="sr-only">Mês</label><input id="agenda-mes" type="month" value="${agendaMes}"><button class="btn" id="agenda-next" aria-label="Próximo mês">→</button><button class="btn" id="agenda-today">Hoje</button></div></div><div class="dashboard-grid">${balanceChart}${budgetChart}</div><div class="section"><div class="filters agenda-filters"><label>Visualização<select id="agenda-visualizacao">${Object.entries(modeLabel).map(([value,label])=>option(value,label,agendaVisualizacao)).join('')}</select></label><label>Categoria<select id="agenda-categoria">${option('','Todas',agendaCategoria)}${categories.map(item=>option(item.id,item.nome,agendaCategoria)).join('')}</select></label><label>Tipo<select id="agenda-tipo">${option('todos','Todos',agendaTipo)}${option('receita','Receitas',agendaTipo)}${option('despesa','Despesas',agendaTipo)}</select></label><label>Conta<select id="agenda-conta">${option('','Todas',agendaFiltros.contaId)}${accounts.map(item=>option(item.id,item.nome,agendaFiltros.contaId)).join('')}</select></label><label>Cartão<select id="agenda-cartao">${option('','Todos',agendaFiltros.cartaoId)}${cards.map(item=>option(item.id,item.nome,agendaFiltros.cartaoId)).join('')}</select></label><label>Dívida<select id="agenda-divida">${option('','Todas',agendaFiltros.dividaId)}${debts.map(item=>option(item.id,item.credor||item.nome,agendaFiltros.dividaId)).join('')}</select></label><label class="agenda-check"><input id="agenda-parcela" type="checkbox" ${agendaFiltros.parcela?'checked':''}> Somente parcelas</label></div><div class="section-head"><div class="tabs" role="tablist"><button class="tab-btn ${agendaModo==='calendario'?'active':''}" data-agenda-mode="calendario" role="tab" aria-selected="${agendaModo==='calendario'}">Calendário</button><button class="tab-btn ${agendaModo==='lista'?'active':''}" data-agenda-mode="lista" role="tab" aria-selected="${agendaModo==='lista'}">Lista</button></div><span class="stat-meta">${items.length} item(ns) · ${analysis.quality.confirmedEntries} confirmado(s) · ${analysis.quality.estimatedEvents} estimado(s)</span></div>${agendaModo==='calendario'?calendar(bounds,items,analysis):(items.length?`<div class="table-wrap"><table><thead><tr><th>Vencimento</th><th>Origem</th><th>Descrição</th><th>Confiança</th><th class="num">Valor</th><th>Ação</th></tr></thead><tbody>${items.map(eventRow).join('')}</tbody></table></div>`:emptyState('Agenda vazia','Não há eventos para os filtros deste mês.'))}<p class="stat-meta">${esc(analysis.limitation)}</p></div>${dayPanel(items,analysis)}`;
  };
  FinTrackViews.register('agenda',()=>window.renderAgendaView());
})();
