(function(){
  const option=(value,label,current)=>`<option value="${esc(value)}" ${current===value?'selected':''}>${esc(label)}</option>`;
  const monthBounds=month=>{const [year,index]=month.split('-').map(Number),last=new Date(year,index,0).getDate();return {start:`${month}-01`,end:`${month}-${String(last).padStart(2,'0')}`,year,index:index-1,last};};
  const monthLabel=month=>new Intl.DateTimeFormat('pt-BR',{month:'long',year:'numeric'}).format(new Date(`${month}-01T12:00:00`));
  const originLabel=value=>({lancamento:'Lançamento',recorrencia:'Recorrência',parcela:'Parcela',divida:'Dívida',despesa_anual:'Despesa anual',cartao:'Cartão'}[value]||value);
  const eventRow=item=>`<tr><td>${formatDate(item.vencimento)}</td><td><span class="agenda-marker agenda-${esc(item.origem)}" aria-hidden="true"></span>${esc(originLabel(item.origem))}</td><td>${esc(item.titulo)}</td><td><span class="badge badge-pending">${esc(item.status)}</span></td><td class="num ${item.tipo==='receita'?'money-in':'money-out'}">${formatMoney(item.valor)}</td><td><button class="btn btn-sm" data-agenda-open="${esc(item.id)}">Detalhes</button></td></tr>`;
  function calendar(bounds,items){
    const offset=new Date(bounds.year,bounds.index,1).getDay(),cells=[];
    for(let i=0;i<offset;i++)cells.push('<div class="agenda-day is-empty" aria-hidden="true"></div>');
    for(let day=1;day<=bounds.last;day++){
      const date=`${agendaMes}-${String(day).padStart(2,'0')}`,events=items.filter(item=>item.vencimento===date),total=events.reduce((sum,item)=>sum+(item.tipo==='receita'?item.valor:-item.valor),0);
      cells.push(`<button class="agenda-day ${events.length?'has-events':''}" data-agenda-day="${date}" aria-label="${day} de ${monthLabel(agendaMes)}, ${events.length} evento(s)"><span class="agenda-day-number">${day}</span><span class="agenda-day-events">${events.slice(0,3).map(item=>`<i class="agenda-marker agenda-${esc(item.origem)}" title="${esc(originLabel(item.origem))}"></i>`).join('')}</span>${events.length?`<small class="${total>=0?'money-in':'money-out'}">${formatMoney(Math.abs(total))}</small>`:''}</button>`);
    }
    return `<div class="agenda-weekdays" aria-hidden="true">${['Dom','Seg','Ter','Qua','Qui','Sex','Sáb'].map(day=>`<span>${day}</span>`).join('')}</div><div class="agenda-calendar">${cells.join('')}</div>`;
  }
  function dayPanel(items){
    if(!agendaDiaSelecionado)return '';
    const events=items.filter(item=>item.vencimento===agendaDiaSelecionado);
    return `<aside class="agenda-panel" role="dialog" aria-modal="false" aria-labelledby="agenda-panel-title"><div class="section-head"><h2 id="agenda-panel-title">${formatDate(agendaDiaSelecionado)}</h2><button class="btn btn-sm" id="agenda-close-day" aria-label="Fechar detalhes do dia">Fechar</button></div><div class="agenda-panel-body">${events.length?events.map(item=>`<article class="agenda-event"><div><span class="agenda-marker agenda-${esc(item.origem)}" aria-hidden="true"></span><strong>${esc(item.titulo)}</strong><p>${esc(originLabel(item.origem))} · ${esc(item.status)} · ${formatMoney(item.valor)}</p></div><div class="quick-actions"><button class="btn btn-sm" data-agenda-link="${esc(item.href||'')}">Ver lançamento</button>${['lancamento','recorrencia','parcela'].includes(item.origem)?`<button class="btn btn-primary btn-sm" data-agenda-pay="${esc(item.entidadeId)}">Marcar como pago</button>`:''}</div></article>`).join(''):emptyState('Sem eventos','Não há compromissos neste dia.')}</div></aside>`;
  }
  window.renderAgendaView=function(){
    const bounds=monthBounds(agendaMes),items=AgendaService.project(state,{start:bounds.start,end:bounds.end},{tipo:agendaTipo,...agendaFiltros}),accounts=state.contas||[],cards=state.cartoes||[],debts=state.dividas||[];
    return `<div class="page-header"><div class="page-heading"><h1 class="page-title">Agenda financeira</h1><p class="page-sub">Eventos derivados dos seus dados, sem duplicar lançamentos</p></div><div class="agenda-month-nav"><button class="btn" id="agenda-prev" aria-label="Mês anterior">←</button><label for="agenda-mes" class="sr-only">Mês</label><input id="agenda-mes" type="month" value="${agendaMes}"><button class="btn" id="agenda-next" aria-label="Próximo mês">→</button><button class="btn" id="agenda-today">Hoje</button></div></div><div class="section"><div class="filters agenda-filters"><label>Tipo<select id="agenda-tipo">${option('todos','Todos',agendaTipo)}${option('receita','Receitas',agendaTipo)}${option('despesa','Despesas',agendaTipo)}</select></label><label>Conta<select id="agenda-conta">${option('','Todas',agendaFiltros.contaId)}${accounts.map(item=>option(item.id,item.nome,agendaFiltros.contaId)).join('')}</select></label><label>Cartão<select id="agenda-cartao">${option('','Todos',agendaFiltros.cartaoId)}${cards.map(item=>option(item.id,item.nome,agendaFiltros.cartaoId)).join('')}</select></label><label>Dívida<select id="agenda-divida">${option('','Todas',agendaFiltros.dividaId)}${debts.map(item=>option(item.id,item.credor||item.nome,agendaFiltros.dividaId)).join('')}</select></label><label class="agenda-check"><input id="agenda-parcela" type="checkbox" ${agendaFiltros.parcela?'checked':''}> Somente parcelas</label></div><div class="section-head"><div class="tabs" role="tablist"><button class="tab-btn ${agendaModo==='calendario'?'active':''}" data-agenda-mode="calendario" role="tab" aria-selected="${agendaModo==='calendario'}">Calendário</button><button class="tab-btn ${agendaModo==='lista'?'active':''}" data-agenda-mode="lista" role="tab" aria-selected="${agendaModo==='lista'}">Lista</button></div><span class="stat-meta">${items.length} item(ns) em ${monthLabel(agendaMes)}</span></div>${agendaModo==='calendario'?calendar(bounds,items):(items.length?`<div class="table-wrap"><table><thead><tr><th>Vencimento</th><th>Origem</th><th>Descrição</th><th>Status</th><th class="num">Valor</th><th>Ação</th></tr></thead><tbody>${items.map(eventRow).join('')}</tbody></table></div>`:emptyState('Agenda vazia','Não há eventos para os filtros deste mês.'))}</div>${dayPanel(items)}`;
  };
  FinTrackViews.register('agenda',()=>window.renderAgendaView());
})();
