(function(){
  'use strict';
  const moneyMetric=(label,value)=>MetricCard.render({label,value:formatMoney(value),tone:value<0?'negative':'neutral'});
  const explanation=(items,limitation='Análise determinística baseada nos dados locais cadastrados.')=>`<details class="analysis-evidence"><summary>Como chegamos a esta conclusão?</summary><ul>${items.map(item=>`<li>${esc(item)}</li>`).join('')}</ul><p class="insight-limitation"><strong>Limitação:</strong> ${esc(limitation)}</p></details>`;
  const insightCard=item=>{if(!item)return InsightCard.render({headline:'Nenhum risco relevante',state:'normal',label:'Normal',message:'Continue mantendo os lançamentos atualizados.'});const presented=InsightPresenter.present(item,{money:formatMoney}),route=FinTrackInsightRoutes.forInsight(item,state);return InsightCard.render({headline:presented.headline,state:['critica','alta'].includes(presented.severity)?'critico':presented.severity==='media'?'atencao':'normal',label:`Relevância ${item.relevancia}/100`,metrics:presented.metrics.slice(0,2).map(metric=>({label:metric.label,value:metric.format==='money'?formatMoney(metric.value):metric.format==='percent'?`${metric.value}%`:metric.value})),message:presented.comparison||item.mensagem,details:presented.details,provenance:presented.provenance,limitation:presented.limitation,action:{label:presented.actionLabel,target:route.view,month:route.month,categoryId:route.categoryId,date:route.date,entityId:route.entityId}});};
  const actionList=actions=>`<ol class="decision-actions">${actions.map(action=>`<li><span>${action.rank}</span><div><strong>${esc(action.title)}</strong><p>${esc(action.reason)}</p><small>${esc(action.effect)} · relevância ${action.relevance}/100</small></div><button class="btn btn-ghost btn-sm" data-insight-target="${esc(action.target)}" data-insight-month="${esc(action.month||'')}" data-insight-category="${esc(action.categoryId||'')}" data-insight-date="${esc(action.date||'')}" data-insight-entity="${esc(action.entityId||'')}" aria-label="Agir: ${esc(action.title)}">Agir</button></li>`).join('')}</ol>`;

  window.renderAnalisesView=function(){
    const month=mesAtualKey(),today=todayLocal(),decision=DecisionService.evaluate(state,{today,limit:3}),recurring=AnalysisService.recurringExpenses(state,{today}),commitment=AnalysisService.futureCommitment(state,{startMonth:month,months:3}),reserve=AnalysisService.emergencyReserve(state,{atDate:today}),quality=AnalysisService.dataQuality(state,{startMonth:month,months:3}),anomaly=AnalysisService.monthAnomaly(state,{month,today}),concentration=AnalysisService.expenseConcentration(state,{month}),primary=decision.primary;
    const central=DataPanel.render({title:'Central de decisão',question:'O que está acontecendo, por quê e o que fazer agora?',state:decision.health.status,summary:`Saúde ${decision.health.score}/100 · ${decision.health.classification}`,content:`<div class="decision-overview"><div class="decision-score"><strong>${decision.health.score}<small>/100</small></strong><span>${esc(decision.health.classification)}</span><p>${esc(decision.health.mainAttention)}</p></div>${insightCard(primary)}</div>`});
    const actions=DataPanel.render({title:'Próximas três ações',question:'Onde agir primeiro?',summary:'Ordenadas por urgência, impacto, qualidade dos dados e capacidade de ação.',content:actionList(decision.actions)});
    const commitmentPanel=DataPanel.render({title:'Comprometimento futuro',question:'Quanto da renda já está reservado?',state:commitment.status,summary:commitment.summary,content:`<div class="metric-grid">${commitment.metrics.map(item=>MetricCard.render({label:item.month,value:item.commitmentRate==null?'Sem renda':`${item.commitmentRate}%`,tone:item.commitmentRate>100?'negative':'neutral',detail:`Livre estimado: ${formatMoney(item.freeIncome)}`})).join('')}</div>${explanation([`${commitment.evidence.historyMonths.length} mês(es) fechados usados como histórico`,'Compromissos confirmados, orçamento e investimentos planejados','Renda planejada ou média histórica quando indisponível'])}`});
    const reserveValues=Object.fromEntries(reserve.metrics.map(item=>[item.key,item.value])),anomalyLabels={despesasComExtraordinarios:'Com extraordinários',despesasSemExtraordinarios:'Sem extraordinários',mediaComparavel:'Média comparável',diferencaSemExtraordinarios:'Diferença sem extraordinários',variacaoSemExtraordinarios:'Variação sem extraordinários',extraordinarios:'Participação extraordinária'},anomalyCards=anomaly.metrics.map(item=>item.key==='variacaoSemExtraordinarios'?MetricCard.render({label:anomalyLabels[item.key],value:`${item.value}%`,tone:Math.abs(item.value)>=35?'negative':'neutral'}):moneyMetric(anomalyLabels[item.key]||item.key,item.value)).join(''),concentrationRows=concentration.evidence.categories||[],concentrationChart=FinTrackCharts.horizontalBars({title:'Concentração de gastos',question:'Poucas categorias consomem a maior parte do dinheiro?',summary:concentration.summary,data:[...concentrationRows,...(concentration.evidence.other?[{label:'Outros',value:concentration.evidence.other}]:[])],format:formatMoney}).replace('</figure>',`${explanation([`${concentrationRows.length} categoria(s) de maior impacto`,'Despesas pagas agrupadas por categoria',concentration.evidence.heuristic||'Participação das três maiores categorias'])}</figure>`);
    const recurringPanel=DataPanel.render({title:'Recorrências',question:'O que se repete?',state:recurring.status,summary:recurring.summary,content:`${moneyMetric('Custo mensal',recurring.metrics[0].value)}<p class="stat-meta">Heurística: ${esc(recurring.evidence.heuristic)}</p>${explanation([`${recurring.evidence.registered.length} recorrência(s) cadastrada(s)`,`${recurring.evidence.detected.length} padrão(ões) detectado(s)`,recurring.evidence.heuristic],'Padrões detectados precisam de confirmação do usuário.')}`});
    const reservePanel=DataPanel.render({title:'Reserva de emergência',question:'Por quanto tempo estou protegido?',state:reserve.status,summary:reserve.summary,content:`${moneyMetric('Disponível',reserveValues.disponivel)}${moneyMetric('Faltante',reserveValues.faltante)}<p class="stat-meta">Qualidade da evidência: ${reserve.confidence==null?'indisponível':`${reserve.confidence}/100`}.</p>${explanation([`${reserve.evidence.historyMonths} mês(es) de despesas essenciais`,`${reserve.evidence.accountIds.length} conta(s) e ${reserve.evidence.assetIds.length} ativo(s) marcados como reserva`,`${reserve.evidence.contributionIds.length} aporte(s) ou resgate(s) válidos`])}`});
    const qualityPanel=DataPanel.render({title:'Qualidade da projeção',question:'Os dados sustentam a projeção?',state:quality.status,summary:quality.summary,content:`<p>Qualidade dos dados: ${quality.confidence}/100 · indicador separado da saúde financeira.</p>${explanation([`Obrigações: ${quality.evidence.dimensions.coverage}/35`,`Renda conhecida: ${quality.evidence.dimensions.income}/25`,`Completude dos vínculos: ${quality.evidence.dimensions.completeness}/20`,`Histórico e atualização: ${quality.evidence.dimensions.history+quality.evidence.dimensions.updates}/20`])}`});
    const anomalyPanel=DataPanel.render({title:'Mês atípico',question:'Este mês está fora do padrão?',state:anomaly.status,summary:anomaly.summary,content:anomaly.metrics.length?`<div class="metric-grid">${anomalyCards}</div><p class="stat-meta">${anomaly.evidence.partial?`Mês parcial comparado até o dia ${anomaly.evidence.comparedThroughDay}.`:'Snapshot fechado.'} Qualidade da evidência: ${anomaly.confidence}/100.</p>${explanation([`${anomaly.evidence.historyMonths.length} mês(es) comparáveis`,anomaly.evidence.partial?`Mesma quantidade de dias: até ${anomaly.evidence.comparedThroughDay}`:'Meses completos','Gastos extraordinários removidos da comparação'])}`:`<p>Feche ao menos três meses comparáveis para habilitar esta análise.</p>${explanation([`${Number(anomaly.evidence.historyMonths||0)} mês(es) comparáveis disponíveis`,'São necessários pelo menos três fechamentos com lançamentos detalhados'],'Sem histórico comparável suficiente para concluir se o mês é atípico.')}`});
    const memory=FinancialMemoryService.timeline(state),comparison=FinancialMemoryService.compare(state),memoryChart=FinTrackCharts.horizontalBars({title:'Evolução da saúde financeira',question:'Estou melhorando ao longo dos fechamentos?',summary:comparison?`${comparison.current.label}: ${comparison.current.health.score}/100 · ${comparison.healthDelta>=0?'+':''}${comparison.healthDelta} ponto(s) em relação a ${comparison.previous.label}.`:'A evolução começa após dois fechamentos com memória financeira.',data:memory.map(item=>({label:item.label,value:item.health.score,tooltip:`${item.health.score}/100`})),format:value=>`${value}/100`,empty:{title:'Sem memória suficiente',message:'Feche dois meses a partir da versão 3.8 para comparar a evolução.'}}),memoryRows=memory.length?`<ol class="memory-timeline">${[...memory].reverse().slice(0,12).map(item=>`<li><strong>${esc(item.label)}</strong><span>${item.health.score}/100 · ${esc(item.health.classification)}</span><small>${item.insights.length?item.insights.map(insight=>esc(insight.title)).join(' · '):'Nenhum sinal mensal relevante'}</small></li>`).join('')}</ol>`:'<p>Fechamentos anteriores à versão 3.8 não recebem diagnósticos retroativos.</p>',memoryPanel=DataPanel.render({title:'Memória financeira',question:'O que mudou nos meses fechados?',summary:'Leituras preservadas no momento do fechamento; meses reabertos ficam fora da evolução até novo fechamento.',content:`${memoryChart}${memoryRows}`});
    return `<div class="page-header"><div class="page-heading"><h1 class="page-title">Análises</h1><p class="page-sub">Decisões priorizadas com evidências, qualidade e limitações</p></div></div>${central}${actions}${memoryPanel}<div class="dashboard-grid">${commitmentPanel}${recurringPanel}${reservePanel}${qualityPanel}${anomalyPanel}${concentrationChart}</div>`;
  };
  FinTrackViews.register('analises',()=>window.renderAnalisesView());
})();
