(function(){
  const moneyMetric=(label,value)=>MetricCard.render({label,value:formatMoney(value),tone:value<0?'negative':'neutral'});
  window.renderAnalisesView=function(){const month=mesAtualKey(),recurring=AnalysisService.recurringExpenses(state,{today:todayLocal()}),commitment=AnalysisService.futureCommitment(state,{startMonth:month,months:3}),reserve=AnalysisService.emergencyReserve(state,{atDate:todayLocal()}),quality=AnalysisService.dataQuality(state,{startMonth:month,months:3}),anomaly=AnalysisService.monthAnomaly(state,{month}),concentration=AnalysisService.expenseConcentration(state,{month}),concentrationChart=FinTrackCharts.horizontalBars({title:'Concentração de gastos',question:'Poucas categorias consomem a maior parte do dinheiro?',summary:concentration.summary,data:[...(concentration.evidence.categories||[]).map(item=>({label:item.label,value:item.value})),...(concentration.evidence.other?[{label:'Outros',value:concentration.evidence.other}]:[])],format:formatMoney});
    const commitmentPanel=DataPanel.render({title:'Comprometimento futuro',question:'Quanto da renda já está reservado?',state:commitment.status,summary:commitment.summary,content:`<div class="metric-grid">${commitment.metrics.map(item=>MetricCard.render({label:item.month,value:item.commitmentRate==null?'Sem renda':`${item.commitmentRate}%`,tone:item.commitmentRate>100?'negative':'neutral',detail:`Livre estimado: ${formatMoney(item.freeIncome)}`})).join('')}</div>`}),reserveValues=Object.fromEntries(reserve.metrics.map(item=>[item.key,item.value]));
    const anomalyLabels={despesasComExtraordinarios:'Com extraordinários',despesasSemExtraordinarios:'Sem extraordinários',mediaComparavel:'Média comparável',diferencaSemExtraordinarios:'Diferença sem extraordinários',variacaoSemExtraordinarios:'Variação sem extraordinários',extraordinarios:'Participação extraordinária'},anomalyCards=anomaly.metrics.map(item=>item.key==='variacaoSemExtraordinarios'?MetricCard.render({label:anomalyLabels[item.key],value:`${item.value}%`,tone:Math.abs(item.value)>=35?'negative':'neutral'}):moneyMetric(anomalyLabels[item.key]||item.key,item.value)).join('');
    return `<div class="page-header"><div class="page-heading"><h1 class="page-title">Análises</h1><p class="page-sub">Leituras determinísticas, evidências e limitações dos seus dados</p></div></div><div class="dashboard-grid">${commitmentPanel}${DataPanel.render({title:'Recorrências',question:'O que se repete?',state:recurring.status,summary:recurring.summary,content:`${moneyMetric('Custo mensal',recurring.metrics[0].value)}<p class="stat-meta">Heurística: ${esc(recurring.evidence.heuristic)}</p>`})}${DataPanel.render({title:'Reserva de emergência',question:'Por quanto tempo estou protegido?',state:reserve.status,summary:reserve.summary,content:`${moneyMetric('Disponível',reserveValues.disponivel)}${moneyMetric('Faltante',reserveValues.faltante)}<p class="stat-meta">Confiança ${reserve.confidence??'indisponível'}${reserve.confidence!=null?'%':''}.</p>`})}${DataPanel.render({title:'Qualidade da projeção',question:'Quanto posso confiar?',state:quality.status,summary:quality.summary,content:`<p>Confiança ${quality.confidence}% · score separado da saúde financeira.</p>`})}${DataPanel.render({title:'Mês atípico',question:'Este mês está fora do padrão?',state:anomaly.status,summary:anomaly.summary,content:anomaly.metrics.length?`<div class="metric-grid">${anomalyCards}</div><p class="stat-meta">${anomaly.evidence.partial?`Mês parcial comparado até o dia ${anomaly.evidence.comparedThroughDay}.`:'Snapshot fechado.'} Confiança ${anomaly.confidence}%.</p>`:'<p>Feche ao menos três meses comparáveis para habilitar esta análise.</p>'})}${concentrationChart}</div>`;
  };
  FinTrackViews.register('analises',()=>window.renderAnalisesView());
})();
