(function(){
  window.configuracoesTab=window.configuracoesTab||'geral';
  async function saveName(name,ignored=false){FinTrackState.transaction(current=>({...current,usuario:{...(current.usuario||{}),nome:String(name||'').trim(),onboardingIgnorado:Boolean(ignored)}}));await saveData();}
  window.openProfileOnboarding=function(){openModal('Bem-vindo ao FinTrack',`<p>Como gostaria de ser chamado?</p><div class="field"><label for="onboarding-name">Seu nome</label><input id="onboarding-name" maxlength="60" autocomplete="name"></div><div class="modal-actions"><button class="btn btn-ghost" id="onboarding-skip">Agora não</button><button class="btn btn-primary" id="onboarding-save">Começar</button></div>`,()=>{document.getElementById('onboarding-skip').onclick=async()=>{await saveName('',true);closeModal();render();};document.getElementById('onboarding-save').onclick=async()=>{await saveName(document.getElementById('onboarding-name').value);closeModal();render();};});};
  const tabs=()=>`<div class="tabs" role="tablist" aria-label="Áreas de configurações">${[['geral','Geral'],['aplicativo','Aplicativo'],['dados','Dados'],['importacoes','Importações']].map(([key,label])=>`<button role="tab" aria-selected="${configuracoesTab===key}" class="tab-btn ${configuracoesTab===key?'active':''}" data-config-tab="${key}">${label}</button>`).join('')}</div>`;
  const geral=()=>`<section class="section"><div class="section-head"><h2>Perfil e preferências</h2></div><div class="planning-fields"><div class="field"><label for="profile-name">Seu nome</label><input id="profile-name" maxlength="60" autocomplete="name" value="${esc(state.usuario?.nome||'')}"></div><div class="field"><label for="reserve-target">Meta da reserva de emergência</label><select id="reserve-target">${[3,6,9,12].map(value=>`<option value="${value}" ${value===(state.configuracoesFinanceiras?.reservaMeses||6)?'selected':''}>${value} meses</option>`).join('')}</select></div><button class="btn btn-primary" id="btn-save-profile">Salvar perfil</button><div id="profile-status" role="status" aria-live="polite"></div></div></section>`;
  const aplicativo=()=>`<section class="section"><div class="section-head"><h2>Instalação e offline</h2></div><div class="history-note"><p>O navegador pode instalar o FinTrack e manter os recursos visitados disponíveis offline.</p><p>Armazenamento ativo: <strong>${esc(FinTrackStorage.adapter)}</strong>.</p><p>As informações continuam neste navegador, mesmo quando o aplicativo está instalado.</p></div></section><section class="section"><div class="section-head"><h2>Lembretes da Agenda</h2></div><div class="planning-fields"><p>A permissão só será solicitada por uma ação explícita. Nenhum lançamento será criado.</p><button class="btn btn-primary" id="btn-enable-notifications">Ativar lembretes locais</button><div id="notification-status" role="status" aria-live="polite"></div></div></section>`;
  const dados=()=>`<section class="section"><div class="section-head"><h2>Dados locais</h2></div><p>Armazenamento ativo: <strong>${esc(FinTrackStorage.adapter)}</strong>. Use estas ações para transportar ou recuperar seus dados.</p><div class="footer-actions"><button class="btn btn-primary" data-config-action="backup">Exportar backup</button><label class="btn btn-primary" for="config-import">Importar backup</label><input id="config-import" type="file" accept="application/json,.json" hidden><button class="btn btn-ghost" data-config-action="recovery">Arquivo de recuperação</button><button class="btn danger-ghost" data-config-action="clear-data">Limpar dados</button></div></section>`;
  const importacoes=()=>`<section class="section"><div class="section-head"><h2>Regras de categoria</h2></div><p class="history-note">Regras explícitas têm prioridade sobre o histórico recorrente. Sugestões aparecem com o motivo e podem ser alteradas antes de salvar. Textos genéricos como PIX e PAGAMENTO não podem virar regras.</p><div class="bank-map-grid"><label>Texto específico na descrição<input id="bank-rule-pattern" maxlength="80" placeholder="Ex.: mercado central"></label><label>Tipo<select id="bank-rule-type"><option>Despesa</option><option>Receita</option></select></label><label>Categoria<select id="bank-rule-category">${state.categorias.filter(category=>category.tipo==='Saída'&&category.natureza!=='movimentacao').map(category=>`<option value="${esc(category.id)}">${esc(category.nome)}</option>`).join('')}</select></label></div><p id="bank-rule-error" class="form-error" role="alert"></p><button class="btn btn-primary" id="bank-rule-add">Adicionar regra</button><div class="bank-rule-list">${(state.importRules||[]).map(rule=>`<div class="bank-batch"><span>${esc(rule.pattern)} → ${esc(state.categorias.find(category=>category.id===rule.categoryId)?.nome||'Categoria removida')} (${esc(rule.type)})</span><button class="btn btn-ghost" data-bank-remove-rule="${esc(rule.id)}">Remover</button></div>`).join('')||'<p>Nenhuma regra cadastrada.</p>'}</div></section>`;
  window.renderConfiguracoesView=function(){const content=configuracoesTab==='aplicativo'?aplicativo():configuracoesTab==='dados'?dados():configuracoesTab==='importacoes'?importacoes():geral();return `<div class="page-header"><div class="page-heading"><h1 class="page-title">Configurações</h1><p class="page-sub">Perfil, aplicativo e gestão dos dados locais</p></div></div>${tabs()}${content}`;};
  window.saveProfileName=saveName;FinTrackViews.register('configuracoes',()=>window.renderConfiguracoesView());
})();
