(function(){
  const defaults=()=>{const today=todayLocal(),year=Number(today.slice(0,4)),month=Number(today.slice(5,7)),lastDay=new Date(year,month,0).getDate();return {from:`${today.slice(0,7)}-01`,to:`${today.slice(0,7)}-${String(lastDay).padStart(2,'0')}`,accountId:'',categoryId:'todas',kind:'todos',status:'todos',search:''};};
  let filters=null;
  const kinds=[['todos','Todos os tipos'],['receita','Receitas'],['despesa','Despesas'],['investimento','Investimentos'],['transferencia','Transferências'],['pagamento_cartao','Pagamentos de fatura'],['pagamento_divida','Pagamentos de dívida']];
  const statusLabel=status=>status==='Pago'?'Pago':'Pendente';
  window.getFinancialStatementFilters=()=>({...filters||defaults()});
  window.setFinancialStatementFilters=next=>{filters={...defaults(),...next};};
  window.renderExtratoView=function(){
    const current=filters||defaults(),result=FinancialStatementService.query(state,current),total=result.totals;
    const columns=[
      {label:'Data',render:row=>formatDate(row.entry.data)},
      {label:'Descrição',render:row=>`<strong>${esc(row.entry.descricao||row.label)}</strong><small class="ledger-kind">${esc(row.label)}</small>`},
      {label:'Conta',render:row=>esc(contaById(row.entry.contaId)?.nome||'—')},
      {label:'Categoria',render:row=>esc(catById(row.entry.categoriaId)?.nome||'—')},
      {label:'Status',render:row=>`<span class="badge ${row.entry.status==='Pago'?'badge-paid':'badge-pending'}">${statusLabel(row.entry.status)}</span>`},
      {label:'Valor',numeric:true,render:row=>`<strong class="${row.signed>0?'money-in':row.signed<0?'money-out':''}">${row.signed>0?'+ ':row.signed<0?'− ':''}${formatMoney(Math.abs(row.signed))}</strong>`},
      {label:'',render:row=>`<button type="button" class="btn btn-ghost btn-sm" data-statement-entry="${esc(row.entry.id)}" aria-label="Abrir lançamento ${esc(row.entry.descricao)}">Abrir</button>`}
    ];
    const table=FinancialLedgerTable.render({label:'Extrato financeiro',rows:result.rows,columns,emptyTitle:'Nenhuma movimentação encontrada',emptyDescription:'Revise o período e os filtros ou consulte outro intervalo.'});
    return `<div class="page-header"><div class="page-heading"><h1 class="page-title">Extrato financeiro</h1><p class="page-sub">Movimentações consolidadas e filtráveis, sem confundir resultado operacional com transferências ou investimentos</p></div><div class="page-actions"><button type="button" class="btn btn-ghost" id="btn-export-statement-csv">Exportar extrato CSV</button></div></div>
      <section class="section statement-filters" aria-labelledby="statement-filters-title"><div class="section-head"><h2 id="statement-filters-title">Período e filtros</h2><button type="button" class="btn btn-ghost btn-sm" id="btn-reset-statement-filters">Limpar filtros</button></div><div class="filters statement-filter-grid"><div class="field"><label for="statement-from">De</label><input type="date" id="statement-from" value="${esc(current.from)}"></div><div class="field"><label for="statement-to">Até</label><input type="date" id="statement-to" value="${esc(current.to)}"></div><div class="field"><label for="statement-account">Conta</label><select id="statement-account"><option value="">Todas as contas</option>${state.contas.map(item=>`<option value="${esc(item.id)}" ${current.accountId===item.id?'selected':''}>${esc(item.nome)}</option>`).join('')}</select></div><div class="field"><label for="statement-category">Categoria</label><select id="statement-category"><option value="todas">Todas as categorias</option>${state.categorias.map(item=>`<option value="${esc(item.id)}" ${current.categoryId===item.id?'selected':''}>${esc(item.nome)}</option>`).join('')}</select></div><div class="field"><label for="statement-kind">Tipo</label><select id="statement-kind">${kinds.map(([value,label])=>`<option value="${value}" ${current.kind===value?'selected':''}>${label}</option>`).join('')}</select></div><div class="field"><label for="statement-status">Status</label><select id="statement-status"><option value="todos" ${current.status==='todos'?'selected':''}>Todos os status</option><option value="Pago" ${current.status==='Pago'?'selected':''}>Pago</option><option value="Pendente" ${current.status==='Pendente'?'selected':''}>Pendente</option></select></div><div class="field statement-search"><label for="statement-search">Descrição</label><input type="search" id="statement-search" value="${esc(current.search)}" placeholder="Buscar movimentação"></div><button type="button" class="btn btn-primary statement-apply" id="btn-apply-statement-filters">Aplicar filtros</button></div><p id="statement-filter-error" class="statement-filter-error" role="alert" hidden></p></section>
      <section class="section statement-summary" aria-label="Resumo do extrato"><div class="statement-metrics">${MetricCard.render({label:'Entradas confirmadas',value:formatMoney(total.inflowsPaid),tone:'positive'})}${MetricCard.render({label:'Saídas confirmadas',value:formatMoney(total.outflowsPaid),tone:'negative'})}${MetricCard.render({label:'Variação confirmada',value:formatMoney(total.netMovement),tone:total.netMovement>=0?'positive':'negative'})}${MetricCard.render({label:'Resultado operacional pago',value:formatMoney(total.operatingResult),detail:`Receitas ${formatMoney(total.income)} − despesas ${formatMoney(total.expenses)}`,tone:total.operatingResult>=0?'positive':'negative'})}</div><p class="statement-pending-summary"><strong>Pendente:</strong> ${formatMoney(total.inflowsPending)} em entradas e ${formatMoney(total.outflowsPending)} em saídas · variação estimada após pendências: <strong>${formatMoney(total.projectedMovement)}</strong></p><p class="statement-method-note">${total.count} movimentação(ões) no recorte. O resultado operacional considera apenas receitas e despesas pagas; exclui investimentos, transferências internas e pagamentos de fatura/dívida. A variação confirmada representa movimentos pagos; pendências aparecem separadas, e pagamentos de cartão não duplicam o gasto das compras.</p></section>
      <section class="section statement-ledger"><div class="section-head"><h2>Movimentações</h2><span class="stat-meta">${total.count} registro(s)</span></div>${table}</section>`;
  };
  FinTrackViews.register('extrato',()=>window.renderExtratoView());
})();
