(function(){
  const monthLabel=key=>{const [year,month]=key.split('-').map(Number);return `${MESES[month-1]} de ${year}`;};
  const variation=(current,previous)=>previous?Math.round(((current-previous)/Math.abs(previous))*100):null;
  const metricCard=(label,key,snapshot,previous)=>{const change=previous?variation(snapshot[key]||0,previous[key]||0):null;return `<div class="stat-card"><div class="stat-label">${label}</div><div class="stat-value">${formatMoney(snapshot[key]||0)}</div>${previous?`<div class="stat-meta">${change===null?'Sem base':`${change>0?'+':''}${change}%`} vs. mês anterior</div>`:''}</div>`;};
  window.renderHistoricoView=function(){
    const entries=Object.entries(state.fechamentos||{}).filter(([,item])=>item?.snapshot).sort(([a],[b])=>b.localeCompare(a));
    if(!entries.length)return `<div class="page-header"><div class="page-heading"><h1 class="page-title">Histórico mensal</h1><p class="page-sub">Consulte períodos encerrados sem recalcular os dados atuais</p></div></div>${emptyState('Nenhum mês fechado','Feche um mês em Planejamento para criar o primeiro snapshot histórico.')}`;
    const selectedKey=historicoMes&&state.fechamentos[historicoMes]?.snapshot?historicoMes:entries[0][0];
    const closing=state.fechamentos[selectedKey],snapshot=closing.snapshot||{},index=entries.findIndex(([key])=>key===selectedKey),previous=index>=0&&entries[index+1]?.[1]?.snapshot;
    const years=[...new Set(entries.map(([key])=>key.slice(0,4)))],metrics=[['Receitas','receitas'],['Despesas','despesas'],['Investimentos','investimentos'],['Resultado','resultado']];
    const calendar=years.map(year=>`<div><strong>${year}</strong><div class="closing-months">${MESES.map((name,i)=>{const key=`${year}-${String(i+1).padStart(2,'0')}`,item=state.fechamentos[key];return `<button class="closing-month ${key===selectedKey?'active':''}" data-action="select-closing" data-key="${key}" ${item?.snapshot?'':'disabled'}>${name}${item?.snapshot?' ✓':''}</button>`;}).join('')}</div></div>`).join('');
    const accounts=snapshot.contas?.length?`<div class="history-block"><h3>Saldos por conta</h3><table><thead><tr><th>Conta</th><th class="num">Saldo no fechamento</th></tr></thead><tbody>${snapshot.contas.map(account=>`<tr><td>${esc(account.nome)}</td><td class="num">${formatMoney(account.saldo)}</td></tr>`).join('')}</tbody></table></div>`:'';
    const transactions=snapshot.lancamentosDetalhados?.length?`<div class="history-block"><h3>Lançamentos congelados</h3><table><thead><tr><th>Data</th><th>Descrição</th><th>Categoria</th><th>Conta</th><th>Status</th><th class="num">Valor</th></tr></thead><tbody>${snapshot.lancamentosDetalhados.map(item=>`<tr><td>${formatDate(item.data)}</td><td>${esc(item.descricao)}</td><td>${esc(item.categoriaNome||'—')}</td><td>${esc(item.contaNome||'—')}</td><td>${esc(item.status)}</td><td class="num">${formatMoney(item.valor)}</td></tr>`).join('')}</tbody></table></div>`:'<div class="empty-state">Snapshot legado: detalhes não estavam disponíveis nesta versão.</div>';
    return `<div class="page-header"><div class="page-heading"><h1 class="page-title">Histórico mensal</h1><p class="page-sub">Snapshots permanentes dos meses encerrados</p></div></div><div class="section"><div class="section-head"><h2>Meses fechados</h2><span class="stat-meta">${entries.length} período(s)</span></div><div class="closing-calendar">${calendar}</div></div><div class="section"><div class="section-head"><div><h2>${monthLabel(selectedKey)}</h2><p class="section-sub">Fechado em ${formatDate(String(closing.fechadoEm||'').slice(0,10))}</p></div><div class="page-actions"><span class="badge ${closing.status==='fechado'?'badge-paid':'badge-pending'}">${closing.status==='fechado'?'Fechado':'Reaberto'}</span><button class="btn btn-ghost" data-action="export-closing-pdf" data-key="${selectedKey}">Gerar PDF</button></div></div><div class="cards-row snapshot-cards">${metrics.map(([label,key])=>metricCard(label,key,snapshot,previous)).join('')}</div>${accounts}${transactions}${closing.observacao?`<div class="history-note"><strong>Observação</strong><p>${esc(closing.observacao)}</p></div>`:''}</div>`;
  };
  window.FinTrackViews.register('historico',()=>window.renderHistoricoView());
})();
