(function(){
  const monthNames=['Janeiro','Fevereiro','Março','Abril','Maio','Junho','Julho','Agosto','Setembro','Outubro','Novembro','Dezembro'];
  const monthLabel=key=>{const [year,month]=key.split('-').map(Number);return `${monthNames[month-1]} de ${year}`;};
  const variation=(current,previous)=>previous?Math.round(((current-previous)/Math.abs(previous))*100):null;
  const isPreviousMonth=(current,previous)=>{const [cy,cm]=current.split('-').map(Number),[py,pm]=previous.split('-').map(Number),date=new Date(cy,cm-2,1);return date.getFullYear()===py&&date.getMonth()+1===pm;};
  const comparisonLabel=(currentKey,previousKey)=>previousKey?`vs. ${monthLabel(previousKey)}${isPreviousMonth(currentKey,previousKey)?'':', último mês fechado'}`:'';
  const metricCard=(label,key,snapshot,previous,labelComparison)=>{const change=previous?variation(snapshot[key]||0,previous[key]||0):null;return `<div class="stat-card"><div class="stat-label">${label}</div><div class="stat-value">${formatMoney(snapshot[key]||0)}</div>${previous?`<div class="stat-meta">${change===null?'Sem base':`${change>0?'+':''}${change}%`} ${labelComparison}</div>`:''}</div>`;};
  window.renderHistoricoView=function(){
    const entries=Object.entries(state.fechamentos||{}).filter(([,item])=>item?.snapshot).sort(([a],[b])=>b.localeCompare(a));
    if(!entries.length)return `<div class="page-header"><div class="page-heading"><h1 class="page-title">Histórico mensal</h1><p class="page-sub">Consulte períodos encerrados sem recalcular os dados atuais</p></div></div>${emptyState('Nenhum mês fechado','Feche um mês em Planejamento para criar o primeiro snapshot histórico.')}`;
    const selectedKey=historicoMes&&state.fechamentos[historicoMes]?.snapshot?historicoMes:entries[0][0];
    const closing=state.fechamentos[selectedKey],snapshot=FinTrackClosing.readSnapshot(closing.snapshot),index=entries.findIndex(([key])=>key===selectedKey),previousEntry=index>=0?entries[index+1]:null,previous=previousEntry?FinTrackClosing.readSnapshot(previousEntry[1].snapshot):null,compareText=comparisonLabel(selectedKey,previousEntry?.[0]);
    const stats=FinTrackClosing.historicalStats(state.fechamentos),years=[...new Set(entries.map(([key])=>key.slice(0,4)))],metrics=[['Receitas','receitas'],['Despesas','despesas'],['Investimentos','investimentos'],['Resultado','resultado']];
    const calendar=years.map(year=>`<div><strong>${year}</strong><div class="closing-months">${MESES.map((name,i)=>{const key=`${year}-${String(i+1).padStart(2,'0')}`,item=state.fechamentos[key];return `<button class="closing-month ${key===selectedKey?'active':''}" data-action="select-closing" data-key="${key}" ${item?.snapshot?'':'disabled'}>${name}${item?.snapshot?' ✓':''}</button>`;}).join('')}</div></div>`).join('');
    const averages=`<div class="section"><div class="section-head"><h2>Estatísticas dos fechamentos</h2><span class="stat-meta">${stats.quantidade} período(s)</span></div><div class="cards-row snapshot-cards">${[['Média de receitas','receitas'],['Média de despesas','despesas'],['Média investida','investimentos'],['Resultado médio','resultado']].map(([label,key])=>`<div class="stat-card"><div class="stat-label">${label}</div><div class="stat-value">${formatMoney(stats.medias[key])}</div></div>`).join('')}</div><div class="summary-strip"><span>Melhor mês: <strong>${monthLabel(stats.melhor.key)} · ${formatMoney(stats.melhor.snapshot.resultado)}</strong></span><span>Pior mês: <strong>${monthLabel(stats.pior.key)} · ${formatMoney(stats.pior.snapshot.resultado)}</strong></span></div></div>`;
    const accounts=snapshot.contas?.length?`<div class="history-block"><h3>Saldos por conta</h3><table><thead><tr><th>Conta</th><th class="num">Saldo no fechamento</th></tr></thead><tbody>${snapshot.contas.map(account=>`<tr><td>${esc(account.nome)}</td><td class="num">${formatMoney(account.saldo)}</td></tr>`).join('')}</tbody></table></div>`:'';
    const budgets=snapshot.orcamentoDetalhado?.length?`<div class="history-block"><h3>Orçamento congelado</h3><table><thead><tr><th>Categoria</th><th class="num">Planejado</th><th class="num">Realizado</th><th class="num">Pendente</th><th class="num">Comprometido</th><th class="num">Disponível</th></tr></thead><tbody>${snapshot.orcamentoDetalhado.map(item=>`<tr><td>${esc(item.categoriaNome||'Categoria removida')}</td><td class="num">${formatMoney(item.orcado)}</td><td class="num">${formatMoney(item.realizado)}</td><td class="num">${item.pendente==null?'Indisponível':formatMoney(item.pendente)}</td><td class="num">${item.comprometido==null?'Indisponível':formatMoney(item.comprometido)}</td><td class="num">${formatMoney(item.disponivel)}</td></tr>`).join('')}</tbody></table></div>`:'';
    const transactions=snapshot.lancamentosDetalhados?.length?`<div class="history-block"><h3>Lançamentos congelados</h3><table><thead><tr><th>Data</th><th>Descrição</th><th>Categoria</th><th>Conta</th><th>Status</th><th class="num">Valor</th></tr></thead><tbody>${snapshot.lancamentosDetalhados.map(item=>`<tr><td>${formatDate(item.data)}</td><td>${esc(item.descricao)}</td><td>${esc(item.categoriaNome||'—')}</td><td>${esc(item.contaNome||'—')}</td><td>${esc(item.status)}</td><td class="num">${formatMoney(item.valor)}</td></tr>`).join('')}</tbody></table></div>`:'<div class="empty-state">Snapshot legado: detalhes não estavam disponíveis nesta versão.</div>';
    const legacyNotice=snapshot.compatibilidade.legado?'<div class="history-note"><strong>Snapshot legado</strong><p>Este fechamento foi preservado em sua versão original. Campos que não existiam na época não foram recalculados com dados atuais.</p></div>':'';
    return `<div class="page-header"><div class="page-heading"><h1 class="page-title">Histórico mensal</h1><p class="page-sub">Snapshots permanentes dos meses encerrados</p></div></div>${averages}<div class="section"><div class="section-head"><h2>Meses fechados</h2><span class="stat-meta">${entries.length} período(s)</span></div><div class="closing-calendar">${calendar}</div></div><div class="section"><div class="section-head"><div><h2>${monthLabel(selectedKey)}</h2><p class="section-sub">Fechado em ${formatDate(String(closing.fechadoEm||'').slice(0,10))}</p></div><div class="page-actions"><span class="badge ${closing.status==='fechado'?'badge-paid':'badge-pending'}">${closing.status==='fechado'?'Fechado':'Reaberto'}</span><button class="btn btn-ghost" data-action="export-closing-pdf" data-key="${selectedKey}">Gerar PDF</button></div></div><div class="cards-row snapshot-cards">${metrics.map(([label,key])=>metricCard(label,key,snapshot,previous,compareText)).join('')}</div>${legacyNotice}${accounts}${budgets}${transactions}${closing.observacao?`<div class="history-note"><strong>Observação</strong><p>${esc(closing.observacao)}</p></div>`:''}</div>`;
  };
  const baseHistorico=window.renderHistoricoView;window.renderHistoricoView=function(){const chart=FinTrackCharts.groupedBars({title:'Resultados históricos',question:'Quais meses fecharam positivos ou negativos?',summary:'Valores lidos exclusivamente dos snapshots existentes.',data:ChartDataService.history(state),keys:[{value:'value',label:'Resultado'}]});return `<div class="dashboard-grid">${chart}</div>${baseHistorico()}`;};
  window.FinTrackViews.register('historico',()=>window.renderHistoricoView());
})();
