(function(){
  const stateTone=value=>value<0?'negative':value>0?'positive':'neutral';
  const metric=(label,value,options={})=>MetricCard.render({label,value:formatMoney(value),tone:options.tone||stateTone(value),comparison:options.comparison,trend:options.trend,detail:options.detail,sparkline:options.sparkline});
  function sparkline(values){const safe=values.map(Number),min=Math.min(...safe),max=Math.max(...safe),span=max-min||1,points=safe.map((value,index)=>`${4+index*42},${26-(value-min)/span*20}`).join(' ');return `<svg viewBox="0 0 92 30" focusable="false"><polyline points="${points}" fill="none" stroke="currentColor" stroke-width="2"/>${safe.map((value,index)=>`<circle cx="${4+index*42}" cy="${26-(value-min)/span*20}" r="2"/>`).join('')}</svg>`;}
  function comparison(current,previous,label){if(!previous)return 'Sem base no período anterior';const percent=Math.round((current/previous-1)*100);return `${percent>0?'+':''}${percent}% vs ${label}`;}
  function todayPanel(pending,projected,categories,month,year){const today=todayLocal(),due=pending.filter(item=>(item.dataVencimento||item.data)<=today),total=due.reduce((sum,item)=>sum+Number(item.valor||0),0),risk=categories.map(category=>({category,budget:resumoOrcamento(category.id,month,year,category.orcado)})).sort((a,b)=>b.budget.percentualComprometido-a.budget.percentualComprometido)[0],action=due.length?`Regularize ${due.length} vencimento(s).`:risk?.budget.percentualComprometido>=80?`Revise ${risk.category.nome}.`:'Mantenha os lançamentos atualizados.';return DataPanel.render({title:'O que fazer hoje',question:'Prioridade financeira',state:due.length?'critico':risk?.budget.percentualComprometido>=80?'atencao':'normal',content:`<div class="metric-grid today-grid">${MetricCard.render({label:'Vencimentos',value:String(due.length),tone:due.length?'negative':'positive',detail:formatMoney(total)})}${metric('Saldo projetado',projected,{detail:'Após pendências'})}${MetricCard.render({label:'Próxima ação',value:action,tone:due.length?'negative':'neutral',detail:due.length?`${formatMoney(total)} aguardam pagamento.`:'Sem urgências vencidas.'})}</div>`});}
  window.renderHome=function(){
    const now=new Date(),month=now.getMonth()+1,year=now.getFullYear(),key=`${year}-${String(month).padStart(2,'0')}`,previousDate=new Date(year,month-2,1),previousLabel=`${MESES[previousDate.getMonth()]} de ${previousDate.getFullYear()}`,summary=resumoFinanceiroDoMes(month,year),previous=totaisDoMes(previousDate.getMonth()+1,previousDate.getFullYear()),accounts=state.contas.reduce((sum,item)=>sum+saldoAtualConta(item),0),patrimony=PatrimonyService.summary(state,todayLocal()),pending=state.lancamentos.filter(item=>item.status==='Pendente'&&serieEstaAtiva(item)&&naturezaLancamento(item)!=='transferencia'),projected=accounts+summary.receitasPendentes-summary.despesasPendentes,categories=state.categorias.filter(item=>item.tipo==='Saída'&&item.orcado>0),recent=[...state.lancamentos].sort((a,b)=>String(b.data).localeCompare(String(a.data))).slice(0,5),readings=InsightService.detect(state,{today:todayLocal(),limit:3}).map(item=>InsightPresenter.present(item,{money:formatMoney}));
    const chartData={cashflow:ChartDataService.cashflow(state,key,6),budgets:ChartDataService.budgets(state,key).slice(0,6),projection:ChartDataService.projection(state,key),patrimony:ChartDataService.patrimony(state),categories:ChartDataService.categories(state,key),daily:ChartDataService.dailyBalance(state,key)};
    const lastThree=chartData.cashflow.slice(-3),patrimonyTrend=chartData.patrimony.slice(-3).map(item=>item.value),cards=`<div class="metric-grid cards-row">${metric('Receitas',summary.receitasRealizadas,{comparison:comparison(summary.receitasRealizadas,previous.receitas,previousLabel),trend:summary.receitasRealizadas>=previous.receitas?'up':'down',sparkline:sparkline(lastThree.map(item=>item.receitas))})}${metric('Despesas',summary.despesasRealizadas,{tone:'negative',comparison:comparison(summary.despesasRealizadas,previous.despesas,previousLabel),trend:summary.despesasRealizadas<=previous.despesas?'up':'down',sparkline:sparkline(lastThree.map(item=>item.despesas))})}${metric('Resultado',summary.resultadoRealizado,{comparison:comparison(summary.resultadoRealizado,previous.resultado,previousLabel),trend:summary.resultadoRealizado>=previous.resultado?'up':'down',sparkline:sparkline(lastThree.map(item=>item.receitas-item.despesas))})}${metric('Patrimônio líquido',patrimony.liquido,{detail:'Contas + investimentos − dívidas',sparkline:patrimonyTrend.length?sparkline(patrimonyTrend):''})}</div>`;
    const charts=`<div class="dashboard-grid">${FinTrackCharts.groupedBars({title:'Receitas × despesas',question:'Estou mantendo despesas abaixo da renda?',summary:'Últimos seis meses realizados.',data:chartData.cashflow,keys:[{value:'receitas',label:'Receitas'},{value:'despesas',label:'Despesas'}]})}${FinTrackCharts.horizontalBars({title:'Orçamento comprometido',question:'Onde estou gastando acima do planejado?',summary:'Percentual real preservado; barra limitada visualmente.',data:chartData.budgets.map(item=>({label:item.label,value:item.percentual})),format:value=>`${value}%`})}${FinTrackCharts.area({title:'Saldo projetado',question:'Meu saldo deve melhorar ou piorar?',summary:'Projeção determinística dos próximos três meses.',data:chartData.projection})}${FinTrackCharts.line({title:'Evolução patrimonial',question:'Meu patrimônio está crescendo?',summary:'Somente snapshots v4.',data:chartData.patrimony})}${FinTrackCharts.donut({title:'Despesas por categoria',question:'Para onde meu dinheiro está indo?',summary:'Cinco categorias principais e Outros.',data:chartData.categories,format:formatMoney})}${FinTrackCharts.line({title:'Saldo diário do mês',question:'Como meu caixa variou ao longo do mês?',summary:'Saldo das contas ao fim de cada dia.',data:chartData.daily})}</div>`;
    const lead=readings[0],insight=lead?InsightCard.render({headline:lead.headline,state:['critica','alta'].includes(lead.severity)?'critico':lead.severity==='media'?'atencao':'normal',label:lead.severity,metrics:lead.metrics.slice(0,2).map(value=>({label:value.label,value:value.format==='money'?formatMoney(value.value):value.format==='percent'?`${value.value}%`:value.value})),message:lead.comparison,details:readings.map(item=>`${item.headline}: ${item.details}`).join(' '),action:{label:lead.actionLabel,target:lead.actionTarget}}):InsightCard.render({headline:'Mês sob controle',state:'normal',label:'Normal',message:'Nenhum sinal relevante neste momento.'});
    const health=calcularSaudeFinanceira(month,year),classification=health.pontos>=80?'Normal':health.pontos>=55?'Atenção':'Crítico',cause=health.fatores[0]||'Nenhum fator crítico identificado.',healthPanel=DataPanel.render({title:'Saúde financeira',question:'Síntese determinística do mês',state:classification==='Crítico'?'critico':classification==='Atenção'?'atencao':'normal',summary:`${health.pontos}/100 · ${classification} · ${cause}`,content:`<details class="health-diagnostic"><summary>Ver diagnóstico</summary><ul>${health.componentes.map(item=>`<li><strong>${esc(item.nome)}: ${item.pontos}/${item.max}</strong><span>${esc(item.detalhe)}</span></li>`).join('')}</ul></details>`});
    const finance=ChartDataService.financialSentence(state,key),sentence=`${finance.state}: o resultado após investimentos é ${formatMoney(finance.net)} e a tendência de três meses ${finance.trend}.`;
    const recentContent=recent.length?`<div class="recent-list">${recent.map(item=>`<article><span>${formatDate(item.data)}</span><strong>${esc(item.descricao)}</strong><small>${esc(catById(item.categoriaId)?.nome||'Sem categoria')}</small><b class="${item.tipo==='Receita'?'money-in':'money-out'}">${formatMoney(item.valor)}</b></article>`).join('')}</div>`:emptyState('Nenhum lançamento ainda','Cadastre seu primeiro lançamento em Movimentações.');
    return `<div class="page-header"><div class="page-heading"><h1 class="page-title">Olá${state.usuario?.nome?`, ${esc(state.usuario.nome)}`:''} 👋</h1><p class="page-sub">Resumo de ${MESES[month-1]} de ${year}</p></div><div class="page-actions"><button class="btn btn-primary" id="btn-novo-lancamento">Novo lançamento</button></div></div>${!state.usuario?.nome&&!state.usuario?.onboardingIgnorado?`<div class="section profile-welcome"><div><strong>Bem-vindo ao FinTrack</strong><p>Defina como gostaria de ser chamado.</p></div><button class="btn btn-ghost" data-insight-target="configuracoes">Configurar perfil</button></div>`:''}<p class="financial-sentence state-${finance.state.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'')}">${esc(sentence)}</p>${cards}${todayPanel(pending,projected,categories,month,year)}${DataPanel.render({title:'Leitura financeira',question:'O que merece atenção neste mês?',summary:'Uma leitura principal com evidências recolhidas',content:insight})}${healthPanel}${charts}${DataPanel.render({title:'Lançamentos recentes',question:'Últimas movimentações registradas',content:recentContent,action:{label:'Ver todos',target:'lancamentos'}})}`;
  };
  FinTrackViews.register('home',()=>window.renderHome());
})();
