(function(){
  'use strict';
  const comparison=(current,previous,label)=>previous?`${Math.round((current/previous-1)*100)>0?'+':''}${Math.round((current/previous-1)*100)}% vs ${label}`:'Sem base no período anterior';
  const actionPanel=actions=>DataPanel.render({title:'Próximas ações',question:'O que posso fazer agora?',summary:'Até três ações ordenadas por relevância.',content:`<ol class="decision-actions">${actions.map(action=>`<li><span>${action.rank}</span><div><strong>${esc(action.title)}</strong><p>${esc(action.effect)}</p></div><button class="btn btn-ghost btn-sm" data-insight-target="${esc(action.target)}" data-insight-month="${esc(action.month||'')}" data-insight-category="${esc(action.categoryId||'')}" data-insight-date="${esc(action.date||'')}" data-insight-entity="${esc(action.entityId||'')}" aria-label="Agir: ${esc(action.title)}">Agir</button></li>`).join('')}</ol>`,action:{label:'Ver central',target:'analises'}});
  const insightCard=item=>{const lead=InsightPresenter.present(item,{money:formatMoney}),route=FinTrackInsightRoutes.forInsight(item,state);return InsightCard.render({headline:lead.headline,state:['critica','alta'].includes(lead.severity)?'critico':lead.severity==='media'?'atencao':'normal',label:`Relevância ${item.relevancia}/100`,metrics:lead.metrics.slice(0,2).map(value=>({label:value.label,value:value.format==='money'?formatMoney(value.value):value.format==='percent'?`${value.value}%`:value.value})),message:lead.comparison||item.mensagem,details:lead.details,provenance:lead.provenance,limitation:lead.limitation,action:{label:lead.actionLabel,target:route.view,month:route.month,categoryId:route.categoryId,date:route.date,entityId:route.entityId}});};
  function healthPanel(health){return DataPanel.render({title:'Saúde financeira',question:'Por que minha nota está neste nível?',state:health.status,size:'compact',content:`<div class="health-score"><div><strong>${health.score}<small>/100</small></strong><span>${esc(health.classification)}</span></div><div class="health-main"><span>Principal atenção</span><strong>${esc(health.mainAttention)}</strong><div class="health-progress" role="progressbar" aria-label="Saúde financeira" aria-valuemin="0" aria-valuemax="100" aria-valuenow="${health.score}"><i style="width:${health.score}%"></i></div></div></div>${health.losses.length?`<div class="health-losses">${health.losses.map(item=>`<span>▼ −${item.loss} ${esc(item.name)}</span>`).join('')}</div>`:''}<details class="health-diagnostic"><summary>Ver diagnóstico</summary><ul>${health.components.map(item=>`<li><div><strong>${esc(item.name)} <b>${item.points}/${item.max}</b></strong><div class="criterion-progress"><i style="width:${Math.round(item.points/item.max*100)}%"></i></div><span>${esc(item.detail)}</span></div></li>`).join('')}</ul>${health.losses.length?`<div class="health-actions"><strong>Como melhorar sua nota</strong><ol>${health.losses.map(item=>`<li>${esc(item.detail)}</li>`).join('')}</ol><p>Potencial após os ajustes: até <strong>${health.potential}/100</strong>.</p></div>`:''}</details>`});}
  function recentEntries(entries){if(!entries.length)return EmptyState.render({title:'Nenhum lançamento ainda',description:'Cadastre seu primeiro lançamento para acompanhar sua situação.',action:{label:'Adicionar lançamento',target:'lancamentos'}});return `<div class="recent-table"><table><thead><tr><th>Data</th><th>Descrição</th><th>Categoria</th><th class="num">Valor</th></tr></thead><tbody>${entries.map(item=>`<tr><td>${formatDate(item.data)}</td><td>${esc(item.descricao)}</td><td>${esc(catById(item.categoriaId)?.nome||'Sem categoria')}</td><td class="num ${item.tipo==='Receita'?'money-in':'money-out'}">${formatMoney(item.valor)}</td></tr>`).join('')}</tbody></table></div><div class="recent-cards">${entries.map(item=>`<article><time>${formatDate(item.data)}</time><div><strong>${esc(item.descricao)}</strong><small>${esc(catById(item.categoriaId)?.nome||'Sem categoria')}</small></div><b class="${item.tipo==='Receita'?'money-in':'money-out'}">${formatMoney(item.valor)}</b></article>`).join('')}</div>`;}
  window.renderHome=function(){
    const today=todayLocal(),now=new Date(`${today}T12:00:00`),month=now.getMonth()+1,year=now.getFullYear(),key=today.slice(0,7),previousDate=new Date(year,month-2,1),previousLabel=`${MESES[previousDate.getMonth()]} de ${previousDate.getFullYear()}`,summary=resumoFinanceiroDoMes(month,year),previous=totaisDoMes(previousDate.getMonth()+1,previousDate.getFullYear()),decision=DecisionService.evaluate(state,{today,limit:3}),available=(state.contas||[]).reduce((total,account)=>total+FinTrackCore.accountBalance(state,account,today),0),recent=[...(state.lancamentos||[])].sort((a,b)=>String(b.data).localeCompare(String(a.data))).slice(0,5),budget=CalendarAnalysisService.analyze(state,key,{mode:'orcamento',today}),todayIndex=Math.min(budget.days.length-1,Number(today.slice(8))-1),pace=budget.days[todayIndex],paceText=budget.summary.budget?`${formatMoney(Math.abs(pace.budgetVariance))} ${pace.budgetVariance>0?'acima':'abaixo'} do ritmo esperado até hoje.`:'Defina um orçamento para acompanhar seu ritmo diário.';
    const snapshot=FinancialSummary.render({balance:formatMoney(available),result:formatMoney(summary.resultadoRealizado),health:`${decision.health.score}/100`,healthLabel:decision.health.classification,comparison:comparison(summary.resultadoRealizado,previous.resultado,previousLabel)});
    const attention=DataPanel.render({title:'O que merece sua atenção',question:'Quais sinais importam agora?',summary:decision.insights.length?'Até três leituras priorizadas por impacto, urgência e qualidade.':'Nenhum sinal relevante foi identificado neste momento.',content:decision.insights.length?`<div class="attention-grid">${decision.insights.slice(0,3).map(insightCard).join('')}</div>`:EmptyState.render({title:'Mês sob controle',description:'Continue mantendo os lançamentos atualizados.',action:{label:'Ver análises',target:'analises'}})});
    const chartData=ChartDataService.cashflow(state,key,6),categories=ChartDataService.categories(state,key),charts=`<div class="dashboard-grid home-charts">${FinTrackCharts.groupedBars({title:'Fluxo do mês',question:'Receitas estão cobrindo as despesas?',summary:'Últimos seis meses realizados.',data:chartData,keys:[{value:'receitas',label:'Receitas'},{value:'despesas',label:'Despesas'}]})}${FinTrackCharts.donut({title:'Despesas por categoria',question:'Para onde foi meu dinheiro?',summary:'Cinco categorias principais e Outros.',data:categories,format:formatMoney})}</div>`;
    const rhythm=FinTrackCharts.multiLine({title:'Ritmo do orçamento',question:'Estou gastando no ritmo certo?',summary:paceText,data:budget.summary.budget?budget.budgetSeries:[],keys:[{value:'actual',label:'Gasto acumulado'},{value:'ideal',label:'Ritmo esperado'}],format:formatMoney,tooltipContent:row=>({title:`Dia ${row.label}`,metrics:[{label:'Gasto acumulado',value:formatMoney(row.actual)},{label:'Ritmo esperado',value:formatMoney(row.ideal)},{label:'Diferença',value:formatMoney(row.actual-row.ideal)}]}),empty:{title:'Orçamento não definido',message:'Defina limites mensais no Planejamento para ver esta comparação.',action:{label:'Definir orçamento',target:'planejamento'}}});
    const finance=ChartDataService.financialSentence(state,key),sentence=`${finance.state}: o resultado após investimentos é ${formatMoney(finance.net)} e a tendência de três meses ${finance.trend}.`;
    return `<div class="page-header"><div class="page-heading"><h1 class="page-title">Olá${state.usuario?.nome?`, ${esc(state.usuario.nome)}`:''} 👋</h1><p class="page-sub">Sua visão financeira de ${MESES[month-1]} de ${year}</p></div><div class="page-actions"><button class="btn btn-primary" id="btn-novo-lancamento">Novo lançamento</button></div></div>${!state.usuario?.nome&&!state.usuario?.onboardingIgnorado?`<div class="section profile-welcome"><div><strong>Bem-vindo ao FinTrack</strong><p>Defina como gostaria de ser chamado.</p></div><button class="btn btn-ghost" data-insight-target="configuracoes">Configurar perfil</button></div>`:''}<p class="financial-sentence state-${finance.state.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'')}">${esc(sentence)}</p>${snapshot}${attention}${actionPanel(decision.actions)}${charts}<div class="dashboard-grid">${rhythm}</div>${healthPanel(decision.health)}${DataPanel.render({title:'Lançamentos recentes',question:'Últimas movimentações registradas',content:recentEntries(recent),action:{label:'Ver todos',target:'lancamentos'}})}`;
  };
  FinTrackViews.register('home',()=>window.renderHome());
})();
