(function(){
  function actionButtons(l){
    return `<div class="row-actions"><button class="icon-btn" data-action="edit-lanc" data-id="${l.id}">Editar</button>${l.serieId?`<button class="icon-btn" data-action="toggle-serie" data-id="${l.serieId}">${serieEstaAtiva(l)?'Pausar série':'Retomar série'}</button>`:''}<button class="icon-btn" data-action="del-lanc" data-id="${l.id}">Excluir</button></div>`;
  }
  function renderMobileTransactions(items){
    return `<div class="transaction-mobile-list">${items.map(l=>`<article class="transaction-card"><div class="transaction-card-head"><div><span class="transaction-card-date">${formatDate(l.data)}</span><strong>${esc(l.descricao)}</strong></div><span class="${l.tipo==='Receita'?'money-in':'money-out'}">${l.tipo==='Receita'?'+':'-'} ${formatMoney(l.valor)}</span></div><div class="transaction-card-meta"><span>${esc(contaById(l.contaId)?.nome||'—')}</span><span>${esc(catById(l.categoriaId)?.nome||'—')}</span></div><div class="transaction-card-actions"><button class="badge ${l.status==='Pago'?'badge-paid':'badge-pending'}" data-action="toggle-status" data-id="${l.id}">${l.status}</button>${actionButtons(l)}</div></article>`).join('')}</div>`;
  }
  function renderTable(groups){
    const body=Object.entries(groups).map(([data,group])=>`<tr><th colspan="7" scope="rowgroup" class="group-title">${formatDate(data)}</th></tr>${group.map(l=>`<tr><td>${l.tipo}</td><td>${esc(l.descricao)}${l.fixa?' <span style="color:var(--muted);font-size:12px;">(fixa)</span>':''} ${serieLabel(l)}</td><td>${esc(contaById(l.contaId)?.nome||'—')}</td><td>${esc(catById(l.categoriaId)?.nome||'—')}</td><td class="num ${l.tipo==='Receita'?'money-in':'money-out'}">${l.tipo==='Receita'?'+':'-'} ${formatMoney(l.valor)}</td><td><span class="badge ${l.status==='Pago'?'badge-paid':'badge-pending'}" style="cursor:pointer;" data-action="toggle-status" data-id="${l.id}">${l.status}</span></td><td>${actionButtons(l)}</td></tr>`).join('')}`).join('');
    return FinancialLedgerTable.renderMarkup({label:'Lançamentos do período',className:'transaction-table',head:'<tr><th scope="col">Data</th><th scope="col">Descrição</th><th scope="col">Conta</th><th scope="col">Categoria</th><th scope="col" class="num">Valor</th><th scope="col">Status</th><th scope="col"></th></tr>',body});
  }
  window.renderLancamentosView=function(){
    const month=`${lancFiltro.ano}-${String(lancFiltro.mes).padStart(2,'0')}`,statement=FinancialStatementService.query(state,{from:`${month}-01`,to:`${month}-${String(new Date(lancFiltro.ano,lancFiltro.mes,0).getDate()).padStart(2,'0')}`,categoryId:lancFiltro.categoriaId,search:lancFiltro.busca,today:todayLocal()}),items=statement.rows.map(row=>row.entry),total=statement.totals.operatingResult;
    const displayed=lancMostrarTodos?items:items.slice(0,12),groups={};
    displayed.forEach(l=>(groups[l.data]||=[]).push(l));
    const content=items.length===0
      ? emptyState('Nada por aqui','Ajuste os filtros ou adicione um lançamento com o botão acima.')
      : `${renderMobileTransactions(displayed)}${renderTable(groups)}${items.length>12?`<div class="show-more"><button class="btn btn-ghost" id="btn-mostrar-lancamentos">${lancMostrarTodos?'Mostrar menos':`Mostrar todos (${items.length})`}</button></div>`:''}`;
    const batches=(state.importBatches||[]).slice().reverse();
    const batchHistory=`<div class="section"><div class="section-head"><h2>Importações bancárias</h2><div class="bank-header-actions"><button class="btn btn-ghost" id="btn-importar-extrato">Importar extrato CSV</button><input id="bank-csv-file" type="file" accept=".csv,text/csv" hidden></div></div><p class="history-note">Revise os lançamentos antes de salvar. Extratos em moeda diferente de BRL não são aceitos.</p>${batches.length?`<div class="bank-batches">${batches.map(batch=>`<div class="bank-batch"><span>${esc(batch.fileName||'Extrato CSV')} · ${esc(batch.createdAt?.slice(0,10)||'')} · ${batch.created.length} criado(s), ${batch.linked.length} vinculado(s) · ${batch.status==='undone'?'desfeito':'ativo'}</span>${batch.status==='active'?`<button class="btn btn-ghost" data-undo-bank-batch="${esc(batch.id)}">Desfazer lote</button>`:''}</div>`).join('')}</div>`:'<p class="history-note">Nenhuma importação bancária registrada.</p>'}</div>`;
    return `<div class="page-header"><div class="page-heading"><h1 class="page-title">Lançamentos</h1><p class="page-sub">Suas receitas e despesas, mês a mês</p></div></div><div class="section"><div class="section-head"><h2>${MESES[lancFiltro.mes-1]} de ${lancFiltro.ano}</h2><div class="page-actions"><button class="btn btn-ghost" id="btn-nova-transferencia">Transferir entre contas</button><button class="btn btn-ghost" id="btn-novo-investimento">Novo investimento</button><button class="btn btn-primary" id="btn-novo-lancamento">Novo lançamento</button></div></div><div class="filters"><select id="filtro-mes" aria-label="Filtrar por mês">${MESES.map((m,i)=>`<option value="${i+1}" ${i+1===lancFiltro.mes?'selected':''}>${m}</option>`).join('')}</select><select id="filtro-ano" aria-label="Filtrar por ano">${anosDisponiveis().map(a=>`<option value="${a}" ${a===lancFiltro.ano?'selected':''}>${a}</option>`).join('')}</select><select id="filtro-categoria" aria-label="Filtrar por categoria"><option value="todas">Todas as categorias</option>${state.categorias.map(c=>`<option value="${c.id}" ${lancFiltro.categoriaId===c.id?'selected':''}>${esc(c.nome)}</option>`).join('')}</select><input type="text" id="filtro-busca" aria-label="Buscar por descrição" placeholder="Buscar por descrição..." value="${esc(lancFiltro.busca||'')}"></div><div class="summary-strip"><span>${items.length} lançamento(s)</span><span>Resultado filtrado: <strong>${formatMoney(total)}</strong></span></div>${content}</div>${batchHistory}`;
  };
  window.FinTrackViews.register('lancamentos',()=>window.renderLancamentosView());
})();
