(function(){
  window.renderPlanejamentoView=function(){
    const key=planejamentoMes,p=state.planejamentos[key]||{receita:0,investimento:0,orcamentos:{}},[ano,mes]=key.split('-').map(Number),summary=resumoFinanceiroDoMes(mes,ano),fechado=mesFechado(`${key}-01`),entries=lancamentosDoMes(mes,ano),categories=state.categorias.filter(c=>c.tipo==='Saída'&&c.natureza!=='movimentacao');
    const statusLabels={normal:'Normal',acompanhamento:'Acompanhamento',atencao:'Atenção',ultrapassado:'Ultrapassado'};
    const rows=categories.map(category=>{const summary=resumoOrcamento(category.id,mes,ano,p.orcamentos[category.id]??category.orcado??0);return {category,budget:summary.planejado,realized:summary.realizado,pending:summary.pendente,committed:summary.comprometido,available:summary.disponivel,percentage:summary.percentualComprometido,status:statusLabels[summary.status]};});
    const plannedExpenses=rows.reduce((sum,item)=>sum+item.budget,0),free=Number(p.receita||0)-plannedExpenses-Number(p.investimento||0);
    const assumptions=`<div class="section"><div class="section-head"><h2>Premissas do mês</h2></div><div class="planning-fields"><div class="form-row"><div class="field"><label for="pl-receita">Receita prevista</label><input id="pl-receita" type="number" min="0" step="0.01" value="${fromCents(p.receita)}" ${fechado?'disabled':''}></div><div class="field"><label for="pl-investimento">Investimento planejado</label><input id="pl-investimento" type="number" min="0" step="0.01" value="${fromCents(p.investimento)}" ${fechado?'disabled':''}></div></div><h3>Orçamento por categoria</h3>${categories.map(category=>`<div class="field"><label for="pl-cat-${category.id}">${esc(category.nome)}</label><input id="pl-cat-${category.id}" type="number" min="0" step="0.01" value="${fromCents(p.orcamentos[category.id]??category.orcado??0)}" ${fechado?'disabled':''}></div>`).join('')}</div></div>`;
    const budget=`<div class="section budget-section"><div class="section-head"><h2>Orçamento operacional</h2><span class="stat-meta">Realizado e pendente</span></div><table><thead><tr><th>Categoria</th><th class="num">Orçado</th><th class="num">Realizado</th><th class="num">Pendente</th><th class="num">Disponível</th><th class="num">Uso</th><th>Estado</th></tr></thead><tbody>${rows.map(item=>`<tr><td>${esc(item.category.nome)}</td><td class="num">${formatMoney(item.budget)}</td><td class="num">${formatMoney(item.realized)}</td><td class="num">${formatMoney(item.pending)}</td><td class="num ${item.available<0?'money-out':''}">${formatMoney(item.available)}</td><td class="num">${item.percentage}%</td><td><span class="badge ${item.status==='Normal'?'badge-paid':'badge-pending'}">${item.status}</span></td></tr>`).join('')}</tbody></table></div>`;
    const comparison=`<div class="section"><div class="section-head"><h2>Planejado × realizado</h2></div><table><thead><tr><th>Indicador</th><th class="num">Planejado</th><th class="num">Realizado</th><th class="num">Pendente</th></tr></thead><tbody><tr><td>Receitas</td><td class="num">${formatMoney(p.receita)}</td><td class="num money-in">${formatMoney(summary.receitasRealizadas)}</td><td class="num">${formatMoney(summary.receitasPendentes)}</td></tr><tr><td>Despesas</td><td class="num">${formatMoney(plannedExpenses)}</td><td class="num money-out">${formatMoney(summary.despesasRealizadas)}</td><td class="num">${formatMoney(summary.despesasPendentes)}</td></tr><tr><td>Investimentos</td><td class="num">${formatMoney(p.investimento)}</td><td class="num">${formatMoney(summary.investimentosRealizados)}</td><td class="num">${formatMoney(summary.investimentosPendentes)}</td></tr></tbody></table></div>`;
    const annual=(state.despesasAnuais||[]).map(item=>({...item,...PlanningService.annualReserve(item,key)}));
    const monthOptions=Array.from({length:25},(_,i)=>addMonths(`${mesAtualKey()}-01`,i-12).slice(0,7)).map(value=>`<option value="${value}" ${value===key?'selected':''}>${value}</option>`).join('');
    return `<div class="page-header"><div class="page-heading"><h1 class="page-title">Planejamento mensal</h1><p class="page-sub">Planeje e acompanhe ${MESES[mes-1]} de ${ano}</p></div><div class="page-actions"><label for="planejamento-mes">Mês</label><select id="planejamento-mes">${monthOptions}</select><button class="btn btn-ghost" id="btn-copiar-planejamento">Copiar mês anterior</button><button class="btn btn-primary" id="btn-salvar-planejamento" ${fechado?'disabled':''}>Salvar planejamento</button><button class="btn btn-ghost" id="${fechado?'btn-reabrir-mes':'btn-fechar-mes'}">${fechado?'Reabrir mês':'Fechar mês'}</button></div></div>${fechado?`<div class="section"><div class="section-head"><h2>Snapshot do fechamento</h2><span class="badge badge-paid">Fechado</span></div><div class="history-note">Resultado: <strong>${formatMoney(state.fechamentos[key].snapshot.resultado)}</strong>. Consulte os detalhes em Histórico.</div></div>`:''}<div class="cards-row"><div class="stat-card"><div class="stat-label">Receita prevista</div><div class="stat-value income">${formatMoney(p.receita)}</div></div><div class="stat-card"><div class="stat-label">Despesas planejadas</div><div class="stat-value expense">${formatMoney(plannedExpenses)}</div></div><div class="stat-card"><div class="stat-label">Investimento planejado</div><div class="stat-value">${formatMoney(p.investimento)}</div></div><div class="stat-card"><div class="stat-label">Valor livre</div><div class="stat-value ${free<0?'money-out':''}">${formatMoney(free)}</div></div></div>${assumptions}<div class="section"><div class="section-head"><h2>Despesas anuais</h2><button class="btn btn-ghost" id="btn-nova-despesa-anual">Nova despesa anual</button></div>${annual.length?`<table><thead><tr><th>Despesa</th><th>Mês</th><th class="num">Estimativa</th><th class="num">Meses restantes</th><th class="num">Reserva sugerida</th></tr></thead><tbody>${annual.map(item=>`<tr><td>${esc(item.nome)}</td><td>${item.mes}</td><td class="num">${formatMoney(item.valorEstimado)}</td><td class="num">${item.mesesRestantes}</td><td class="num">${formatMoney(item.reservaMensalSugerida)}</td></tr>`).join('')}</tbody></table>`:emptyState('Nenhuma despesa anual','Cadastre impostos, seguros e outros compromissos anuais.')}</div>${budget}${comparison}`;
  };
  const basePlanejamento=window.renderPlanejamentoView;window.renderPlanejamentoView=function(){const rows=ChartDataService.planning(state,planejamentoMes).slice(0,8),chart=FinTrackCharts.groupedBars({title:'Orçado, realizado e pendente',question:'Onde o planejamento está comprometido?',summary:'Série preparada pelo núcleo financeiro do planejamento.',data:rows,keys:[{value:'orcado',label:'Orçado'},{value:'realizado',label:'Realizado'},{value:'pendente',label:'Pendente'}]});return basePlanejamento().replace('<div class="section">',`<div class="dashboard-grid">${chart}</div><div class="section">`);};
  window.FinTrackViews.register('planejamento',()=>window.renderPlanejamentoView());
})();
