(function(){
  window.renderPlanejamentoView=function(){
    const key=mesAtualKey(),p=state.planejamentos[key]||{receita:0,investimento:0,orcamentos:{}},[ano,mes]=key.split('-').map(Number),summary=resumoFinanceiroDoMes(mes,ano),fechado=mesFechado(`${key}-01`),entries=lancamentosDoMes(mes,ano),categories=state.categorias.filter(c=>c.tipo==='Saída'&&c.natureza!=='movimentacao');
    const rows=categories.map(category=>{const budget=Number(p.orcamentos[category.id]??category.orcado??0),items=entries.filter(item=>item.categoriaId===category.id&&naturezaLancamento(item)==='despesa'),realized=items.filter(item=>item.status==='Pago').reduce((sum,item)=>sum+Number(item.valor),0),pending=items.filter(item=>item.status==='Pendente').reduce((sum,item)=>sum+Number(item.valor),0),percentage=budget?Math.round((realized+pending)/budget*100):0,status=percentage>=100?'Ultrapassado':percentage>=80?'Atenção':percentage>=70?'Acompanhamento':'Normal';return {category,budget,realized,pending,available:budget-realized-pending,percentage,status};});
    const plannedExpenses=rows.reduce((sum,item)=>sum+item.budget,0),free=Number(p.receita||0)-plannedExpenses-Number(p.investimento||0);
    const assumptions=`<div class="section"><div class="section-head"><h2>Premissas do mês</h2></div><div class="planning-fields"><div class="form-row"><div class="field"><label for="pl-receita">Receita prevista</label><input id="pl-receita" type="number" min="0" step="0.01" value="${fromCents(p.receita)}" ${fechado?'disabled':''}></div><div class="field"><label for="pl-investimento">Investimento planejado</label><input id="pl-investimento" type="number" min="0" step="0.01" value="${fromCents(p.investimento)}" ${fechado?'disabled':''}></div></div><h3>Orçamento por categoria</h3>${categories.map(category=>`<div class="field"><label for="pl-cat-${category.id}">${esc(category.nome)}</label><input id="pl-cat-${category.id}" type="number" min="0" step="0.01" value="${fromCents(p.orcamentos[category.id]??category.orcado??0)}" ${fechado?'disabled':''}></div>`).join('')}</div></div>`;
    const budget=`<div class="section budget-section"><div class="section-head"><h2>Orçamento operacional</h2><span class="stat-meta">Realizado e pendente</span></div><table><thead><tr><th>Categoria</th><th class="num">Orçado</th><th class="num">Realizado</th><th class="num">Pendente</th><th class="num">Disponível</th><th class="num">Uso</th><th>Estado</th></tr></thead><tbody>${rows.map(item=>`<tr><td>${esc(item.category.nome)}</td><td class="num">${formatMoney(item.budget)}</td><td class="num">${formatMoney(item.realized)}</td><td class="num">${formatMoney(item.pending)}</td><td class="num ${item.available<0?'money-out':''}">${formatMoney(item.available)}</td><td class="num">${item.percentage}%</td><td><span class="badge ${item.status==='Normal'?'badge-paid':'badge-pending'}">${item.status}</span></td></tr>`).join('')}</tbody></table></div>`;
    const comparison=`<div class="section"><div class="section-head"><h2>Planejado × realizado</h2></div><table><thead><tr><th>Indicador</th><th class="num">Planejado</th><th class="num">Realizado</th><th class="num">Pendente</th></tr></thead><tbody><tr><td>Receitas</td><td class="num">${formatMoney(p.receita)}</td><td class="num money-in">${formatMoney(summary.receitasRealizadas)}</td><td class="num">${formatMoney(summary.receitasPendentes)}</td></tr><tr><td>Despesas</td><td class="num">${formatMoney(plannedExpenses)}</td><td class="num money-out">${formatMoney(summary.despesasRealizadas)}</td><td class="num">${formatMoney(summary.despesasPendentes)}</td></tr><tr><td>Investimentos</td><td class="num">${formatMoney(p.investimento)}</td><td class="num">${formatMoney(summary.investimentosRealizados)}</td><td class="num">${formatMoney(summary.investimentosPendentes)}</td></tr></tbody></table></div>`;
    return `<div class="page-header"><div class="page-heading"><h1 class="page-title">Planejamento mensal</h1><p class="page-sub">Planeje e acompanhe ${MESES[mes-1]} de ${ano}</p></div><div class="page-actions"><button class="btn btn-primary" id="btn-salvar-planejamento" ${fechado?'disabled':''}>Salvar planejamento</button><button class="btn btn-ghost" id="${fechado?'btn-reabrir-mes':'btn-fechar-mes'}">${fechado?'Reabrir mês':'Fechar mês'}</button></div></div>${fechado?`<div class="section"><div class="section-head"><h2>Snapshot do fechamento</h2><span class="badge badge-paid">Fechado</span></div><div class="history-note">Resultado: <strong>${formatMoney(state.fechamentos[key].snapshot.resultado)}</strong>. Consulte os detalhes em Histórico.</div></div>`:''}<div class="cards-row"><div class="stat-card"><div class="stat-label">Receita prevista</div><div class="stat-value income">${formatMoney(p.receita)}</div></div><div class="stat-card"><div class="stat-label">Despesas planejadas</div><div class="stat-value expense">${formatMoney(plannedExpenses)}</div></div><div class="stat-card"><div class="stat-label">Investimento planejado</div><div class="stat-value">${formatMoney(p.investimento)}</div></div><div class="stat-card"><div class="stat-label">Valor livre</div><div class="stat-value ${free<0?'money-out':''}">${formatMoney(free)}</div></div></div>${assumptions}${budget}${comparison}`;
  };
  window.FinTrackViews.register('planejamento',()=>window.renderPlanejamentoView());
})();
