(function(){
  const flowBlock=(title,data)=>`<div class="projection-flow">${title?`<strong>${title}</strong>`:''}<span>Entradas ${formatMoney(data.entradas)}</span><span>Saídas ${formatMoney(data.saidas)}</span><span>Investimentos ${formatMoney(data.investimentos)}</span></div>`;
  const situation=row=>row.alerta==='saldo_negativo'?['Crítico','critico','Saldo negativo']:row.alerta?['Atenção','atencao','Margem reduzida']:['Normal','normal','Sem risco identificado'];
  const details=row=>`<details class="projection-details"><summary>Ver memória de cálculo</summary><div class="projection-detail-grid">${flowBlock('Confirmado',row.confirmado)}${flowBlock('Planejado',row.planejado)}<div><strong>Saldos</strong><span>Inicial ${formatMoney(row.saldoInicial)}</span><span>Mínimo ${formatMoney(row.projetado.menorSaldo)}</span><span>Final ${formatMoney(row.projetado.saldoFinal)}</span>${row.excessoOrcamento?`<span>Excesso ${formatMoney(row.excessoOrcamento)}</span>`:''}</div></div></details>`;
  window.renderProjecaoView=function(){
    const result=ProjectionService.project(state,mesAtualKey(),3),rows=result.meses;
    const final=rows.at(-1)?.projetado.saldoFinal||0,minimum=rows.length?Math.min(...rows.map(item=>item.projetado.menorSaldo)):0;
    const chart=FinTrackCharts.area({title:'Saldo projetado',question:'Como confirmado e planejado afetam o saldo?',summary:'Cenário consolidado sem duplicar compromissos já materializados.',data:rows.map(item=>({label:item.mes,value:item.projetado.saldoFinal}))}).replace('class="chart ','class="chart chart-daily ');
    const cards=`<div class="metric-grid cards-row">${MetricCard.render({label:'Saldo em três meses',value:formatMoney(final),tone:final<0?'negative':'neutral'})}${MetricCard.render({label:'Menor saldo',value:formatMoney(minimum),tone:minimum<0?'negative':'neutral'})}${MetricCard.render({label:'Referência diária',value:`${formatMoney(result.referenciaDiaria)}/dia`,detail:'Estimativa, não saldo garantido'})}</div>`;
    const table=`<div class="projection-table table-wrap"><table><thead><tr><th>Mês</th><th>Confirmado</th><th>Planejado</th><th class="num">Saldo projetado</th><th>Situação</th></tr></thead><tbody>${rows.map(row=>{const status=situation(row);return `<tr><td><strong>${row.mes}</strong>${details(row)}</td><td>${flowBlock('',row.confirmado)}</td><td>${flowBlock('',row.planejado)}</td><td class="num money-nowrap ${row.projetado.saldoFinal<0?'money-out':''}">${formatMoney(row.projetado.saldoFinal)}</td><td><span class="badge state-${status[1]}">${status[0]}</span><strong>${status[2]}</strong>${row.principalImpacto?`<small>Principal causa: ${esc(row.principalImpacto)}</small>`:''}</td></tr>`;}).join('')}</tbody></table></div>`;
    const mobile=`<div class="projection-cards">${rows.map(row=>{const status=situation(row);return `<article class="section state-${status[1]}"><header><strong>${row.mes}</strong><span class="badge">${status[0]}</span></header><p class="money-nowrap ${row.projetado.saldoFinal<0?'money-out':''}">${formatMoney(row.projetado.saldoFinal)}</p>${details(row)}</article>`;}).join('')}</div>`;
    const quality=AnalysisService.dataQuality(state,{startMonth:mesAtualKey(),months:3});
    const qualityPanel=DataPanel.render({title:'Qualidade da projeção',question:'Quanto posso confiar nesta previsão?',state:quality.status,summary:`${quality.score}/100`,content:`<div class="metric-grid">${quality.metrics.map(item=>MetricCard.render({label:item.month,value:`${item.score}%`,tone:item.score<60?'negative':'neutral',detail:item.estimated?'Inclui estimativas':'Base conhecida'})).join('')}</div><details><summary>Por que não é 100?</summary><p>Obrigações ${quality.evidence.dimensions.coverage}/35 · receita ${quality.evidence.dimensions.income}/25 · completude ${quality.evidence.dimensions.completeness}/20 · histórico ${quality.evidence.dimensions.history}/10 · atualização ${quality.evidence.dimensions.updates}/10.</p></details>`});
    return `<div class="page-header"><div class="page-heading"><h1 class="page-title">Projeção financeira</h1><p class="page-sub">Confirmado, planejado e projetado nos próximos três meses</p></div><button class="btn btn-ghost" id="btn-cenario-projecao">Simular cenário</button></div>${cards}<div class="dashboard-grid">${chart}</div><section class="section"><div class="section-head"><h2>Fluxo projetado</h2><span class="stat-meta">Não altera dados reais</span></div>${table}${mobile}</section><details class="projection-warning"><summary>Sobre a referência diária</summary><p>${esc(result.aviso)}</p></details>${qualityPanel}`;
  };
  FinTrackViews.register('projecao',()=>window.renderProjecaoView());
})();
