(function(){
  'use strict';
  const analysis=window.FinTrackAnalysisInternals,{num,sum,base,closedSnapshots}=analysis;
  analysis.monthAnomaly=function(data,options={}){
    const period=options.month||new Date().toISOString().slice(0,7),closing=data.fechamentos?.[period],today=options.today||new Date().toISOString().slice(0,10),partial=!closing?.snapshot,day=partial&&today.startsWith(period)?Number(today.slice(8)):31,history=closedSnapshots(data).filter(([key,value])=>key<period&&Array.isArray(value.snapshot.lancamentosDetalhados)).slice(-6);
    if(history.length<3)return base('anomalia',period,{status:'indisponivel',summary:'São necessários ao menos três meses comparáveis.',evidence:{historyMonths:history.length,partial}});
    const valid=item=>item.tipo==='Despesa'&&!['transferencia','investimento','pagamento_cartao','pagamento_divida'].includes(item.tipoOperacao),currentRows=closing?.snapshot?.lancamentosDetalhados||(data.lancamentos||[]).filter(item=>item.status==='Pago'&&item.data?.startsWith(period)),observed=currentRows.filter(valid).filter(item=>!partial||Number(item.data?.slice(8)||31)<=day),total=sum(observed,'valor'),extraordinary=sum(observed.filter(item=>item.extraordinario),'valor'),without=total-extraordinary,historical=history.map(([,value])=>sum(value.snapshot.lancamentosDetalhados.filter(valid).filter(item=>!partial||Number(item.data?.slice(8)||31)<=day).filter(item=>!item.extraordinario),'valor')),average=Math.round(sum(historical,item=>item)/historical.length),difference=without-average,variation=average?Math.round(difference/average*1000)/10:0,incomeAverage=Math.round(sum(history,item=>item[1].snapshot.receitas)/history.length),relevant=Math.abs(difference)>=incomeAverage*.05,status=relevant&&variation>=35?'critico':relevant&&variation>=20?'atencao':'normal',confidence=Math.min(95,65+(history.length-3)*10);
    return base('anomalia',period,{status,confidence,summary:`${partial?'Mês parcial: ':''}despesas sem extraordinários ${variation>=0?'+':''}${variation}% ante a média comparável.`,metrics:[{key:'despesasComExtraordinarios',value:total},{key:'despesasSemExtraordinarios',value:without},{key:'mediaComparavel',value:average},{key:'diferencaSemExtraordinarios',value:difference},{key:'variacaoSemExtraordinarios',value:variation},{key:'extraordinarios',value:extraordinary}],evidence:{historyMonths:history.map(([key])=>key),partial,comparedThroughDay:partial?day:null,extraordinary}});
  };
})();
