(function(){
  'use strict';
  const analysis=window.FinTrackAnalysisInternals,{num,sum,base,closedSnapshots}=analysis;
  analysis.futureCommitment=function(data,options={}){
    const startMonth=options.startMonth||new Date().toISOString().slice(0,7),count=Math.max(1,Math.min(12,num(options.months)||3)),history=closedSnapshots(data).slice(-6),avgIncome=history.length?Math.round(sum(history,entry=>entry[1].snapshot.receitas)/history.length):0,avgExpenses=history.length?Math.round(sum(history,entry=>entry[1].snapshot.despesas)/history.length):0,projection=window.ProjectionService.project(data,startMonth,count);
    const months=projection.meses.map(row=>{const planning=data.planejamentos?.[row.mes]||{},knownIncome=num(planning.receita),expectedIncome=knownIncome||avgIncome,confirmed=num(row.confirmado.saidas),planned=num(row.planejado.saidas),estimated=planning.orcamentos&&Object.keys(planning.orcamentos).length?0:Math.max(0,avgExpenses-confirmed),plannedInvestment=num(row.planejado.investimentos),total=confirmed+planned+estimated+plannedInvestment,rate=expectedIncome?Math.round(total/expectedIncome*1000)/10:null,impacts=[['Compromissos confirmados',confirmed],['Planejamento',planned],['Estimativa histórica',estimated],['Investimentos',plannedInvestment]].sort((a,b)=>b[1]-a[1]);return {month:row.mes,expectedIncome,confirmed,planned,estimated,plannedInvestment,commitmentRate:rate,freeIncome:expectedIncome-total,principalImpact:impacts[0][1]?{label:impacts[0][0],value:impacts[0][1]}:null,sources:{income:knownIncome?'planejamento':avgIncome?'historico':'indisponivel',historyMonths:history.length}};});
    const worst=months.filter(item=>item.commitmentRate!==null).sort((a,b)=>b.commitmentRate-a.commitmentRate)[0];
    return base('comprometimento',startMonth,{status:worst?.commitmentRate>100?'critico':worst?.commitmentRate>=80?'atencao':'normal',summary:worst?`${worst.month}: ${worst.commitmentRate}% da renda comprometida.`:'Renda futura indisponível.',metrics:months,evidence:{historyMonths:history.map(([key])=>key)},actions:worst?.commitmentRate>=80?[{id:'review-planning',label:'Revisar planejamento',target:'planejamento'}]:[]});
  };
})();
