(function(){
  'use strict';
  const num=value=>Number(value||0),sum=(items,field)=>items.reduce((total,item)=>total+num(typeof field==='function'?field(item):item[field]),0),clone=value=>JSON.parse(JSON.stringify(value));
  const monthShift=(key,offset)=>{const [y,m]=key.split('-').map(Number),d=new Date(y,m-1+offset,1);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`;};
  const base=(type,period,values={})=>({type,period,status:'normal',score:null,confidence:null,summary:'',metrics:[],evidence:{},actions:[],...values});
  const normalize=value=>String(value||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/\d+/g,'#').replace(/[^a-z#]+/g,' ').trim().replace(/\s+/g,' ');
  const median=values=>{const list=[...values].sort((a,b)=>a-b),middle=Math.floor(list.length/2);return list.length%2?list[middle]:Math.round((list[middle-1]+list[middle])/2);};
  const validExpense=item=>item.tipo==='Despesa'&&item.status==='Pago'&&!item.extraordinario&&!['transferencia','investimento','pagamento_cartao','pagamento_divida'].includes(item.tipoOperacao);
  function recurringExpenses(data,options={}){
    const end=options.today||new Date().toISOString().slice(0,10),start=new Date(`${end}T12:00:00`);start.setMonth(start.getMonth()-12);const decisions=new Map((data.recurrenceDecisions||[]).map(item=>[item.fingerprint,item])),groups=new Map();
    (data.lancamentos||[]).filter(validExpense).filter(item=>item.data>=start.toISOString().slice(0,10)&&item.data<=end).forEach(item=>{const key=`${normalize(item.descricao)}|${item.categoriaId||''}|${item.contaId||''}`,list=groups.get(key)||[];list.push(item);groups.set(key,list);});
    const detected=[];groups.forEach((items,fingerprint)=>{items.sort((a,b)=>a.data.localeCompare(b.data));if(items.length<3||decisions.get(fingerprint)?.status==='ignorada')return;const gaps=items.slice(1).map((item,index)=>(new Date(item.data)-new Date(items[index].data))/86400000),values=items.map(item=>num(item.valor)),mid=median(values);if(gaps.every(gap=>gap>=25&&gap<=35)&&values.every(value=>Math.abs(value-mid)<=mid*.1))detected.push({fingerprint,descricao:items.at(-1).descricao,categoriaId:items[0].categoriaId,contaId:items[0].contaId,mensal:mid,anual:mid*12,sourceIds:items.map(item=>item.id),ocorrencias:items.length,status:decisions.get(fingerprint)?.status||'detectada'});});
    const registered=[...new Map((data.lancamentos||[]).filter(item=>item.serieId&&item.serieTipo==='recorrencia').map(item=>[item.serieId,item])).values()].map(item=>({serieId:item.serieId,descricao:item.descricao,mensal:num(item.valor),anual:num(item.valor)*12,status:item.serieStatus==='ativa'?'confirmada':'encerrada'}));
    const monthly=sum(registered.filter(item=>item.status==='confirmada'),'mensal');return base('recorrencias',end.slice(0,7),{status:detected.length?'atencao':'normal',summary:`${registered.length} recorrência(s) cadastrada(s) e ${detected.length} possível(is).`,metrics:[{key:'mensal',value:monthly},{key:'anual',value:monthly*12}],evidence:{registered,detected,heuristic:'3 ocorrências, intervalo de 25–35 dias e variação máxima de 10%'},actions:detected.length?[{id:'review-recurring',label:'Revisar recorrentes',target:'planejamento'}]:[]});
  }
  const closedSnapshots=data=>Object.entries(data.fechamentos||{}).filter(([,item])=>item.status==='fechado'&&item.snapshot).sort(([a],[b])=>a.localeCompare(b));
  function futureCommitment(data,options={}){
    const startMonth=options.startMonth||new Date().toISOString().slice(0,7),count=Math.max(1,Math.min(12,num(options.months)||3)),history=closedSnapshots(data).slice(-6),avgIncome=history.length?Math.round(sum(history,entry=>entry[1].snapshot.receitas)/history.length):0,avgExpenses=history.length?Math.round(sum(history,entry=>entry[1].snapshot.despesas)/history.length):0,projection=window.ProjectionService.project(data,startMonth,count),months=projection.meses.map(row=>{const planning=data.planejamentos?.[row.mes]||{},knownIncome=num(planning.receita),expectedIncome=knownIncome||avgIncome,confirmed=num(row.confirmado.saidas),planned=num(row.planejado.saidas),estimated=planning.orcamentos&&Object.keys(planning.orcamentos).length?0:Math.max(0,avgExpenses-confirmed),plannedInvestment=num(row.planejado.investimentos),total=confirmed+planned+estimated+plannedInvestment,rate=expectedIncome?Math.round(total/expectedIncome*1000)/10:null,impacts=[['Compromissos confirmados',confirmed],['Planejamento',planned],['Estimativa histórica',estimated],['Investimentos',plannedInvestment]].sort((a,b)=>b[1]-a[1]);return {month:row.mes,expectedIncome,confirmed,planned,estimated,plannedInvestment,commitmentRate:rate,freeIncome:expectedIncome-total,principalImpact:impacts[0][1]?{label:impacts[0][0],value:impacts[0][1]}:null,sources:{income:knownIncome?'planejamento':avgIncome?'historico':'indisponivel',historyMonths:history.length}};}),worst=months.filter(item=>item.commitmentRate!==null).sort((a,b)=>b.commitmentRate-a.commitmentRate)[0];return base('comprometimento',startMonth,{status:worst?.commitmentRate>100?'critico':worst?.commitmentRate>=80?'atencao':'normal',summary:worst?`${worst.month}: ${worst.commitmentRate}% da renda comprometida.`:'Renda futura indisponível.',metrics:months,evidence:{historyMonths:history.map(([key])=>key)},actions:worst?.commitmentRate>=80?[{id:'review-planning',label:'Revisar planejamento',target:'planejamento'}]:[]});
  }
  function emergencyReserve(data,options={}){
    const target=[3,6,9,12].includes(num(options.targetMonths))?num(options.targetMonths):num(data.configuracoesFinanceiras?.reservaMeses)||6,categories=new Set((data.categorias||[]).filter(item=>item.essencial).map(item=>item.id)),history=closedSnapshots(data).slice(-6),monthly=history.map(([,closing])=>sum(closing.snapshot.lancamentosDetalhados||[],item=>item.tipo==='Despesa'&&categories.has(item.categoriaId)?item.valor:0)).filter(Boolean),average=monthly.length?Math.round(sum(monthly,item=>item)/monthly.length):0,at=options.atDate||new Date().toISOString().slice(0,10),accounts=(data.contas||[]).filter(item=>item.reservaEmergencia),assets=(data.ativosInvestimento||[]).filter(item=>item.reservaEmergencia),available=sum(accounts,item=>window.FinTrackCore.accountBalance(data,item,at))+sum(assets,'valorAtual'),coverage=average?Math.round(available/average*10)/10:null,needed=average*target,missing=Math.max(0,needed-available),operations=new Map((data.operacoes||[]).map(item=>[item.id,item])),contributions=(data.lancamentos||[]).filter(item=>item.aporteReservaEmergencia&&item.tipoOperacao==='investimento'&&item.status==='Pago'&&item.data>=monthShift(at.slice(0,7),-5)+'-01'&&item.data<=at&&operations.get(item.operacaoId)?.status!=='estornada'),aporteTotal=sum(contributions,item=>item.movimentoInvestimento==='resgate'?0:item.valor),resgateTotal=sum(contributions,item=>item.movimentoInvestimento==='resgate'?item.valor:0),contributionAverage=Math.round((aporteTotal-resgateTotal)/6),monthsToTarget=contributionAverage>0&&missing?Math.ceil(missing/contributionAverage):null;return base('reserva',at.slice(0,7),{status:!average?'indisponivel':coverage<target/2?'critico':coverage<target?'atencao':'normal',confidence:monthly.length>=6?90:monthly.length>=3?60:20,summary:average?`Cobertura de ${coverage} mês(es), meta de ${target}.`:'Marque categorias essenciais e feche ao menos três meses.',metrics:[{key:'disponivel',value:available},{key:'mediaEssencial',value:average},{key:'cobertura',value:coverage},{key:'necessario',value:needed},{key:'faltante',value:missing},{key:'mesesParaMeta',value:monthsToTarget}],evidence:{historyMonths:monthly.length,accountIds:accounts.map(item=>item.id),assetIds:assets.map(item=>item.id),contributionIds:contributions.map(item=>item.id),aporteTotal,resgateTotal,contributionAverage},actions:[{id:'configure-reserve',label:'Configurar reserva',target:'patrimonio'}]});
  }
  function dataQuality(data,options={}){const startMonth=options.startMonth||new Date().toISOString().slice(0,7),months=Math.max(1,num(options.months)||3),commitment=futureCommitment(data,{startMonth,months}),invalid=(data.lancamentos||[]).filter(item=>!item.contaId||!item.categoriaId).length,history=closedSnapshots(data).length,recentAssets=(data.ativosInvestimento||[]).filter(item=>item.atualizadoEm&&Date.now()-new Date(item.atualizadoEm).getTime()<93*86400000).length,coverage=commitment.metrics.filter(item=>item.confirmed>0).length/months,income=commitment.metrics.filter(item=>item.sources.income==='planejamento').length/months,completeness=(data.lancamentos||[]).length?1-invalid/data.lancamentos.length:0,updates=(data.ativosInvestimento||[]).length?recentAssets/data.ativosInvestimento.length:1,dimensions={coverage:Math.round(35*coverage),income:Math.round(25*income),completeness:Math.round(20*Math.max(0,completeness)),history:Math.round(10*Math.min(1,history/6)),updates:Math.round(10*updates)},score=sum(Object.values(dimensions),item=>item),monthly=commitment.metrics.map((item,index)=>({month:item.month,score:Math.max(0,Math.round(score-index*5-(item.estimated>0?15:0))),estimated:item.estimated}));return base('qualidade',startMonth,{status:score>=80?'normal':score>=60?'atencao':'critico',score,confidence:score,summary:`Qualidade da projeção: ${score}/100.`,metrics:monthly,evidence:{dimensions,invalidLinks:invalid},actions:score<80?[{id:'improve-data',label:'Melhorar dados',target:'planejamento'}]:[]});}
  function dataQualityWithKnownIncome(data,options={}){const result=dataQuality(data,options),sources=result.metrics.map(metric=>{if(num(data.planejamentos?.[metric.month]?.receita)>0)return {month:metric.month,source:'planejamento'};const known=(data.lancamentos||[]).some(item=>item.tipo==='Receita'&&item.status==='Pendente'&&item.data?.startsWith(metric.month));return {month:metric.month,source:known?'receita_materializada':'historico_estimado'};}),income=Math.round(25*sources.filter(item=>item.source!=='historico_estimado').length/Math.max(1,sources.length)),score=result.score-result.evidence.dimensions.income+income,delta=score-result.score,metrics=result.metrics.map(item=>({...item,score:Math.max(0,Math.min(100,item.score+delta)),incomeSource:sources.find(source=>source.month===item.month)?.source})),dimensions={...result.evidence.dimensions,income},losses=Object.entries({coverage:35,income:25,completeness:20,history:10,updates:10}).filter(([key,max])=>dimensions[key]<max).map(([key,max])=>({dimension:key,lost:max-dimensions[key]}));return {...result,status:score>=80?'normal':score>=60?'atencao':'critico',score,confidence:score,summary:`Qualidade da projeção: ${score}/100.`,metrics,evidence:{...result.evidence,dimensions,incomeSources:sources,losses}};}
  function monthAnomaly(data,options={}){const period=options.month||new Date().toISOString().slice(0,7),history=closedSnapshots(data).filter(([key])=>key<period).slice(-6);if(history.length<3)return base('anomalia',period,{status:'indisponivel',summary:'São necessários ao menos três meses fechados.',evidence:{historyMonths:history.length}});const current=data.fechamentos?.[period]?.snapshot||window.FinTrackCore.totals(data,Number(period.slice(5)),Number(period.slice(0,4))),average=Math.round(sum(history,item=>item[1].snapshot.despesas)/history.length),difference=num(current.despesas)-average,variation=average?Math.round(difference/average*1000)/10:0,incomeAverage=Math.round(sum(history,item=>item[1].snapshot.receitas)/history.length),relevant=Math.abs(difference)>=incomeAverage*.05,status=relevant&&variation>=35?'critico':relevant&&variation>=20?'atencao':'normal';return base('anomalia',period,{status,summary:`Despesas ${variation>=0?'':'-'}${Math.abs(variation)}% em relação à média.`,metrics:[{key:'despesas',value:num(current.despesas)},{key:'media',value:average},{key:'diferenca',value:difference}],evidence:{historyMonths:history.map(([key])=>key),partial:!data.fechamentos?.[period],extraordinary:sum((data.lancamentos||[]).filter(item=>item.extraordinario&&item.data.startsWith(period)),'valor')}});}
  function monthAnomalyWithConfidence(data,options={}){const result=monthAnomaly(data,options),count=Array.isArray(result.evidence.historyMonths)?result.evidence.historyMonths.length:Number(result.evidence.historyMonths||0);return {...result,confidence:result.status==='indisponivel'?null:Math.min(95,65+Math.max(0,count-3)*10)};}
  function expenseConcentration(data,options={}){const period=options.month||new Date().toISOString().slice(0,7),[year,month]=period.split('-').map(Number),rows=(data.categorias||[]).filter(item=>item.tipo==='Saída'&&item.natureza!=='movimentacao').map(item=>({id:item.id,label:item.nome,value:window.FinTrackCore.categorySpend(data,item.id,month,year,'Pago')})).filter(item=>item.value>0).sort((a,b)=>b.value-a.value),total=sum(rows,'value');if(!total)return base('concentracao',period,{status:'indisponivel',summary:'Não há despesas realizadas no período.'});const top3=sum(rows.slice(0,3),'value')/total*100,top5=sum(rows.slice(0,5),'value')/total*100,status=top3>70?'critico':top3>=50?'atencao':'normal';return base('concentracao',period,{status,summary:`As três maiores categorias representam ${Math.round(top3)}% das despesas.`,metrics:[{key:'top3',value:Math.round(top3*10)/10},{key:'top5',value:Math.round(top5*10)/10},{key:'total',value:total}],evidence:{categories:rows.slice(0,5),other:sum(rows.slice(5),'value'),heuristic:'Top 3: baixa <50%, moderada 50–70%, alta >70%'}});}
  window.AnalysisService={recurringExpenses,futureCommitment,emergencyReserve,dataQuality:dataQualityWithKnownIncome,monthAnomaly:monthAnomalyWithConfidence,expenseConcentration};
})();
