(function(){
  'use strict';
  const targets={orcamento:'planejamento',projecao:'projecao',comprometimento:'planejamento',qualidade:'projecao',reserva:'patrimonio',anomalia:'analises',concentracao:'analises',atrasos:'agenda',dividas:'dividas',metas:'metas',investimentos:'lancamentos',tendencia:'balanco'};
  const effects={orcamento:'Ajuda a recuperar o ritmo do orçamento.',projecao:'Reduz a chance de saldo negativo ou margem insuficiente.',comprometimento:'Protege a renda futura antes de novos compromissos.',qualidade:'Torna a projeção mais confiável para decisões.',reserva:'Aumenta a proteção contra imprevistos.',anomalia:'Separa mudanças de comportamento de eventos extraordinários.',concentracao:'Mostra onde uma revisão terá maior alcance.',atrasos:'Atualiza o caixa e evita que vencimentos distorçam a projeção.',dividas:'Direciona recursos para a obrigação de maior custo.',metas:'Reaproxima a contribuição do prazo definido.',investimentos:'Transforma parte da renda em patrimônio.',tendencia:'Identifica quais categorias explicam a mudança.'};
  const sectionFor=type=>['atrasos','orcamento','projecao'].includes(type)?'Agora':['tendencia','anomalia'].includes(type)?'O que mudou':['concentracao','dividas','reserva'].includes(type)?'Estrutura':['comprometimento','qualidade','metas'].includes(type)?'Futuro':'Oportunidade';
  function evaluate(data,options={}){
    const today=options.today||new Date().toISOString().slice(0,10),limit=Math.max(1,Math.min(3,Number(options.limit)||3)),health=window.HealthService.evaluate(data,{today}),insights=window.InsightService.detect(data,{today,limit:20}),seen=new Set(),actions=[];
    for(const item of insights){const target=targets[item.tipo]||'home',key=`${target}|${item.acao}`;if(!item.acao||seen.has(key))continue;seen.add(key);actions.push({id:`${item.tipo}:${item.periodo}`,rank:actions.length+1,title:item.acao,reason:item.mensagem,effect:effects[item.tipo]||'Ajuda a manter os dados e decisões financeiras atualizados.',target,relevance:item.relevancia,dataQuality:item.qualidadeDados,severity:item.severidade,sourceType:item.tipo});if(actions.length===limit)break;}
    if(!actions.length)actions.push({id:'maintenance',rank:1,title:'Manter os lançamentos atualizados',reason:'Nenhum risco relevante foi identificado neste momento.',effect:'Preserva a qualidade das próximas análises.',target:'lancamentos',relevance:50,dataQuality:100,severity:'baixa',sourceType:'manutencao'});
    const narrative=['Agora','O que mudou','Estrutura','Futuro','Oportunidade'].map(section=>({section,items:insights.filter(item=>sectionFor(item.tipo)===section).slice(0,2)})).filter(group=>group.items.length);
    return {period:today.slice(0,7),health,primary:insights[0]||null,insights,actions,narrative,summary:insights[0]?.mensagem||'Nenhum sinal financeiro relevante foi identificado.',limitation:'Decisões determinísticas baseadas apenas nos dados locais cadastrados.'};
  }
  window.DecisionService={evaluate};
})();
