(function(){
  'use strict';
  const rank={critica:4,alta:3,media:2,baixa:1};
  const insight=(tipo,severidade,titulo,mensagem,evidencia,acao,categoria)=>({tipo,severidade,titulo,mensagem,evidencia,acao,categoria});
  const linkedQualityFor=data=>{const operational=(data.lancamentos||[]).filter(entry=>!['transferencia','pagamento_cartao','pagamento_divida'].includes(entry.tipoOperacao));return operational.length?Math.round(operational.filter(entry=>entry.contaId&&entry.categoriaId).length/operational.length*100):100;};
  const evidenceQualityFor=(item,analyses,data)=>{const linkedQuality=analyses.linkedQuality;if(['orcamento','atrasos','dividas','investimentos','concentracao'].includes(item.tipo))return linkedQuality;if(item.tipo==='tendencia')return Math.min(90,linkedQuality);if(item.tipo==='reserva')return analyses.reserve.confidence;if(item.tipo==='anomalia')return analyses.anomaly.confidence;if(['projecao','comprometimento','qualidade'].includes(item.tipo)){const period=item.evidencia?.periodo,month=analyses.quality.metrics.find(metric=>metric.month===period);return month?.score??analyses.quality.score;}if(item.tipo==='metas'){const goal=(data.metas||[]).find(candidate=>candidate.id===item.evidencia?.metaId);return Number(goal?.saldoInicial||0)>0?70:90;}return Math.min(80,linkedQuality);};
  const calculationReliabilityFor=item=>({anomalia:85,tendencia:90,metas:90,reserva:95,qualidade:95}[item.tipo]||100);
  const financialValueFor=item=>{const evidence=item.evidencia||{},reserveMissing=(evidence.metricas||[]).find(metric=>metric.key==='faltante')?.value;return Math.abs(Number(evidence.total??evidence.saldo??evidence.comprometido??evidence.menorSaldo??reserveMissing??0));};
  function relevanceFor(item,monthlyIncome){const severity={critica:100,alta:80,media:55,baixa:30}[item.severidade]||20,urgency={projecao:100,atrasos:100,comprometimento:85,orcamento:80,reserva:65,dividas:65,qualidade:60,anomalia:55,metas:50,concentracao:45,tendencia:40,investimentos:30}[item.tipo]||40,financial=monthlyIncome?Math.min(100,Math.round(item.valor/monthlyIncome*100)):0,impact=Math.max(severity,financial),quality=Number(item.qualidadeDados||0),actionability=item.acao?100:40,score=Math.round(urgency*.35+impact*.35+quality*.2+actionability*.1);return {score,factors:{urgency,impact,dataQuality:quality,actionability},formula:'urgência 35% + impacto 35% + qualidade dos dados 20% + capacidade de ação 10%'};}
  function provenanceFor(item,analyses){const evidence=item.evidencia||{},period=evidence.periodo||item.periodo;
    if(item.tipo==='orcamento')return [`Orçamento de ${period}`,`Valor planejado e comprometido da categoria`,`Lançamentos vinculados até o período`];
    if(item.tipo==='atrasos')return [`${evidence.quantidade||0} compromisso(s) com vencimento passado`,`Valor total pendente cadastrado`,`Status informado nos lançamentos locais`];
    if(item.tipo==='dividas')return [`${evidence.quantidade||0} dívida(s) ativa(s)`,`Saldos devedores informados nos cadastros`];
    if(item.tipo==='investimentos')return [`Receitas realizadas em ${period}`,`Aportes pagos identificados no mesmo período`];
    if(item.tipo==='tendencia')return ['Despesas realizadas do mês atual','Despesas realizadas do mês anterior'];
    if(item.tipo==='projecao')return [`Projeção determinística para ${period}`,`Menor saldo e saldo final projetados`,evidence.principalImpacto?`Principal impacto: ${evidence.principalImpacto}`:'Principal impacto não identificado'];
    if(item.tipo==='comprometimento')return [`Compromissos confirmados e planejados de ${period}`,`Histórico disponível: ${analyses.commitment?.evidence?.historyMonths?.length||0} mês(es)`,evidence.principalImpacto?.label?`Principal impacto: ${evidence.principalImpacto.label}`:'Principal impacto não identificado'];
    if(item.tipo==='reserva')return [`${analyses.reserve?.evidence?.historyMonths||0} mês(es) de despesas essenciais`,`${analyses.reserve?.evidence?.accountIds?.length||0} conta(s) e ${analyses.reserve?.evidence?.assetIds?.length||0} ativo(s) marcados como reserva`,`${analyses.reserve?.evidence?.contributionIds?.length||0} aporte(s) ou resgate(s) válidos na janela`];
    if(item.tipo==='qualidade'){const sources=analyses.quality?.evidence?.incomeSources||[];return [`${sources.filter(source=>source.source==='planejamento').length} mês(es) com renda planejada`,`${sources.filter(source=>source.source==='receita_materializada').length} mês(es) com receita futura cadastrada`,`${analyses.quality?.evidence?.invalidLinks||0} lançamento(s) com vínculo incompleto`];}
    if(item.tipo==='anomalia')return [`${analyses.anomaly?.evidence?.historyMonths?.length||0} mês(es) comparáveis`,analyses.anomaly?.evidence?.partial?`Comparação limitada até o dia ${analyses.anomaly.evidence.comparedThroughDay}`:'Mês fechado comparado integralmente','Gastos extraordinários separados da comparação'];
    if(item.tipo==='concentracao')return [`${evidence.categorias?.length||0} categoria(s) de maior impacto`,`Despesas realizadas agrupadas por categoria`];
    if(item.tipo==='metas')return ['Saldo inicial e aportes vinculados à meta','Prazo e ritmo necessário cadastrados'];
    return ['Dados financeiros locais cadastrados'];
  }
  function detect(data,options={}){
    const today=options.today||new Date().toISOString().slice(0,10),date=new Date(`${today}T12:00:00`),month=date.getMonth()+1,year=date.getFullYear(),items=[];
    (data.categorias||[]).filter(category=>category.tipo==='Saída'&&category.natureza!=='movimentacao'&&Number(category.orcado||0)>0).forEach(category=>{const b=window.FinTrackCore.budgetSummary(data,category.id,month,year,category.orcado,today);if(b.percentualComprometido>=80)items.push(insight('orcamento',b.percentualComprometido>100?'alta':'media',`Orçamento de ${category.nome}`,`A categoria comprometeu ${b.percentualComprometido}% do limite mensal.`,{categoriaId:category.id,planejado:b.planejado,comprometido:b.comprometido,percentual:b.percentualComprometido},'Revise os lançamentos da categoria e ajuste apenas um planejamento ainda aberto.','atencao'));});
    const overdue=(data.lancamentos||[]).filter(item=>item.status==='Pendente'&&(item.dataVencimento||item.data)<today&&item.tipoOperacao!=='transferencia');if(overdue.length)items.push(insight('atrasos','alta','Vencimentos atrasados',`${overdue.length} compromisso(s) vencido(s) aguardam atualização.`,{quantidade:overdue.length,total:overdue.reduce((sum,item)=>sum+Number(item.valor||0),0),lancamentoIds:overdue.map(item=>item.id)},'Confirme pagamentos ou reprograme os vencimentos com informação real.','atencao'));
    const current=window.FinTrackCore.totals(data,month,year,today),previousDate=new Date(year,month-2,1),previous=window.FinTrackCore.totals(data,previousDate.getMonth()+1,previousDate.getFullYear(),today);if(previous.despesas&&current.despesas>previous.despesas*1.15)items.push(insight('tendencia','media','Despesas em alta',`As despesas realizadas aumentaram ${Math.round((current.despesas/previous.despesas-1)*100)}% ante o mês anterior.`,{atual:current.despesas,anterior:previous.despesas},'Compare as categorias dos dois meses antes de alterar o orçamento.','evolucao'));
    const invested=window.FinTrackCore.totalByNature(data,month,year,'investimento',today,{status:'Pago'});if(current.receitas>0&&invested===0)items.push(insight('investimentos','baixa','Sem aporte no mês','Há receita realizada, mas nenhum aporte pago foi identificado.',{receitas:current.receitas,investimentos:invested,periodo:`${year}-${String(month).padStart(2,'0')}`},'Avalie se o planejamento permite registrar um aporte; não comprometa obrigações prioritárias.','oportunidades'));
    const debts=(data.dividas||[]).filter(item=>Number(item.saldo||0)>0),debtTotal=debts.reduce((sum,item)=>sum+Number(item.saldo||0),0);if(debts.length)items.push(insight('dividas',debtTotal>current.receitas*3?'alta':'media','Dívidas em aberto',`${debts.length} dívida(s) somam saldo devedor relevante.`,{quantidade:debts.length,saldo:debtTotal},'Priorize a dívida de maior custo informado e confira as condições reais com o credor.','atencao'));
    (data.metas||[]).map(goal=>window.GoalService.summary(data,goal,today)).filter(summary=>summary.status==='atrasada').forEach(summary=>items.push(insight('metas','media','Meta atrasada','O aporte médio válido está abaixo do necessário para o prazo.',{metaId:summary.metaId,acumulado:summary.acumulado,aporteMedio:summary.aporteMedio},'Revise prazo ou contribuição planejada sem duplicar aportes já registrados.','oportunidades')));
    const projection=window.ProjectionService.project(data,`${year}-${String(month).padStart(2,'0')}`,3),risk=projection.meses.find(item=>item.alerta);if(risk)items.push(insight('projecao',risk.alerta==='saldo_negativo'?'critica':'alta','Risco na projeção',`A projeção indica ${risk.alerta==='saldo_negativo'?'saldo negativo':'margem reduzida'} em ${risk.mes}.`,{periodo:risk.mes,menorSaldo:risk.menorSaldo,saldoFinal:risk.saldoFinal,principalImpacto:risk.principalImpacto},'Revise primeiro o principal impacto e confirme datas e valores previstos.','previsoes'));
    const period=`${year}-${String(month).padStart(2,'0')}`,analyses={reserve:{confidence:0},quality:{score:0,metrics:[]},anomaly:{confidence:0},linkedQuality:linkedQualityFor(data)};
    if(window.AnalysisService){analyses.commitment=window.AnalysisService.futureCommitment(data,{startMonth:period,months:3});analyses.reserve=window.AnalysisService.emergencyReserve(data,{atDate:today});analyses.quality=window.AnalysisService.dataQuality(data,{startMonth:period,months:3});analyses.anomaly=window.AnalysisService.monthAnomaly(data,{month:period,today});analyses.concentration=window.AnalysisService.expenseConcentration(data,{month:period});const {commitment,reserve,quality,anomaly,concentration}=analyses,worst=commitment.metrics.find(item=>item.commitmentRate>100)||commitment.metrics.find(item=>item.commitmentRate>=80);if(worst)items.push(insight('comprometimento',worst.commitmentRate>100?'critica':'alta','Renda futura comprometida',`${worst.commitmentRate}% da renda de ${worst.month} já está comprometida.`,{periodo:worst.month,total:worst.confirmed+worst.planned+worst.estimated,principalImpacto:worst.principalImpact},'Revise obrigações e planejamento antes de assumir novos compromissos.','previsoes'));if(reserve.status==='critico')items.push(insight('reserva','alta','Reserva abaixo da meta',reserve.summary,{periodo:period,metricas:reserve.metrics},'Revise quais contas, ativos e categorias formam sua reserva.','atencao'));if(quality.status==='critico')items.push(insight('qualidade','media','Projeção com baixa qualidade de dados',quality.summary,{periodo:period,score:quality.score},'Complete receita, vínculos e histórico antes de tomar decisões.','atencao'));if(['atencao','critico'].includes(anomaly.status))items.push(insight('anomalia',anomaly.status==='critico'?'alta':'media','Mês fora do padrão',anomaly.summary,{periodo:period,metricas:anomaly.metrics},'Confira as categorias e gastos extraordinários que explicam a diferença.','evolucao'));if(concentration.status==='critico')items.push(insight('concentracao','media','Gastos concentrados',concentration.summary,{periodo:period,categorias:concentration.evidence.categories},'Revise as categorias de maior impacto.','evolucao'));}
    return items.map(item=>{const enriched={...item,periodo:item.evidencia?.periodo||period,causa:item.evidencia?.principalImpacto||item.titulo,valor:financialValueFor(item),fontes:['FinancialCore','AnalysisService'],confiabilidadeCalculo:calculationReliabilityFor(item),qualidadeDados:evidenceQualityFor(item,analyses,data),limitacao:'Análise determinística baseada apenas nos dados locais cadastrados.'},relevance=relevanceFor(enriched,current.receitas);return {...enriched,confianca:enriched.qualidadeDados,proveniencia:provenanceFor(enriched,analyses),relevancia:relevance.score,fatoresRelevancia:relevance.factors,formulaRelevancia:relevance.formula};}).sort((a,b)=>b.relevancia-a.relevancia||rank[b.severidade]-rank[a.severidade]||b.valor-a.valor||b.qualidadeDados-a.qualidadeDados||a.titulo.localeCompare(b.titulo)).slice(0,options.limit||5);
  }
  window.InsightService={detect};
})();
