(function(){
  'use strict';
  const rank={critica:4,alta:3,media:2,baixa:1};
  const insight=(tipo,severidade,titulo,mensagem,evidencia,acao,categoria)=>({tipo,severidade,titulo,mensagem,evidencia,acao,categoria});
  const confidenceFor=(item,analyses,data)=>{if(['orcamento','atrasos','dividas','investimentos','concentracao'].includes(item.tipo))return 100;if(item.tipo==='tendencia')return 80;if(item.tipo==='reserva')return analyses.reserve.confidence;if(item.tipo==='anomalia')return analyses.anomaly.confidence;if(['projecao','comprometimento','qualidade'].includes(item.tipo)){const period=item.evidencia?.periodo,month=analyses.quality.metrics.find(metric=>metric.month===period);return month?.score??analyses.quality.score;}if(item.tipo==='metas'){const goal=(data.metas||[]).find(candidate=>candidate.id===item.evidencia?.metaId);return Number(goal?.saldoInicial||0)>0?70:90;}return 80;};
  function detect(data,options={}){
    const today=options.today||new Date().toISOString().slice(0,10),date=new Date(`${today}T12:00:00`),month=date.getMonth()+1,year=date.getFullYear(),items=[];
    (data.categorias||[]).filter(category=>category.tipo==='Saída'&&category.natureza!=='movimentacao'&&Number(category.orcado||0)>0).forEach(category=>{const b=window.FinTrackCore.budgetSummary(data,category.id,month,year,category.orcado,today);if(b.percentualComprometido>=80)items.push(insight('orcamento',b.percentualComprometido>100?'alta':'media',`Orçamento de ${category.nome}`,`A categoria comprometeu ${b.percentualComprometido}% do limite mensal.`,{categoriaId:category.id,planejado:b.planejado,comprometido:b.comprometido,percentual:b.percentualComprometido},'Revise os lançamentos da categoria e ajuste apenas um planejamento ainda aberto.','atencao'));});
    const overdue=(data.lancamentos||[]).filter(item=>item.status==='Pendente'&&(item.dataVencimento||item.data)<today&&item.tipoOperacao!=='transferencia');if(overdue.length)items.push(insight('atrasos','alta','Vencimentos atrasados',`${overdue.length} compromisso(s) vencido(s) aguardam atualização.`,{quantidade:overdue.length,total:overdue.reduce((sum,item)=>sum+Number(item.valor||0),0),lancamentoIds:overdue.map(item=>item.id)},'Confirme pagamentos ou reprograme os vencimentos com informação real.','atencao'));
    const current=window.FinTrackCore.totals(data,month,year,today),previousDate=new Date(year,month-2,1),previous=window.FinTrackCore.totals(data,previousDate.getMonth()+1,previousDate.getFullYear(),today);if(previous.despesas&&current.despesas>previous.despesas*1.15)items.push(insight('tendencia','media','Despesas em alta',`As despesas realizadas aumentaram ${Math.round((current.despesas/previous.despesas-1)*100)}% ante o mês anterior.`,{atual:current.despesas,anterior:previous.despesas},'Compare as categorias dos dois meses antes de alterar o orçamento.','evolucao'));
    const invested=window.FinTrackCore.totalByNature(data,month,year,'investimento',today,{status:'Pago'});if(current.receitas>0&&invested===0)items.push(insight('investimentos','baixa','Sem aporte no mês','Há receita realizada, mas nenhum aporte pago foi identificado.',{receitas:current.receitas,investimentos:invested,periodo:`${year}-${String(month).padStart(2,'0')}`},'Avalie se o planejamento permite registrar um aporte; não comprometa obrigações prioritárias.','oportunidades'));
    const debts=(data.dividas||[]).filter(item=>Number(item.saldo||0)>0),debtTotal=debts.reduce((sum,item)=>sum+Number(item.saldo||0),0);if(debts.length)items.push(insight('dividas',debtTotal>current.receitas*3?'alta':'media','Dívidas em aberto',`${debts.length} dívida(s) somam saldo devedor relevante.`,{quantidade:debts.length,saldo:debtTotal},'Priorize a dívida de maior custo informado e confira as condições reais com o credor.','atencao'));
    (data.metas||[]).map(goal=>window.GoalService.summary(data,goal,today)).filter(summary=>summary.status==='atrasada').forEach(summary=>items.push(insight('metas','media','Meta atrasada','O aporte médio válido está abaixo do necessário para o prazo.',{metaId:summary.metaId,acumulado:summary.acumulado,aporteMedio:summary.aporteMedio},'Revise prazo ou contribuição planejada sem duplicar aportes já registrados.','oportunidades')));
    const projection=window.ProjectionService.project(data,`${year}-${String(month).padStart(2,'0')}`,3),risk=projection.meses.find(item=>item.alerta);if(risk)items.push(insight('projecao',risk.alerta==='saldo_negativo'?'critica':'alta','Risco na projeção',`A projeção indica ${risk.alerta==='saldo_negativo'?'saldo negativo':'margem reduzida'} em ${risk.mes}.`,{periodo:risk.mes,menorSaldo:risk.menorSaldo,saldoFinal:risk.saldoFinal,principalImpacto:risk.principalImpacto},'Revise primeiro o principal impacto e confirme datas e valores previstos.','previsoes'));
    if(window.AnalysisService){const period=`${year}-${String(month).padStart(2,'0')}`,commitment=window.AnalysisService.futureCommitment(data,{startMonth:period,months:3}),reserve=window.AnalysisService.emergencyReserve(data,{atDate:today}),quality=window.AnalysisService.dataQuality(data,{startMonth:period,months:3}),anomaly=window.AnalysisService.monthAnomaly(data,{month:period}),concentration=window.AnalysisService.expenseConcentration(data,{month:period}),worst=commitment.metrics.find(item=>item.commitmentRate>100)||commitment.metrics.find(item=>item.commitmentRate>=80);if(worst)items.push(insight('comprometimento',worst.commitmentRate>100?'critica':'alta','Renda futura comprometida',`${worst.commitmentRate}% da renda de ${worst.month} já está comprometida.`,{periodo:worst.month,total:worst.confirmed+worst.planned+worst.estimated,principalImpacto:worst.principalImpact},'Revise obrigações e planejamento antes de assumir novos compromissos.','previsoes'));if(reserve.status==='critico')items.push(insight('reserva','alta','Reserva abaixo da meta',reserve.summary,{periodo:period,metricas:reserve.metrics},'Revise quais contas, ativos e categorias formam sua reserva.','atencao'));if(quality.status==='critico')items.push(insight('qualidade','media','Projeção com baixa confiança',quality.summary,{periodo:period,score:quality.score},'Complete receita, vínculos e histórico antes de tomar decisões.','atencao'));if(['atencao','critico'].includes(anomaly.status))items.push(insight('anomalia',anomaly.status==='critico'?'alta':'media','Mês fora do padrão',anomaly.summary,{periodo:period,metricas:anomaly.metrics},'Confira as categorias e gastos extraordinários que explicam a diferença.','evolucao'));if(concentration.status==='critico')items.push(insight('concentracao','media','Gastos concentrados',concentration.summary,{periodo:period,categorias:concentration.evidence.categories},'Revise as categorias de maior impacto.','evolucao'));}
    const analysisContext=window.AnalysisService?{reserve:window.AnalysisService.emergencyReserve(data,{atDate:today}),quality:window.AnalysisService.dataQuality(data,{startMonth:`${year}-${String(month).padStart(2,'0')}`,months:3}),anomaly:window.AnalysisService.monthAnomaly(data,{month:`${year}-${String(month).padStart(2,'0')}`})}:{reserve:{confidence:0},quality:{score:0,metrics:[]},anomaly:{confidence:0}},priority={projecao:100,atrasos:90,comprometimento:80,reserva:70,qualidade:60,anomalia:50,concentracao:40};return items.map(item=>({...item,periodo:item.evidencia?.periodo||`${year}-${String(month).padStart(2,'0')}`,causa:item.evidencia?.principalImpacto||item.titulo,valor:Number(item.evidencia?.total??item.evidencia?.saldo??item.evidencia?.comprometido??0),fontes:['FinancialCore','AnalysisService'],confianca:confidenceFor(item,analysisContext,data),limitacao:'Análise determinística baseada apenas nos dados locais cadastrados.'})).sort((a,b)=>(priority[b.tipo]||0)-(priority[a.tipo]||0)||rank[b.severidade]-rank[a.severidade]||b.valor-a.valor||b.confianca-a.confianca||a.titulo.localeCompare(b.titulo)).slice(0,options.limit||5);
  }
  window.InsightService={detect};
})();
